/**
 * Auto-generated field mappings for I90UNLOCKED
 *
 * Generated on: 2025-12-16T14:12:35.054Z
 * Total fields: 188
 */

export interface FieldMapping {
  questionId: string;
  pdfField: string;
  type?: string;
  value?: string;
}

export const I90UNLOCKED_AUTO_MAPPINGS: FieldMapping[] = [
  { questionId: "part1.3a.familyName", pdfField: "form1[0].#subform[0].P1_Line3a_FamilyName[0]" },
  { questionId: "part1.3b.givenName", pdfField: "form1[0].#subform[0].P1_Line3b_GivenName[0]" },
  { questionId: "part1.3c.middleName", pdfField: "form1[0].#subform[0].P1_Line3c_MiddleName[0]", type: "checkbox" },
  { questionId: "part1.checkbox4", pdfField: "form1[0].#subform[0].P1_checkbox4[0]", type: "checkbox" },
  { questionId: "part1.checkbox4", pdfField: "form1[0].#subform[0].P1_checkbox4[1]", type: "checkbox" },
  { questionId: "part1.checkbox4", pdfField: "form1[0].#subform[0].P1_checkbox4[2]" },
  { questionId: "part1.6a.inCareofName", pdfField: "form1[0].#subform[0].P1_Line6a_InCareofName[0]" },
  { questionId: "part1.6b.streetNumberName", pdfField: "form1[0].#subform[0].P1_Line6b_StreetNumberName[0]" },
  { questionId: "part1.6c.aptSteFlrNumber", pdfField: "form1[0].#subform[0].P1_Line6c_AptSteFlrNumber[0]" },
  { questionId: "part1.6d.cityOrTown", pdfField: "form1[0].#subform[0].P1_Line6d_CityOrTown[0]" },
  { questionId: "part1.6h.postalCode", pdfField: "form1[0].#subform[0].P1_Line6h_PostalCode[0]" },
  { questionId: "part1.6f.zipCode", pdfField: "form1[0].#subform[0].P1_Line6f_ZipCode[0]" },
  { questionId: "part1.6e.state", pdfField: "form1[0].#subform[0].P1_Line6e_State[0]" },
  { questionId: "part1.6i.country", pdfField: "form1[0].#subform[0].P1_Line6i_Country[0]" },
  { questionId: "part1.5a.familyName", pdfField: "form1[0].#subform[0].P1_Line5a_FamilyName[0]" },
  { questionId: "part1.5b.givenName", pdfField: "form1[0].#subform[0].P1_Line5b_GivenName[0]" },
  { questionId: "part1.5c.middleName", pdfField: "form1[0].#subform[0].P1_Line5c_MiddleName[0]" },
  { questionId: "part1.2.acctIdentifier", pdfField: "form1[0].#subform[0].P1_Line2_AcctIdentifier[0]" },
  { questionId: "part1.6g.province", pdfField: "form1[0].#subform[0].P1_Line6g_Province[0]" },
  { questionId: "#area[1].p1.line1.aliennumber", pdfField: "form1[0].#subform[0].#area[1].P1_Line1_AlienNumber[0]", type: "checkbox" },
  { questionId: "part1.checkbox6c_Unit", pdfField: "form1[0].#subform[0].P1_checkbox6c_Unit[0]", type: "checkbox" },
  { questionId: "part1.checkbox6c_Unit", pdfField: "form1[0].#subform[0].P1_checkbox6c_Unit[1]", type: "checkbox" },
  { questionId: "part1.checkbox6c_Unit", pdfField: "form1[0].#subform[0].P1_checkbox6c_Unit[2]" },
  { questionId: "part1.7a.streetNumberName", pdfField: "form1[0].#subform[0].P1_Line7a_StreetNumberName[0]" },
  { questionId: "part1.7c.cityOrTown", pdfField: "form1[0].#subform[0].P1_Line7c_CityOrTown[0]" },
  { questionId: "part1.7e.zipCode", pdfField: "form1[0].#subform[0].P1_Line7e_ZipCode[0]" },
  { questionId: "part1.7b.aptSteFlrNumber", pdfField: "form1[0].#subform[0].P1_Line7b_AptSteFlrNumber[0]" },
  { questionId: "part1.7h.country", pdfField: "form1[0].#subform[0].P1_Line7h_Country[0]" },
  { questionId: "part1.7g.postalCode", pdfField: "form1[0].#subform[0].P1_Line7g_PostalCode[0]" },
  { questionId: "part1.7f.province", pdfField: "form1[0].#subform[0].P1_Line7f_Province[0]", type: "checkbox" },
  { questionId: "part1.checkbox7b_Unit", pdfField: "form1[0].#subform[0].P1_checkbox7b_Unit[0]", type: "checkbox" },
  { questionId: "part1.checkbox7b_Unit", pdfField: "form1[0].#subform[0].P1_checkbox7b_Unit[1]", type: "checkbox" },
  { questionId: "part1.checkbox7b_Unit", pdfField: "form1[0].#subform[0].P1_checkbox7b_Unit[2]" },
  { questionId: "part1.7d.state", pdfField: "form1[0].#subform[0].P1_Line7d_State[0]" },
  { questionId: "part1.9.dateOfBirth", pdfField: "form1[0].#subform[1].P1_Line9_DateOfBirth[0]" },
  { questionId: "part1.10.cityTownOfBirth", pdfField: "form1[0].#subform[1].P1_Line10_CityTownOfBirth[0]" },
  { questionId: "part1.11.countryofBirth", pdfField: "form1[0].#subform[1].P1_Line11_CountryofBirth[0]" },
  { questionId: "part1.16.sSN", pdfField: "form1[0].#subform[1].P1_Line16_SSN[0]" },
  { questionId: "part1.15.dateOfAdmission", pdfField: "form1[0].#subform[1].P1_Line15_DateOfAdmission[0]" },
  { questionId: "part1.14.classOfAdmission", pdfField: "form1[0].#subform[1].P1_Line14_ClassOfAdmission[0]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[0]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[1]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[2]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[3]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[4]" },
  { questionId: "part1.12.motherGivenName", pdfField: "form1[0].#subform[1].P1_Line12_MotherGivenName[0]" },
  { questionId: "part1.13.fatherGivenName", pdfField: "form1[0].#subform[1].P1_Line13_FatherGivenName[0]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[5]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[6]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[7]", type: "checkbox" },
  { questionId: "part1.8.male", pdfField: "form1[0].#subform[1].P1_Line8_male[0]", type: "checkbox" },
  { questionId: "part1.8.female", pdfField: "form1[0].#subform[1].P1_Line8_female[0]", type: "checkbox" },
  { questionId: "part2.checkbox1", pdfField: "form1[0].#subform[1].P2_checkbox1[0]", type: "checkbox" },
  { questionId: "part2.checkbox1", pdfField: "form1[0].#subform[1].P2_checkbox1[1]", type: "checkbox" },
  { questionId: "part2.checkbox1", pdfField: "form1[0].#subform[1].P2_checkbox1[2]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[8]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[9]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[10]", type: "checkbox" },
  { questionId: "part2.checkbox2", pdfField: "form1[0].#subform[1].P2_checkbox2[11]" },
  { questionId: "part2.2h1.cityandState", pdfField: "form1[0].#subform[1].P2_Line2h1_CityandState[0]" },
  { questionId: "part3.1.locationAppliedVisa", pdfField: "form1[0].#subform[2].P3_Line1_LocationAppliedVisa[0]" },
  { questionId: "part3.2.locationIssuedVisa", pdfField: "form1[0].#subform[2].P3_Line2_LocationIssuedVisa[0]", type: "checkbox" },
  { questionId: "part3.checkbox4", pdfField: "form1[0].#subform[2].P3_checkbox4[0]", type: "checkbox" },
  { questionId: "part3.checkbox4", pdfField: "form1[0].#subform[2].P3_checkbox4[1]", type: "checkbox" },
  { questionId: "part3.checkbox5", pdfField: "form1[0].#subform[2].P3_checkbox5[0]", type: "checkbox" },
  { questionId: "part3.checkbox5", pdfField: "form1[0].#subform[2].P3_checkbox5[1]" },
  { questionId: "part3.8.heightFeet", pdfField: "form1[0].#subform[2].P3_Line8_HeightFeet[0]" },
  { questionId: "part3.8.heightInches", pdfField: "form1[0].#subform[2].P3_Line8_HeightInches[0]", type: "checkbox" },
  { questionId: "part2.checkbox3", pdfField: "form1[0].#subform[2].P2_checkbox3[0]", type: "checkbox" },
  { questionId: "part2.checkbox3", pdfField: "form1[0].#subform[2].P2_checkbox3[1]", type: "checkbox" },
  { questionId: "part2.checkbox3", pdfField: "form1[0].#subform[2].P2_checkbox3[2]", type: "checkbox" },
  { questionId: "part2.checkbox3", pdfField: "form1[0].#subform[2].P2_checkbox3[3]", type: "checkbox" },
  { questionId: "part2.checkbox3", pdfField: "form1[0].#subform[2].P2_checkbox3[4]" },
  { questionId: "part3.9.heightInches1", pdfField: "form1[0].#subform[2].P3_Line9_HeightInches1[0]" },
  { questionId: "part3.9.heightInches2", pdfField: "form1[0].#subform[2].P3_Line9_HeightInches2[0]" },
  { questionId: "part3.9.heightInches3", pdfField: "form1[0].#subform[2].P3_Line9_HeightInches3[0]", type: "checkbox" },
  { questionId: "part3.checkbox6", pdfField: "form1[0].#subform[2].P3_checkbox6[0]", type: "checkbox" },
  { questionId: "part3.checkbox6", pdfField: "form1[0].#subform[2].P3_checkbox6[1]", type: "checkbox" },
  { questionId: "part3.checkbox7_Hawaiian", pdfField: "form1[0].#subform[2].P3_checkbox7_Hawaiian[0]", type: "checkbox" },
  { questionId: "part3.checkbox7_Indian", pdfField: "form1[0].#subform[2].P3_checkbox7_Indian[0]", type: "checkbox" },
  { questionId: "part3.checkbox7_White", pdfField: "form1[0].#subform[2].P3_checkbox7_White[0]", type: "checkbox" },
  { questionId: "part3.checkbox7_Asian", pdfField: "form1[0].#subform[2].P3_checkbox7_Asian[0]", type: "checkbox" },
  { questionId: "part3.checkbox7_Black", pdfField: "form1[0].#subform[2].P3_checkbox7_Black[0]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[0]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[1]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[2]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[3]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[4]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[5]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[6]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[7]", type: "checkbox" },
  { questionId: "part3.checkbox10", pdfField: "form1[0].#subform[2].P3_checkbox10[8]" },
  { questionId: "part3.3a1.cityandState", pdfField: "form1[0].#subform[2].P3_Line3a1_CityandState[0]" },
  { questionId: "part3.3a.destination", pdfField: "form1[0].#subform[2].P3_Line3a_Destination[0]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[0]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[1]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[2]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[3]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[4]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[5]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[6]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[7]", type: "checkbox" },
  { questionId: "part3.checkbox11", pdfField: "form1[0].#subform[2].P3_checkbox11[8]", type: "checkbox" },
  { questionId: "part4.checkbox1", pdfField: "form1[0].#subform[2].P4_checkbox1[0]", type: "checkbox" },
  { questionId: "part4.checkbox1", pdfField: "form1[0].#subform[2].P4_checkbox1[1]", type: "checkbox" },
  { questionId: "part4.checkbox1a", pdfField: "form1[0].#subform[2].P4_checkbox1a[0]" },
  { questionId: "part4.1a.accomodationRequested", pdfField: "form1[0].#subform[2].P4_Line1a_AccomodationRequested[0]", type: "checkbox" },
  { questionId: "part4.checkbox1b", pdfField: "form1[0].#subform[3].P4_checkbox1b[0]" },
  { questionId: "part4.1b.accomodationRequested", pdfField: "form1[0].#subform[3].P4_Line1b_AccomodationRequested[0]", type: "checkbox" },
  { questionId: "part4.checkbox1c", pdfField: "form1[0].#subform[3].P4_checkbox1c[0]" },
  { questionId: "part4.1c.accomodationRequested", pdfField: "form1[0].#subform[3].P4_Line1c_AccomodationRequested[0]", type: "checkbox" },
  { questionId: "p5.checkbox1b", pdfField: "form1[0].#subform[3].P5_Checkbox1b[0]" },
  { questionId: "part5.1b.language", pdfField: "form1[0].#subform[3].P5_Line1b_Language[0]", type: "checkbox" },
  { questionId: "p5.checkbox1a", pdfField: "form1[0].#subform[3].P5_Checkbox1a[0]", type: "checkbox" },
  { questionId: "p5.checkbox2", pdfField: "form1[0].#subform[3].P5_Checkbox2[0]" },
  { questionId: "part5.2.nameofRepresentative", pdfField: "form1[0].#subform[3].P5_Line2_NameofRepresentative[0]" },
  { questionId: "part5.5.emailAddress", pdfField: "form1[0].#subform[3].P5_Line5_EmailAddress[0]" },
  { questionId: "part5.3.daytimePhoneNumber", pdfField: "form1[0].#subform[3].P5_Line3_DaytimePhoneNumber[0]" },
  { questionId: "part5.4.mobilePhoneNumber", pdfField: "form1[0].#subform[3].P5_Line4_MobilePhoneNumber[0]" },
  { questionId: "part5.6b.dateofSignature", pdfField: "form1[0].#subform[3].P5_Line6b_DateofSignature[0]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[3].P5_Line6a_SignatureofApplicant[0]" },
  { questionId: "part6.1b.interpretersGivenName", pdfField: "form1[0].#subform[4].P6_Line1b_InterpretersGivenName[0]" },
  { questionId: "part6.1a.interpretersFamilyName", pdfField: "form1[0].#subform[4].P6_Line1a_InterpretersFamilyName[0]" },
  { questionId: "part6.2.nameofBusinessor", pdfField: "form1[0].#subform[4].P6_Line2_NameofBusinessor[0]" },
  { questionId: "part6.3c.cityTown", pdfField: "form1[0].#subform[4].P6_Line3c_CityTown[0]" },
  { questionId: "part6.3a.streetNumberName", pdfField: "form1[0].#subform[4].P6_Line3a_StreetNumberName[0]" },
  { questionId: "part6.3b.aptSteFlrNumber", pdfField: "form1[0].#subform[4].P6_Line3b_AptSteFlrNumber[0]" },
  { questionId: "part6.3f.province", pdfField: "form1[0].#subform[4].P6_Line3f_Province[0]" },
  { questionId: "part6.3e.zipCode", pdfField: "form1[0].#subform[4].P6_Line3e_ZipCode[0]" },
  { questionId: "part6.3d.state", pdfField: "form1[0].#subform[4].P6_Line3d_State[0]" },
  { questionId: "part6.3h.country", pdfField: "form1[0].#subform[4].P6_Line3h_Country[0]" },
  { questionId: "part6.3g.postalCode", pdfField: "form1[0].#subform[4].P6_Line3g_PostalCode[0]", type: "checkbox" },
  { questionId: "part6.checkbox3b_Unit", pdfField: "form1[0].#subform[4].P6_checkbox3b_Unit[0]", type: "checkbox" },
  { questionId: "part6.checkbox3b_Unit", pdfField: "form1[0].#subform[4].P6_checkbox3b_Unit[1]", type: "checkbox" },
  { questionId: "part6.checkbox3b_Unit", pdfField: "form1[0].#subform[4].P6_checkbox3b_Unit[2]" },
  { questionId: "part6.5.interpretersEmailAddress", pdfField: "form1[0].#subform[4].P6_Line5_InterpretersEmailAddress[0]" },
  { questionId: "part6.4.interpretersDaytimePhoneNumber", pdfField: "form1[0].#subform[4].P6_Line4_InterpretersDaytimePhoneNumber[0]" },
  { questionId: "part6.4.interpretersDaytimePhoneNumber", pdfField: "form1[0].#subform[4].P6_Line4_InterpretersDaytimePhoneNumber[1]" },
  { questionId: "p6.language", pdfField: "form1[0].#subform[4].P6_Language[0]" },
  { questionId: "part6.6b.dateofSignature", pdfField: "form1[0].#subform[4].P6_Line6b_DateofSignature[0]" },
  { questionId: "part6.6a.signature", pdfField: "form1[0].#subform[4].P6_Line6a_Signature[0]" },
  { questionId: "part7.1a.familyName", pdfField: "form1[0].#subform[4].P7_Line1a_FamilyName[0]" },
  { questionId: "part7.1b.preparersGivenName", pdfField: "form1[0].#subform[4].P7_Line1b_PreparersGivenName[0]" },
  { questionId: "part7.2.nameofBusinessor", pdfField: "form1[0].#subform[4].P7_Line2_NameofBusinessor[0]" },
  { questionId: "part7.3c.cityTown", pdfField: "form1[0].#subform[4].P7_Line3c_CityTown[0]" },
  { questionId: "part7.3a.streetNumberName", pdfField: "form1[0].#subform[4].P7_Line3a_StreetNumberName[0]" },
  { questionId: "part7.3b.aptSteFlrNumber", pdfField: "form1[0].#subform[4].P7_Line3b_AptSteFlrNumber[0]" },
  { questionId: "part7.3f.province", pdfField: "form1[0].#subform[4].P7_Line3f_Province[0]" },
  { questionId: "part7.3e.zipCode", pdfField: "form1[0].#subform[4].P7_Line3e_ZipCode[0]" },
  { questionId: "part7.3d.state", pdfField: "form1[0].#subform[4].P7_Line3d_State[0]" },
  { questionId: "part7.3h.country", pdfField: "form1[0].#subform[4].P7_Line3h_Country[0]" },
  { questionId: "part7.3g.postalCode", pdfField: "form1[0].#subform[4].P7_Line3g_PostalCode[0]", type: "checkbox" },
  { questionId: "part7.checkbox3b_Unit", pdfField: "form1[0].#subform[4].P7_checkbox3b_Unit[0]", type: "checkbox" },
  { questionId: "part7.checkbox3b_Unit", pdfField: "form1[0].#subform[4].P7_checkbox3b_Unit[1]", type: "checkbox" },
  { questionId: "part7.checkbox3b_Unit", pdfField: "form1[0].#subform[4].P7_checkbox3b_Unit[2]" },
  { questionId: "part7.6.preparersEmailAddress", pdfField: "form1[0].#subform[4].P7_Line6_PreparersEmailAddress[0]" },
  { questionId: "part7.4.preparersDaytimePhoneNumber", pdfField: "form1[0].#subform[4].P7_Line4_PreparersDaytimePhoneNumber[0]" },
  { questionId: "part7.5.preparersFaxNumber", pdfField: "form1[0].#subform[4].P7_Line5_PreparersFaxNumber[0]", type: "checkbox" },
  { questionId: "part7.checkbox7", pdfField: "form1[0].#subform[5].P7_checkbox7[0]", type: "checkbox" },
  { questionId: "part7.checkbox7", pdfField: "form1[0].#subform[5].P7_checkbox7[1]", type: "checkbox" },
  { questionId: "part7.checkbox7Extend", pdfField: "form1[0].#subform[5].P7_checkbox7Extend[0]", type: "checkbox" },
  { questionId: "part7.checkbox7Extend", pdfField: "form1[0].#subform[5].P7_checkbox7Extend[1]" },
  { questionId: "part7.8a.signatureofPreparer", pdfField: "form1[0].#subform[5].P7_Line8a_SignatureofPreparer[0]" },
  { questionId: "part7.8b.dateofSignature", pdfField: "form1[0].#subform[5].P7_Line8b_DateofSignature[0]" },
  { questionId: "part8.3d.additionalInfo", pdfField: "form1[0].#subform[6].P8_Line3d_AdditionalInfo[0]" },
  { questionId: "part8.5a.pageNumber", pdfField: "form1[0].#subform[6].P8_Line5a_PageNumber[0]" },
  { questionId: "part8.5b.partNumber", pdfField: "form1[0].#subform[6].P8_Line5b_PartNumber[0]" },
  { questionId: "part8.5c.itemNumber", pdfField: "form1[0].#subform[6].P8_Line5c_ItemNumber[0]" },
  { questionId: "part8.5d.additionalInfo", pdfField: "form1[0].#subform[6].P8_Line5d_AdditionalInfo[0]" },
  { questionId: "part8.4d.additionalInfo", pdfField: "form1[0].#subform[6].P8_Line4d_AdditionalInfo[0]" },
  { questionId: "part8.3a.pageNumber", pdfField: "form1[0].#subform[6].P8_Line3a_PageNumber[0]" },
  { questionId: "part8.3b.partNumber", pdfField: "form1[0].#subform[6].P8_Line3b_PartNumber[0]" },
  { questionId: "part8.3c.itemNumber", pdfField: "form1[0].#subform[6].P8_Line3c_ItemNumber[0]" },
  { questionId: "part8.4a.pageNumber", pdfField: "form1[0].#subform[6].P8_Line4a_PageNumber[0]" },
  { questionId: "part8.4b.partNumber", pdfField: "form1[0].#subform[6].P8_Line4b_PartNumber[0]" },
  { questionId: "part8.4c.itemNumber", pdfField: "form1[0].#subform[6].P8_Line4c_ItemNumber[0]" },
  { questionId: "part1.3a.familyName", pdfField: "form1[0].#subform[6].P1_Line3a_FamilyName[1]" },
  { questionId: "part1.3b.givenName", pdfField: "form1[0].#subform[6].P1_Line3b_GivenName[1]" },
  { questionId: "part1.3c.middleName", pdfField: "form1[0].#subform[6].P1_Line3c_MiddleName[1]" },
  { questionId: "part8.5a.pageNumber", pdfField: "form1[0].#subform[6].P8_Line5a_PageNumber[1]" },
  { questionId: "part8.5b.partNumber", pdfField: "form1[0].#subform[6].P8_Line5b_PartNumber[1]" },
  { questionId: "part8.5c.itemNumber", pdfField: "form1[0].#subform[6].P8_Line5c_ItemNumber[1]" },
  { questionId: "part8.5d.additionalInfo", pdfField: "form1[0].#subform[6].P8_Line5d_AdditionalInfo[1]" },
  { questionId: "part8.5a.pageNumber", pdfField: "form1[0].#subform[6].P8_Line5a_PageNumber[2]" },
  { questionId: "part8.5b.partNumber", pdfField: "form1[0].#subform[6].P8_Line5b_PartNumber[2]" },
  { questionId: "part8.5c.itemNumber", pdfField: "form1[0].#subform[6].P8_Line5c_ItemNumber[2]" },
  { questionId: "part8.5d.additionalInfo", pdfField: "form1[0].#subform[6].P8_Line5d_AdditionalInfo[2]" },
  { questionId: "#area[3].p1.line1.aliennumber", pdfField: "form1[0].#subform[6].#area[3].P1_Line1_AlienNumber[1]" },
];
