/**
 * N-400 Field Mappings
 * Generated: 2025-12-29T21:22:30.551Z
 */

export interface FieldMapping {
  questionId: string;
  pdfField: string;
  type?: string;
  value?: string;
}

export const N_400_FIELD_MAPPINGS: FieldMapping[] = [
  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[0]",
    type: "radio",
    value: "A",
  },
  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[1]",
    type: "radio",
    value: "B",
  },
  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[2]",
    type: "radio",
    value: "C",
  },

  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[3]",
    type: "choice",
    value: "D",
  },

  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[4]",
    type: "radio",
    value: "E",
  },
  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[6]",
    type: "radio",
    value: "F",
  },
  {
    questionId: "part1.eligibility",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[5]",
    type: "radio",
    value: "G",
  },

  {
    questionId: "part1.eligibilityHonorableMilitaryService",
    pdfField: "form1[0].#subform[0].Part1_Eligibility[6]",
    type: "text",
  },
  {
    questionId: "part1.alienNumber",
    pdfField: "form1[0].#subform[0].#area[0].Line1_AlienNumber[0]",
    type: "text",
  },

  {
    questionId: "part1.otherReasonForFiling",
    pdfField: "form1[0].#subform[0].Part1Line5_OtherExplain[0]",
    type: "text",
  },

  {
    questionId: "part1.fieldOfficeSelection",
    pdfField: "form1[0].#subform[0].DropDownList1[0]",
    type: "text",
  },
  {
    questionId: "part2.middleName",
    pdfField: "form1[0].#subform[0].P2_Line1_MiddleName[0]",
    type: "text",
  },
  {
    questionId: "part2.givenName",
    pdfField: "form1[0].#subform[0].P2_Line1_GivenName[0]",
    type: "text",
  },
  {
    questionId: "part2.familyName",
    pdfField: "form1[0].#subform[0].P2_Line1_FamilyName[0]",
    type: "text",
  },
  {
    questionId: "part2.otherNamesUsedMiddleName2",
    pdfField: "form1[0].#subform[0].Line3_MiddleName2[0]",
    type: "text",
  },
  {
    questionId: "part2.otherNamesUsedGivenName2",
    pdfField: "form1[0].#subform[0].Line3_GivenName2[0]",
    type: "text",
  },
  {
    questionId: "part2.otherNamesUsedMiddleName1",
    pdfField: "form1[0].#subform[0].Line3_MiddleName1[0]",
    type: "text",
  },
  {
    questionId: "part2.otherNamesUsedGivenName1",
    pdfField: "form1[0].#subform[0].Line3_GivenName1[0]",
    type: "text",
  },
  {
    questionId: "part2.otherNamesUsedFamilyName1",
    pdfField: "form1[0].#subform[0].Line2_FamilyName1[0]",
    type: "text",
  },
  {
    questionId: "part2.otherNamesUsedFamilyName2",
    pdfField: "form1[0].#subform[0].Line2_FamilyName2[0]",
    type: "text",
  },
  {
    questionId: "part1.alienNumber",
    pdfField: "form1[0].#subform[1].#area[1].Line1_AlienNumber[1]",
    type: "text",
  },
  {
    questionId: "part2.dateOfBirth",
    pdfField: "form1[0].#subform[1].P2_Line8_DateOfBirth[0]",
    type: "button",
  },
  {
    questionId: "part2.gender",
    pdfField: "form1[0].#subform[1].P2_Line7_Gender[0]",
    type: "radio",
    value: "M",
  },
  {
    questionId: "part2.gender",
    pdfField: "form1[0].#subform[1].P2_Line7_Gender[1]",
    type: "text",
    value: "F",
  },
  {
    questionId: "part2.uscisOnlineAccountNumber",
    pdfField: "form1[0].#subform[1].P2_Line6_USCISELISAcctNumber[0]",
    type: "text",
  },
  {
    questionId: "part2.dateBecamePermanentResident",
    pdfField: "form1[0].#subform[1].P2_Line9_DateBecamePermanentResident[0]",
    type: "text",
  },
  {
    questionId: "part2.countryOfNationality",
    pdfField: "form1[0].#subform[1].P2_Line11_CountryOfNationality[0]",
    type: "button",
  },
  {
    questionId: "part2.parentUsCitizen",
    pdfField: "form1[0].#subform[1].P2_Line10_claimdisability[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part2.parentUsCitizen",
    pdfField: "form1[0].#subform[1].P2_Line10_claimdisability[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part2.socialSecurityUpdate",
    pdfField: "form1[0].#subform[1].Line12a_Checkbox[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part2.socialSecurityUpdate",
    pdfField: "form1[0].#subform[1].Line12a_Checkbox[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part2.socialSecurityNumber",
    pdfField: "form1[0].#subform[1].Line12b_SSN[0]",
    type: "button",
  },
  {
    questionId: "part2.consentForDisclosure",
    pdfField: "form1[0].#subform[1].Line12\\.c_Checkbox[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part2.consentForDisclosure",
    pdfField: "form1[0].#subform[1].Line12\\.c_Checkbox[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part2.disabilityClaim",
    pdfField: "form1[0].#subform[1].P2_Line11_claimdisability[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part2.disabilityClaim",
    pdfField: "form1[0].#subform[1].P2_Line11_claimdisability[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part2.countryOfBirth",
    pdfField: "form1[0].#subform[1].P2_Line10_CountryOfBirth[0]",
    type: "text",
  },
  {
    questionId: "part2.middleNameChange",
    pdfField: "form1[0].#subform[1].Part2Line4a_MiddleName[0]",
    type: "text",
  },
  {
    questionId: "part2.givenNameChange",
    pdfField: "form1[0].#subform[1].Part2Line4a_GivenName[0]",
    type: "button",
  },
  {
    questionId: "part2.nameChange",
    pdfField: "form1[0].#subform[1].P2_Line34_NameChange[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part2.nameChange",
    pdfField: "form1[0].#subform[1].P2_Line34_NameChange[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part2.familyNameChange",
    pdfField: "form1[0].#subform[1].Part2Line3_FamilyName[0]",
    type: "text",
  },
  {
    questionId: "part1.alienNumber",
    pdfField: "form1[0].#subform[2].#area[2].Line1_AlienNumber[2]",
    type: "button",
  },
  {
    questionId: "part4.race",
    pdfField: "form1[0].#subform[2].P7_Line2_Race[0]",
    type: "select",
    value: "0",
  },
  {
    questionId: "part4.race",
    pdfField: "form1[0].#subform[2].P7_Line2_Race[1]",
    type: "select",
    value: "1",
  },
  {
    questionId: "part4.race",
    pdfField: "form1[0].#subform[2].P7_Line2_Race[2]",
    type: "select",
    value: "2",
  },
  {
    questionId: "part4.race",
    pdfField: "form1[0].#subform[2].P7_Line2_Race[3]",
    type: "select",
    value: "3",
  },
  {
    questionId: "part4.race",
    pdfField: "form1[0].#subform[2].P7_Line2_Race[4]",
    type: "select",
    value: "4",
  },
  {
    questionId: "part4.ethnicity",
    pdfField: "form1[0].#subform[2].P7_Line1_Ethnicity[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part4.ethnicity",
    pdfField: "form1[0].#subform[2].P7_Line1_Ethnicity[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part4.weightSecondDigit",
    pdfField: "form1[0].#subform[2].P7_Line4_Pounds2[0]",
    type: "choice",
  },
  {
    questionId: "part4.heightFeet",
    pdfField: "form1[0].#subform[2].P7_Line3_HeightFeet[0]",
    type: "select",
  },
  {
    questionId: "part4.heightInches",
    pdfField: "form1[0].#subform[2].P7_Line3_HeightInches[0]",
    type: "select",
  },
  {
    questionId: "part4.weightPoundsFirstDigit",
    pdfField: "form1[0].#subform[2].P7_Line4_Pounds1[0]",
    type: "text",
  },
  {
    questionId: "part4.weightPoundsThirdDigit",
    pdfField: "form1[0].#subform[2].P7_Line4_Pounds3[0]",
    type: "button",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[0]",
    type: "radio",
    value: "BRO",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[1]",
    type: "radio",
    value: "BLU",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[2]",
    type: "radio",
    value: "GRN",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[3]",
    type: "radio",
    value: "HAZ",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[4]",
    type: "radio",
    value: "GRY",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[5]",
    type: "radio",
    value: "BLK",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[6]",
    type: "radio",
    value: "PNK",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[7]",
    type: "radio",
    value: "MAR",
  },
  {
    questionId: "part4.eyeColor",
    pdfField: "form1[0].#subform[2].P7_Line5_Eye[8]",
    type: "radio",
    value: "XXX",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[0]",
    type: "radio",
    value: "BAL",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[1]",
    type: "radio",
    value: "SDY",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[2]",
    type: "radio",
    value: "RED",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[3]",
    type: "radio",
    value: "WHI",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[4]",
    type: "radio",
    value: "GRY",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[5]",
    type: "radio",
    value: "BLN",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[6]",
    type: "radio",
    value: "BRO",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[7]",
    type: "radio",
    value: "BLK",
  },
  {
    questionId: "part4.hairColor",
    pdfField: "form1[0].#subform[2].P7_Line6_Hair[8]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddressLine1",
    pdfField: "form1[0].#subform[2].P4_Line3_PhysicalAddress1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddressLine2",
    pdfField: "form1[0].#subform[2].P4_Line3_PhysicalAddress2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddressLine3",
    pdfField: "form1[0].#subform[2].P4_Line3_PhysicalAddress3[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line3.cityTown",
    pdfField: "form1[0].#subform[2].P4_Line3_CityTown3[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line2.cityTown",
    pdfField: "form1[0].#subform[2].P4_Line3_CityTown2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line1.cityTown",
    pdfField: "form1[0].#subform[2].P4_Line3_CityTown1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line1.fromDate",
    pdfField: "form1[0].#subform[2].P4_Line3_From1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line2.fromDate",
    pdfField: "form1[0].#subform[2].P4_Line3_From2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line3.fromDate",
    pdfField: "form1[0].#subform[2].P4_Line3_From3[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line1.toDate",
    pdfField: "form1[0].#subform[2].P4_Line3_To1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line2.toDate",
    pdfField: "form1[0].#subform[2].P4_Line3_To2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line3.toDate",
    pdfField: "form1[0].#subform[2].P4_Line3_To3[0]",
    type: "button",
  },
  {
    questionId: "part3.currentPhysicalAddressMailingAddress",
    pdfField: "form1[0].#subform[2].Pt3_Line2a_Checkbox[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part3.currentPhysicalAddressMailingAddress",
    pdfField: "form1[0].#subform[2].Pt3_Line2a_Checkbox[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part3.physicalAddresses.line1.zipCode",
    pdfField: "form1[0].#subform[2].P4_Line3_ZipCode1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line2.zipCode",
    pdfField: "form1[0].#subform[2].P4_Line3_ZipCode2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line3.zipCode",
    pdfField: "form1[0].#subform[2].P4_Line3_ZipCode3[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line1.state",
    pdfField: "form1[0].#subform[2].P4_Line3_State1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line2.state",
    pdfField: "form1[0].#subform[2].P4_Line3_State2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line3.state",
    pdfField: "form1[0].#subform[2].P4_Line3_State3[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line1.country",
    pdfField: "form1[0].#subform[2].P4_Line3_Country1[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line2.country",
    pdfField: "form1[0].#subform[2].P4_Line3_Country2[0]",
    type: "text",
  },
  {
    questionId: "part3.physicalAddresses.line3.country",
    pdfField: "form1[0].#subform[2].P4_Line3_Country3[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.city",
    pdfField: "form1[0].#subform[2].P4_Line1_City[0]",
    type: "choice",
  },
  {
    questionId: "part3.currentMailingAddress.state",
    pdfField: "form1[0].#subform[2].P4_Line1_State[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.zipCode",
    pdfField: "form1[0].#subform[2].P4_Line1_ZipCode[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.postalCode",
    pdfField: "form1[0].#subform[2].P4_Line1_PostalCode[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.province",
    pdfField: "form1[0].#subform[2].P4_Line1_Province[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.streetName",
    pdfField: "form1[0].#subform[2].P4_Line1_StreetName[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.inCareOfName",
    pdfField: "form1[0].#subform[2].P4_Line1_InCareOfName[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.apartmentSuiteFloorNumber",
    pdfField: "form1[0].#subform[2].P4_Line1_Number[0]",
    type: "button",
  },
  {
    questionId: "part3.currentMailingAddress.unit",
    pdfField: "form1[0].#subform[2].P4_Line1_Unit[0]",
    type: "radio",
    value: "FLR",
  },
  {
    questionId: "part3.currentMailingAddress.unit",
    pdfField: "form1[0].#subform[2].P4_Line1_Unit[1]",
    type: "radio",
    value: "STE",
  },
  {
    questionId: "part3.currentMailingAddress.unit",
    pdfField: "form1[0].#subform[2].P4_Line1_Unit[2]",
    type: "text",
  },
  {
    questionId: "part3.datesOfResidence",
    pdfField: "form1[0].#subform[2].P4_Line1_DatesofResidence[0]",
    type: "text",
  },
  // {
  //   questionId: "part3.datesOfResidence",
  //   pdfField: "form1[0].#subform[2].P4_Line1_DatesofResidence[1]",
  //   type: "text",
  // },
  {
    questionId: "part3.physicalAddresses.fromDate",
    pdfField: "form1[0].#subform[2].P4_Line3_From1[1]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.country",
    pdfField: "form1[0].#subform[2].P4_Line1_Country[0]",
    type: "text",
  },
  {
    questionId: "page2.alienRegistrationNumber",
    pdfField: "form1[0].#subform[3].#area[3].Line1_AlienNumber[3]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.cityOrTown",
    pdfField: "form1[0].#subform[3].P5_Line1b_City[0]",
    type: "choice",
  },
  {
    questionId: "part3.currentMailingAddress.state",
    pdfField: "form1[0].#subform[3].P4_Line1_State[1]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.zipCode",
    pdfField: "form1[0].#subform[3].P5_Line1b_ZipCode[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.postalCode",
    pdfField: "form1[0].#subform[3].P5_Line1b_PostalCode[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.provinceOrRegion",
    pdfField: "form1[0].#subform[3].P5_Line1b_Province[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.streetNumberAndName",
    pdfField: "form1[0].#subform[3].P5_Line1b_StreetName[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.inCareOfName",
    pdfField: "form1[0].#subform[3].P5_Line1b_InCareOfName[0]",
    type: "text",
  },
  {
    questionId: "part3.currentMailingAddress.apartmentSuiteFloorNumber",
    pdfField: "form1[0].#subform[3].P5_Line1b_Number[0]",
    type: "button",
  },
  {
    questionId: "part3.currentMailingAddress.unit",
    pdfField: "form1[0].#subform[3].P5_Line1b_Unit[0]",
    type: "radio",
    value: "FLR",
  },
  {
    questionId: "part3.currentMailingAddress.unit",
    pdfField: "form1[0].#subform[3].P5_Line1b_Unit[1]",
    type: "radio",
    value: "STE",
  },
  {
    questionId: "part3.currentMailingAddress.country",
    pdfField: "form1[0].#subform[3].P5_Line1b_Country[0]",
    type: "text",
  },
  {
    questionId: "part7.maritalStatus",
    pdfField: "form1[0].#subform[3].P10_Line1_MaritalStatus[2]",
    type: "radio",
    value: "W",
  },
  {
    questionId: "part7.maritalStatus",
    pdfField: "form1[0].#subform[3].P10_Line1_MaritalStatus[3]",
    type: "radio",
    value: "M",
  },
  {
    questionId: "part7.maritalStatus",
    pdfField: "form1[0].#subform[3].P10_Line1_MaritalStatus[4]",
    type: "radio",
    value: "A",
  },
  {
    questionId: "part7.maritalStatus",
    pdfField: "form1[0].#subform[3].P10_Line1_MaritalStatus[5]",
    type: "radio",
    value: "E",
  },
  {
    questionId: "part7.spouseArmedForces",
    pdfField: "form1[0].#subform[3].P7_Line2_Forces[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part7.spouseArmedForces",
    pdfField: "form1[0].#subform[3].P7_Line2_Forces[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part7.currentSpouseMiddleName",
    pdfField: "form1[0].#subform[3].P10_Line4a_MiddleName[0]",
    type: "text",
  },
  {
    questionId: "part7.currentSpouseGivenName",
    pdfField: "form1[0].#subform[3].P10_Line4a_GivenName[0]",
    type: "text",
  },
  {
    questionId: "part7.currentSpouseFamilyName",
    pdfField: "form1[0].#subform[3].P10_Line4a_FamilyName[0]",
    type: "text",
  },
  {
    questionId: "part7.currentSpouseDateOfBirth",
    pdfField: "form1[0].#subform[3].P10_Line4d_DateofBirth[0]",
    type: "text",
  },
  {
    questionId: "part7.dateEnteredMarriage",
    pdfField: "form1[0].#subform[3].P10_Line4e_DateEnterMarriage[0]",
    type: "text",
  },
  {
    questionId: "part7.spouseSameAddress",
    pdfField: "form1[0].#subform[3].P10_Line5_Citizen[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part7.spouseSameAddress",
    pdfField: "form1[0].#subform[3].P10_Line5_Citizen[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part7.spouseCitizenDate",
    pdfField: "form1[0].#subform[3].P10_Line5b_DateBecame[0]",
    type: "text",
  },
  {
    questionId: "part7.spouseCitizenBy",
    pdfField: "form1[0].#subform[3].P10_Line5a_When[0]",
    type: "radio",
    value: "B",
  },
  {
    questionId: "part7.spouseCitizenBy",
    pdfField: "form1[0].#subform[3].P10_Line5a_When[1]",
    type: "radio",
    value: "O",
  },
  {
    questionId: "page5.alienNumber",
    pdfField: "form1[0].#subform[4].#area[4].Line1_AlienNumber[4]",
    type: "text",
  },
  {
    questionId: "part7.spouseAlienNumber",
    pdfField: "form1[0].#subform[4].#area[5].P7_Line6_ANumber[0]",
    type: "text",
  },
  {
    questionId: "part7.spouseMarriagesCount",
    pdfField: "form1[0].#subform[4].P10_Line4g_Employer[0]",
    type: "text",
  },
  {
    questionId: "part7.spouseEmployer",
    pdfField: "form1[0].#subform[4].TextField1[0]",
    type: "text",
  },
  {
    questionId: "part8.totalChildren",
    pdfField: "form1[0].#subform[4].P11_Line1_TotalChildren[0]",
    type: "text",
  },
  {
    questionId: "part6.child1Name",
    pdfField: "form1[0].#subform[4].P7_EmployerName1[0]",
    type: "text",
  },
  {
    questionId: "part6.child2Name",
    pdfField: "form1[0].#subform[4].P7_EmployerName2[0]",
    type: "text",
  },
  {
    questionId: "part6.child3Name",
    pdfField: "form1[0].#subform[4].P7_EmployerName3[0]",
    type: "text",
  },
  {
    questionId: "part6.child1DateOfBirth",
    pdfField: "form1[0].#subform[4].P7_From1[0]",
    type: "text",
  },
  {
    questionId: "part6.child2DateOfBirth",
    pdfField: "form1[0].#subform[4].P7_From2[0]",
    type: "text",
  },
  {
    questionId: "part6.child3DateOfBirth",
    pdfField: "form1[0].#subform[4].P7_From3[0]",
    type: "text",
  },
  {
    questionId: "part6.child1Residence",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy1[0]",
    type: "text",
  },
  {
    questionId: "part6.child2Residence",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy2[0]",
    type: "text",
  },
  {
    questionId: "part6.child3Residence",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy3[0]",
    type: "text",
  },
  {
    questionId: "part6.child1Relationship",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy1[1]",
    type: "text",
  },
  {
    questionId: "part6.child2Relationship",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy2[1]",
    type: "text",
  },
  {
    questionId: "part6.child3Relationship",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy3[1]",
    type: "text",
  },
  {
    questionId: "part6.child1Support",
    pdfField: "form1[0].#subform[4].P9_Line5a[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part6.child1Support",
    pdfField: "form1[0].#subform[4].P9_Line5a[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part6.child2Support",
    pdfField: "form1[0].#subform[4].P6_ChildTwo[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part6.child2Support",
    pdfField: "form1[0].#subform[4].P6_ChildTwo[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part6.child3Support",
    pdfField: "form1[0].#subform[4].P6_ChildThree[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part6.child3Support",
    pdfField: "form1[0].#subform[4].P6_ChildThree[1]",
    value: "Y",
    type: "radio",
  },
  {
    questionId: "part5.employer1Name",
    pdfField: "form1[0].#subform[4].P5_EmployerName1[0]",
    type: "text",
  },
  {
    questionId: "part5.employer2Name",
    pdfField: "form1[0].#subform[4].P5_EmployerName2[0]",
    type: "text",
  },
  {
    questionId: "part5.employer3Name",
    pdfField: "form1[0].#subform[4].P5_EmployerName3[0]",
    type: "text",
  },
  {
    questionId: "part5.employer3City",
    pdfField: "form1[0].#subform[4].P7_City3[0]",
    type: "text",
  },
  {
    questionId: "part5.employer2City",
    pdfField: "form1[0].#subform[4].P7_City2[0]",
    type: "text",
  },
  {
    questionId: "part5.employer1City",
    pdfField: "form1[0].#subform[4].P7_City1[0]",
    type: "text",
  },
  {
    questionId: "part5.employment1FromDate",
    pdfField: "form1[0].#subform[4].P7_From1[1]",
    type: "text",
  },
  {
    questionId: "part5.employment2FromDate",
    pdfField: "form1[0].#subform[4].P7_From2[1]",
    type: "text",
  },
  {
    questionId: "part5.employment3FromDate",
    pdfField: "form1[0].#subform[4].P7_From3[1]",
    type: "text",
  },
  {
    questionId: "part5.employment2ToDate",
    pdfField: "form1[0].#subform[4].P7_To2[0]",
    type: "text",
  },
  {
    questionId: "part5.employment3ToDate",
    pdfField: "form1[0].#subform[4].P7_To3[0]",
    type: "text",
  },
  {
    questionId: "part5.occupationFieldStudy1",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy1[2]",
    type: "text",
  },
  {
    questionId: "part5.occupationFieldStudy2",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy2[2]",
    type: "text",
  },
  {
    questionId: "part5.occupationFieldStudy3",
    pdfField: "form1[0].#subform[4].P7_OccupationFieldStudy3[2]",
    type: "text",
  },
  {
    questionId: "part5.employerState1",
    pdfField: "form1[0].#subform[4].P7_State1[0]",
    type: "text",
  },
  {
    questionId: "part5.employerState2",
    pdfField: "form1[0].#subform[4].P7_State2[0]",
    type: "text",
  },
  {
    questionId: "part5.employerState3",
    pdfField: "form1[0].#subform[4].P7_State3[0]",
    type: "text",
  },
  {
    questionId: "part5.employerZipCode1",
    pdfField: "form1[0].#subform[4].P7_ZipCode1[0]",
    type: "text",
  },
  {
    questionId: "part5.employerZipCode2",
    pdfField: "form1[0].#subform[4].P7_ZipCode2[0]",
    type: "text",
  },
  {
    questionId: "part5.employerZipCode3",
    pdfField: "form1[0].#subform[4].P7_ZipCode3[0]",
    type: "text",
  },
  {
    questionId: "part5.country3",
    pdfField: "form1[0].#subform[4].P7_Country3[0]",
    type: "text",
  },
  {
    questionId: "part5.country2",
    pdfField: "form1[0].#subform[4].P7_Country2[0]",
    type: "text",
  },
  {
    questionId: "part5.country1",
    pdfField: "form1[0].#subform[4].P7_Country1[0]",
    type: "text",
  },
  {
    questionId: "part6.trip1DateReturn",
    pdfField: "form1[0].#subform[5].P8_Line1_DateReturn1[0]",
    type: "text",
  },
  {
    questionId: "part6.trip3DateReturn",
    pdfField: "form1[0].#subform[5].P8_Line1_DateReturn3[0]",
    type: "text",
  },
  {
    questionId: "part6.trip5DateReturn",
    pdfField: "form1[0].#subform[5].P8_Line1_DateReturn5[0]",
    type: "text",
  },
  {
    questionId: "part6.trip6Countries",
    pdfField: "form1[0].#subform[5].P8_Line1_Countries6[0]",
    type: "text",
  },
  {
    questionId: "part6.trip6DateLeft",
    pdfField: "form1[0].#subform[5].P8_Line1_DateLeft6[0]",
    type: "text",
  },
  {
    questionId: "part6.trip6DateReturn",
    pdfField: "form1[0].#subform[5].P8_Line1_DateReturn6[0]",
    type: "text",
  },
  {
    questionId: "part6.trip5DateLeft",
    pdfField: "form1[0].#subform[5].P8_Line1_DateLeft5[0]",
    type: "text",
  },
  {
    questionId: "part6.trip5Countries",
    pdfField: "form1[0].#subform[5].P8_Line1_Countries5[0]",
    type: "text",
  },
  {
    questionId: "part6.trip4Countries",
    pdfField: "form1[0].#subform[5].P8_Line1_Countries4[0]",
    type: "text",
  },
  {
    questionId: "part6.trip4DateLeft",
    pdfField: "form1[0].#subform[5].P8_Line1_DateLeft4[0]",
    type: "text",
  },
  {
    questionId: "part6.trip4DateReturn",
    pdfField: "form1[0].#subform[5].P8_Line1_DateReturn4[0]",
    type: "text",
  },
  {
    questionId: "part6.trip3DateLeft",
    pdfField: "form1[0].#subform[5].P8_Line1_DateLeft3[0]",
    type: "text",
  },
  {
    questionId: "part6.trip3Countries",
    pdfField: "form1[0].#subform[5].P8_Line1_Countries3[0]",
    type: "text",
  },
  {
    questionId: "part6.tripTwoCountriesTraveled",
    pdfField: "form1[0].#subform[5].P8_Line1_Countries2[0]",
    type: "text",
  },
  {
    questionId: "part6.tripTwoDateLeft",
    pdfField: "form1[0].#subform[5].P8_Line1_DateLeft2[0]",
    type: "text",
  },
  {
    questionId: "part6.tripTwoDateReturned",
    pdfField: "form1[0].#subform[5].P8_Line1_DateReturn2[0]",
    type: "text",
  },
  {
    questionId: "part6.tripOneDateLeft",
    pdfField: "form1[0].#subform[5].P8_Line1_DateLeft1[0]",
    type: "text",
  },
  {
    questionId: "part6.tripOneCountriesTraveled",
    pdfField: "form1[0].#subform[5].P9_Line1_Countries1[0]",
    type: "text",
  },
  {
    questionId: "page5.alienRegistrationNumber",
    pdfField: "form1[0].#subform[5].#area[6].Line1_AlienNumber[5]",
    type: "button",
  },
  {
    questionId: "part9.registeredToVote",
    pdfField: "form1[0].#subform[5].P9_Line2[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.registeredToVote",
    pdfField: "form1[0].#subform[5].P9_Line2[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.claimedUSCitizen",
    pdfField: "form1[0].#subform[5].P9_Line1[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.claimedUSCitizen",
    pdfField: "form1[0].#subform[5].P9_Line1[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.oweOverdueTaxes",
    pdfField: "form1[0].#subform[5].P9_Line3[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.oweOverdueTaxes",
    pdfField: "form1[0].#subform[5].P9_Line3[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.calledNonUSResident",
    pdfField: "form1[0].#subform[5].P9_Line4[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.calledNonUSResident",
    pdfField: "form1[0].#subform[5].P9_Line4[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.communistPartyMember",
    pdfField: "form1[0].#subform[5].P9_5a[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.communistPartyMember",
    pdfField: "form1[0].#subform[5].P9_5a[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.groupOppositionToGovernment",
    pdfField: "form1[0].#subform[5].P9_5b[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.groupOppositionToGovernment",
    pdfField: "form1[0].#subform[5].P9_5b[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.groupUsedWeapon",
    pdfField: "form1[0].#subform[6].P12_6a[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.groupUsedWeapon",
    pdfField: "form1[0].#subform[6].P12_6a[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.groupEngagedInKidnapping",
    pdfField: "form1[0].#subform[6].P12_6b[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.groupEngagedInKidnapping",
    pdfField: "form1[0].#subform[6].P12_6b[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.groupThreatenedActs",
    pdfField: "form1[0].#subform[6].P12_6c[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.groupThreatenedActs",
    pdfField: "form1[0].#subform[6].P12_6c[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.torture",
    pdfField: "form1[0].#subform[6].P9_Line7a[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.torture",
    pdfField: "form1[0].#subform[6].P9_Line7a[1]",
    type: "radio",
  },
  {
    questionId: "part9.genocide",
    pdfField: "form1[0].#subform[6].P9_Line7\\.b\\.[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.genocide",
    pdfField: "form1[0].#subform[6].P9_Line7\\.b\\.[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.killing",
    pdfField: "form1[0].#subform[6].P9_Line7\\.c[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.killing",
    pdfField: "form1[0].#subform[6].P9_Line7\\.c[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.sexualContact",
    pdfField: "form1[0].#subform[6].P9_Line7\\.e[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.sexualContact",
    pdfField: "form1[0].#subform[6].P9_Line7\\.e[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.religion",
    pdfField: "form1[0].#subform[6].P9_Line7\\.f[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.religion",
    pdfField: "form1[0].#subform[6].P9_Line7\\.f[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.harm",
    pdfField: "form1[0].#subform[6].P9_Line7\\.g[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.harm",
    pdfField: "form1[0].#subform[6].P9_Line7\\.g[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.injury",
    pdfField: "form1[0].#subform[6].P11_7d[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.injury",
    pdfField: "form1[0].#subform[6].P11_7d[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.alienNumber",
    pdfField: "form1[0].#subform[6].#area[7].Line1_AlienNumber[6]",
    type: "button",
  },
  {
    questionId: "part9.armedGroup",
    pdfField: "form1[0].#subform[6].P9_Line8a[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.armedGroup",
    pdfField: "form1[0].#subform[6].P9_Line8a[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.detained",
    pdfField: "form1[0].#subform[6].P9_Line9[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.detained",
    pdfField: "form1[0].#subform[6].P9_Line9[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.weaponUse",
    pdfField: "form1[0].#subform[6].P9_Line10b[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.weaponUse",
    pdfField: "form1[0].#subform[6].P9_Line10b[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.weaponThreat",
    pdfField: "form1[0].#subform[6].P9_Line10c[0]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.weaponThreat",
    pdfField: "form1[0].#subform[6].P9_Line10c[1]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.groupWeapon",
    pdfField: "form1[0].#subform[6].P9_Line10a[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.groupWeapon",
    pdfField: "form1[0].#subform[6].P9_Line10a[1]",
    type: "radio",
    value: "yes",
  },
  {
    questionId: "part9.armedGroupParticipation",
    pdfField: "form1[0].#subform[6].P9_Line8b[0]",
    type: "radio",
    value: "no",
  },
  {
    questionId: "part9.armedGroupParticipation",
    pdfField: "form1[0].#subform[6].P9_Line8b[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.weaponsTransport",
    pdfField: "form1[0].#subform[6].P9_Line11[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.weaponsTransport",
    pdfField: "form1[0].#subform[6].P9_Line11[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.weaponsTraining",
    pdfField: "form1[0].#subform[6].P9_Line12[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.weaponsTraining",
    pdfField: "form1[0].#subform[6].P9_Line12[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.recruitmentOfMinors",
    pdfField: "form1[0].#subform[6].P9_Line13[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.recruitmentOfMinors",
    pdfField: "form1[0].#subform[6].P9_Line13[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.useOfMinorsInHostilities",
    pdfField: "form1[0].#subform[6].P9_Line14[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.useOfMinorsInHostilities",
    pdfField: "form1[0].#subform[6].P9_Line14[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.alienNumber",
    pdfField: "form1[0].#subform[7].#area[8].Line1_AlienNumber[7]",
    type: "button",
  },
  {
    questionId: "part9.unarrestedCrimes",
    pdfField: "form1[0].#subform[7].P9_Line15a[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.unarrestedCrimes",
    pdfField: "form1[0].#subform[7].P9_Line15a[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.arrestHistory",
    pdfField: "form1[0].#subform[7].P9_Line15b[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.arrestHistory",
    pdfField: "form1[0].#subform[7].P9_Line15b[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.crimeOrOffense1",
    pdfField: "form1[0].#subform[7].P12_Line29_why1[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOrOffense2",
    pdfField: "form1[0].#subform[7].P12_Line29_why2[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOrOffense3",
    pdfField: "form1[0].#subform[7].P12_Line29_why3[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOrOffense4",
    pdfField: "form1[0].#subform[7].P12_Line29_why4[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOrOffense5",
    pdfField: "form1[0].#subform[7].P12_Line29_why5[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeDate1",
    pdfField: "form1[0].#subform[7].P12_Line29_Date1[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeDate2",
    pdfField: "form1[0].#subform[7].P12_Line29_Date2[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeDate3",
    pdfField: "form1[0].#subform[7].P12_Line29_Date3[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeDate4",
    pdfField: "form1[0].#subform[7].P12_Line29_Date4[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeDate5",
    pdfField: "form1[0].#subform[7].P12_Line29_Date5[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOutcome5",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome5[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOutcomeLine4",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome4[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOutcomeLine3",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome3[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOutcomeLine2",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome2[0]",
    type: "text",
  },
  {
    questionId: "part9.crimeOutcomeLine1",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome1[0]",
    type: "text",
  },
  {
    questionId: "part9.placeOfCrimeLine5",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome5[1]",
    type: "text",
  },
  {
    questionId: "part9.placeOfCrimeLine4",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome4[1]",
    type: "text",
  },
  {
    questionId: "part9.placeOfCrimeLine3",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome3[1]",
    type: "text",
  },
  {
    questionId: "part9.placeOfCrimeLine2",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome2[1]",
    type: "text",
  },
  {
    questionId: "part9.placeOfCrimeLine1",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome1[1]",
    type: "text",
  },
  {
    questionId: "part9.sentenceLine5",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome5[2]",
    type: "text",
  },
  {
    questionId: "part9.sentenceLine4",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome4[2]",
    type: "text",
  },
  {
    questionId: "part9.sentenceLine3",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome3[2]",
    type: "text",
  },
  {
    questionId: "part9.sentenceLine2",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome2[2]",
    type: "text",
  },
  {
    questionId: "part9.sentenceLine1",
    pdfField: "form1[0].#subform[7].P12_Line29_Outcome1[2]",
    type: "text",
  },
  {
    questionId: "part9.dateOfConvictionLine5",
    pdfField: "form1[0].#subform[7].P12_Line29_DateOfConv5[0]",
    type: "text",
  },
  {
    questionId: "part9.dateOfConvictionLine4",
    pdfField: "form1[0].#subform[7].P12_Line29_DateOfConv4[0]",
    type: "text",
  },
  {
    questionId: "part9.dateOfConvictionLine3",
    pdfField: "form1[0].#subform[7].P12_Line29_DateOfConv3[0]",
    type: "text",
  },
  {
    questionId: "part9.dateOfConvictionLine2",
    pdfField: "form1[0].#subform[7].P12_Line29_DateOfConv2[0]",
    type: "text",
  },
  {
    questionId: "part9.dateOfConvictionLine1",
    pdfField: "form1[0].#subform[7].P12_Line29_DateOfConv1[0]",
    type: "button",
  },
  {
    questionId: "part9.completedSentence",
    pdfField: "form1[0].#subform[7].P12_Line16[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.completedSentence",
    pdfField: "form1[0].#subform[7].P12_Line16[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part12.alienNumber",
    pdfField: "form1[0].#subform[8].#area[9].Line1_AlienNumber[8]",
    type: "button",
  },
  {
    questionId: "part9.engagedInProstitution",
    pdfField: "form1[0].#subform[8].P11_Line17A[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.engagedInProstitution",
    pdfField: "form1[0].#subform[8].P11_Line17A[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.drugTrafficking",
    pdfField: "form1[0].#subform[8].P11_Line17B[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.manufacturedControlledSubstances",
    pdfField: "form1[0].#subform[8].P11_Line17B[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.marriedMultiplePersons",
    pdfField: "form1[0].#subform[8].P11_Line17C[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.marriedMultiplePersons",
    pdfField: "form1[0].#subform[8].P11_Line17C[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.marriedForImmigrationBenefit",
    pdfField: "form1[0].#subform[8].P12_Line17d[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.marriedForImmigrationBenefit",
    pdfField: "form1[0].#subform[8].P12_Line17d[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.helpedIllegalEntry",
    pdfField: "form1[0].#subform[8].P12_Line17e[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.helpedIllegalEntry",
    pdfField: "form1[0].#subform[8].P12_Line17e[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.misrepresentationForBenefit",
    pdfField: "form1[0].#subform[8].P12_Line17h[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.misrepresentationForBenefit",
    pdfField: "form1[0].#subform[8].P12_Line17h[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.failedToSupportDependents",
    pdfField: "form1[0].#subform[8].P12_Line17g[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.failedToSupportDependents",
    pdfField: "form1[0].#subform[8].P12_Line17g[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.illegalGambling",
    pdfField: "form1[0].#subform[8].P12_Line17f[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.illegalGambling",
    pdfField: "form1[0].#subform[8].P12_Line17f[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.removedOrDeported",
    pdfField: "form1[0].#subform[8].P12_Line21[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.removedOrDeported",
    pdfField: "form1[0].#subform[8].P12_Line21[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.removalProceedings",
    pdfField: "form1[0].#subform[8].P12_Line20[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.removalProceedings",
    pdfField: "form1[0].#subform[8].P12_Line20[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.maleLivedInUS",
    pdfField: "form1[0].#subform[8].P9_Line22a[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.maleLivedInUS",
    pdfField: "form1[0].#subform[8].P9_Line22a[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.registrationDate",
    pdfField: "form1[0].#subform[8].P9_Line22c_Date[0]",
    type: "text",
  },
  {
    questionId: "part9.selectiveServiceNumber",
    pdfField: "form1[0].#subform[8].P9_Line22c_SSNumber[0]",
    type: "text",
  },
  {
    questionId: "part9.registeredForSelectiveService",
    pdfField: "form1[0].#subform[8].Pt9_Line22b[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.registeredForSelectiveService",
    pdfField: "form1[0].#subform[8].Pt9_Line22b[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.liedToUSOfficials",
    pdfField: "form1[0].#subform[8].P12_Line19[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.liedToUSOfficials",
    pdfField: "form1[0].#subform[8].P12_Line19[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.falseInformation",
    pdfField: "form1[0].#subform[8].P12_Line18[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.falseInformation",
    pdfField: "form1[0].#subform[8].P12_Line18[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.avoidDraft",
    pdfField: "form1[0].#subform[8].P12_Line23[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.avoidDraft",
    pdfField: "form1[0].#subform[8].P12_Line23[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.exemptionFromMilitary",
    pdfField: "form1[0].#subform[8].P12_Line24[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.exemptionFromMilitary",
    pdfField: "form1[0].#subform[8].P12_Line24[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.servedInMilitary",
    pdfField: "form1[0].#subform[8].P12_Line25[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.servedInMilitary",
    pdfField: "form1[0].#subform[8].P12_Line25[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.alienNumber",
    pdfField: "form1[0].#subform[9].#area[10].Line1_AlienNumber[9]",
    type: "button",
  },
  {
    questionId: "part9.currentMilitaryMember",
    pdfField: "form1[0].#subform[9].P12_Line26a[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.currentMilitaryMember",
    pdfField: "form1[0].#subform[9].P12_Line26a[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.scheduledToDeploy",
    pdfField: "form1[0].#subform[9].P12_Line26b[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.scheduledToDeploy",
    pdfField: "form1[0].#subform[9].P12_Line26b[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.stationedOutsideUS",
    pdfField: "form1[0].#subform[9].P12_Line26c[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.stationedOutsideUS",
    pdfField: "form1[0].#subform[9].P12_Line26c[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part12.stationedOverseas",
    pdfField: "form1[0].#subform[9].P11_Line26d[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part12.stationedOverseas",
    pdfField: "form1[0].#subform[9].P11_Line26d[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.courtMartialed",
    pdfField: "form1[0].#subform[9].P12_Line27[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.courtMartialed",
    pdfField: "form1[0].#subform[9].P12_Line27[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.dischargedAsAlien",
    pdfField: "form1[0].#subform[9].P12_Line28[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.dischargedAsAlien",
    pdfField: "form1[0].#subform[9].P12_Line28[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.desertedMilitary",
    pdfField: "form1[0].#subform[9].P9_Line29[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.desertedMilitary",
    pdfField: "form1[0].#subform[9].P9_Line29[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.hereditaryTitle",
    pdfField: "form1[0].#subform[9].P12_Line30a[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.hereditaryTitle",
    pdfField: "form1[0].#subform[9].P12_Line30a[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.willingToGiveUpTitles",
    pdfField: "form1[0].#subform[9].P12_Line30b[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.willingToGiveUpTitles",
    pdfField: "form1[0].#subform[9].P12_Line30b[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.supportConstitution",
    pdfField: "form1[0].#subform[9].P12_Line31[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.understandOath",
    pdfField: "form1[0].#subform[9].P12_Line32[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.understandOath",
    pdfField: "form1[0].#subform[9].P12_Line32[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.supportConstitution",
    pdfField: "form1[0].#subform[9].P12_Line31[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.willingToBearArms",
    pdfField: "form1[0].#subform[9].P12_Line35[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.willingToPerformNoncombatant",
    pdfField: "form1[0].#subform[9].P12_Line36[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.willingToPerformNoncombatant",
    pdfField: "form1[0].#subform[9].P12_Line36[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.willingToBearArms",
    pdfField: "form1[0].#subform[9].P12_Line35[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.willingToTakeOath",
    pdfField: "form1[0].#subform[9].P12_Line34[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.willingToTakeOath",
    pdfField: "form1[0].#subform[9].P12_Line34[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.willingToPerformWork",
    pdfField: "form1[0].#subform[9].P12_Line37[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.willingToPerformWork",
    pdfField: "form1[0].#subform[9].P12_Line37[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.unableToTakeOath",
    pdfField: "form1[0].#subform[9].P12_Line33[0]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part9.unableToTakeOath",
    pdfField: "form1[0].#subform[9].P12_Line33[1]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part10.daytimeTelephone",
    pdfField: "form1[0].#subform[9].P9_NobilityTitles[0]",
    type: "text",
  },
  {
    questionId: "part14.alienNumber",
    pdfField: "form1[0].#subform[10].#area[11].Line1_AlienNumber[10]",
    type: "text",
  },
  {
    questionId: "part10.signature",
    pdfField: "form1[0].#subform[10].P12_SignatureApplicant[0]",
    type: "text",
  },
  {
    questionId: "part10.dateOfSignature",
    pdfField: "form1[0].#subform[10].P13_DateofSignature[0]",
    type: "text",
  },
  {
    questionId: "part10.email",
    pdfField: "form1[0].#subform[10].P12_Line5_Email[0]",
    type: "text",
  },
  {
    questionId: "part10.daytimeTelephone",
    pdfField: "form1[0].#subform[10].P12_Line3_Telephone[0]",
    type: "text",
  },
  {
    questionId: "part10.mobileTelephone",
    pdfField: "form1[0].#subform[10].P12_Line3_Mobile[0]",
    type: "text",
  },
  {
    questionId: "part8.totalChildren",
    pdfField: "form1[0].#subform[10].P10_Line3_HouseHoldSize[0]",
    type: "text",
  },
  {
    questionId: "part8.totalChildren",
    pdfField: "form1[0].#subform[10].P11_Line1_TotalChildren[1]",
    type: "text",
  },
  {
    questionId: "part8.totalNumberOfChildren",
    pdfField: "form1[0].#subform[10].P10_Line5b_NameOfHousehold[0]",
    type: "button",
  },
  {
    questionId: "part7.currentSpouseAddressSame",
    pdfField: "form1[0].#subform[10].P10_Line1_Citizen[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part7.currentSpouseAddressSame",
    pdfField: "form1[0].#subform[10].P10_Line1_Citizen[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "part8.totalNumberOfChildren",
    pdfField: "form1[0].#subform[10].P10_Line2_TotalHouseholdIn[0]",
    type: "button",
  },
  {
    questionId: "part9.supportConstitution",
    pdfField: "form1[0].#subform[10].P10_Line5a[0]",
    type: "radio",
    value: "N",
  },
  {
    questionId: "part9.supportConstitution",
    pdfField: "form1[0].#subform[10].P10_Line5a[1]",
    type: "radio",
    value: "Y",
  },
  {
    questionId: "page15.alienRegistrationNumber",
    pdfField: "form1[0].#subform[11].#area[12].Line1_AlienNumber[11]",
    type: "text",
  },
  {
    questionId: "part11.interpreterBusinessName",
    pdfField: "form1[0].#subform[11].P14_Line2_NameofBusinessorOrgName[0]",
    type: "text",
  },
  {
    questionId: "part11.interpreterGivenName",
    pdfField: "form1[0].#subform[11].P14_Line1_nterpreterGivenName[0]",
    type: "text",
  },
  {
    questionId: "part11.interpreterFamilyName",
    pdfField: "form1[0].#subform[11].P14_Line1_nterpreterFamilyName[0]",
    type: "text",
  },
  {
    questionId: "part11.interpreterEmailAddress",
    pdfField: "form1[0].#subform[11].P14_Line5_EmailAddress[0]",
    type: "text",
  },
  {
    questionId: "part11.interpreterDaytimeTelephone",
    pdfField: "form1[0].#subform[11].P14_Line4_Telephone[0]",
    type: "text",
  },
  {
    questionId: "part11.interpreterMobileTelephone",
    pdfField: "form1[0].#subform[11].P14_Line5_Mobile[0]",
    type: "text",
  },
  {
    questionId: "part14.languageFluent",
    pdfField: "form1[0].#subform[11].P14_NameOfLanguage[0]",
    type: "text",
  },
  {
    questionId: "part14.dateOfSignature",
    pdfField: "form1[0].#subform[11].P14_DateofSignature[0]",
    type: "text",
  },
  {
    questionId: "part14.interpreterSignature",
    pdfField: "form1[0].#subform[11].P12_SignatureApplicant[1]",
    type: "text",
  },
  {
    questionId: "part12.preparerGivenName",
    pdfField: "form1[0].#subform[11].P15_Line1_PreparerGivenName[0]",
    type: "text",
  },
  {
    questionId: "part12.preparerFamilyName",
    pdfField: "form1[0].#subform[11].P15_Line1_PreparerFamilyName[0]",
    type: "text",
  },
  {
    questionId: "part12.preparerBusinessName",
    pdfField: "form1[0].#subform[11].P15_Line2_NameofBusinessorOrgName[0]",
    type: "text",
  },
  {
    questionId: "part12.preparerEmailAddress",
    pdfField: "form1[0].#subform[11].P15_Line6_Email[0]",
    type: "text",
  },
  {
    questionId: "part12.preparerDaytimeTelephone",
    pdfField: "form1[0].#subform[11].P15_Line4_Telephone[0]",
    type: "text",
  },
  {
    questionId: "part12.preparerMobileTelephone",
    pdfField: "form1[0].#subform[11].P15_Line5_Mobile[0]",
    type: "text",
  },
  {
    questionId: "part12.dateOfSignature",
    pdfField: "form1[0].#subform[11].P15_DateofSignature[0]",
    type: "text",
  },
  {
    questionId: "part12.applicantSignature",
    pdfField: "form1[0].#subform[11].P12_SignatureApplicant[2]",
    type: "text",
  },
  {
    questionId: "alienRegistrationNumber",
    pdfField: "form1[0].#subform[12].#area[13].Line1_AlienNumber[12]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation5AdditionalInfo",
    pdfField: "form1[0].#subform[12].P11_Line5D[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation6PageNumber",
    pdfField: "form1[0].#subform[12].P11_Line6A[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation6PartNumber",
    pdfField: "form1[0].#subform[12].P11_Line6B[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation6ItemNumber",
    pdfField: "form1[0].#subform[12].P11_Line6C[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation6AdditionalInfo",
    pdfField: "form1[0].#subform[12].P11_Line6D[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation5ItemNumber",
    pdfField: "form1[0].#subform[12].P11_Line5C[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation5PartNumber",
    pdfField: "form1[0].#subform[12].P11_Line5B[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation5PageNumber",
    pdfField: "form1[0].#subform[12].P11_Line5A[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation3PageNumber",
    pdfField: "form1[0].#subform[12].P11_Line3A[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation3PartNumber",
    pdfField: "form1[0].#subform[12].P11_Line3B[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation3ItemNumber",
    pdfField: "form1[0].#subform[12].P11_Line3C[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation3AdditionalInfo",
    pdfField: "form1[0].#subform[12].P11_Line3D[0]",
    type: "text",
  },
  {
    questionId: "part14.noEntryFamilyName",
    pdfField: "form1[0].#subform[12].P2_Line1_FamilyName[1]",
    type: "text",
  },
  {
    questionId: "part14.noEntryGivenName",
    pdfField: "form1[0].#subform[12].P2_Line1_GivenName[1]",
    type: "text",
  },
  {
    questionId: "part14.noEntryMiddleName",
    pdfField: "form1[0].#subform[12].P2_Line1_MiddleName[1]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation4PageNumber",
    pdfField: "form1[0].#subform[12].P11_Line4A[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation4PartNumber",
    pdfField: "form1[0].#subform[12].P11_Line4B[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation4ItemNumber",
    pdfField: "form1[0].#subform[12].P11_Line4C[0]",
    type: "text",
  },
  {
    questionId: "part14.additionalInformation4AdditionalInfo",
    pdfField: "form1[0].#subform[12].P11_Line4D[0]",
    type: "text",
  },
  {
    questionId: "page20.alienRegistrationNumber",
    pdfField: "form1[0].#subform[13].#area[14].Line1_AlienNumber[13]",
    type: "text",
  },
  {
    questionId: "part15.applicantsSignature",
    pdfField: "form1[0].#subform[13].Part15ApplicantsSignature[0]",
    type: "text",
  },
  {
    questionId: "part15.uscisOfficersSignature",
    pdfField: "form1[0].#subform[13].Part15USCISSignature[0]",
    type: "text",
  },
  {
    questionId: "part15.dateOfSignature",
    pdfField: "form1[0].#subform[13].Part15DateofSignature[0]",
    type: "text",
  },
  {
    questionId: "part15.uscisOfficersName",
    pdfField: "form1[0].#subform[13].Part15USCISName[0]",
    type: "text",
  },
  {
    questionId: "part16.oathOfAllegianceApplicantsSignature",
    pdfField: "form1[0].#subform[13].ApplicantsSignature[0]",
    type: "text",
  },
  {
    questionId: "part16.dateOfSignature",
    pdfField: "form1[0].#subform[13].Part15DateofSignature[1]",
  },
];
