/**
 * Auto-generated field mappings for I129UNLOCKED
 *
 * Generated on: 2025-12-16T20:55:49.589Z
 * Total fields: 932
 */

export interface FieldMapping {
  questionId: string;
  pdfField: string;
  type?: string;
  value?: string;
}

export const I129UNLOCKED_AUTO_MAPPINGS: FieldMapping[] = [
  { questionId: "line1.middlename", pdfField: "form1[0].#subform[0].Line1_MiddleName[0]" },
  { questionId: "line1.givenname", pdfField: "form1[0].#subform[0].Line1_GivenName[0]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[0].Line1_FamilyName[0]" },
  { questionId: "line3.companyororgname", pdfField: "form1[0].#subform[0].Line3_CompanyorOrgName[0]" },
  { questionId: "line.citytown", pdfField: "form1[0].#subform[0].Line_CityTown[0]" },
  { questionId: "part1.3.zipCode", pdfField: "form1[0].#subform[0].P1_Line3_ZipCode[0]" },
  { questionId: "part1.3.state", pdfField: "form1[0].#subform[0].P1_Line3_State[0]" },
  { questionId: "line7a.incareofname", pdfField: "form1[0].#subform[0].Line7a_InCareofName[0]" },
  { questionId: "line7b.streetnumbername", pdfField: "form1[0].#subform[0].Line7b_StreetNumberName[0]", type: "checkbox" },
  { questionId: "line3.unit", pdfField: "form1[0].#subform[0].Line3_Unit[0]", type: "checkbox" },
  { questionId: "line3.unit", pdfField: "form1[0].#subform[0].Line3_Unit[1]", type: "checkbox" },
  { questionId: "line3.unit", pdfField: "form1[0].#subform[0].Line3_Unit[2]" },
  { questionId: "line3.aptsteflrnumber", pdfField: "form1[0].#subform[0].Line3_AptSteFlrNumber[0]" },
  { questionId: "line9.emailaddress", pdfField: "form1[0].#subform[0].Line9_EmailAddress[0]" },
  { questionId: "textfield1", pdfField: "form1[0].#subform[0].TextField1[0]" },
  { questionId: "part1.3.postalCode", pdfField: "form1[0].#subform[0].P1_Line3_PostalCode[0]" },
  { questionId: "part1.3.province", pdfField: "form1[0].#subform[0].P1_Line3_Province[0]" },
  { questionId: "part1.3.country", pdfField: "form1[0].#subform[0].P1_Line3_Country[0]" },
  { questionId: "line2.daytimephonenumber1.part8", pdfField: "form1[0].#subform[0].Line2_DaytimePhoneNumber1_Part8[0]" },
  { questionId: "line3.mobilephonenumber1.part8", pdfField: "form1[0].#subform[0].Line3_MobilePhoneNumber1_Part8[0]", type: "checkbox" },
  { questionId: "p1line6.no", pdfField: "form1[0].#subform[0].P1Line6_No[0]", type: "checkbox" },
  { questionId: "p1line6.yes", pdfField: "form1[0].#subform[0].P1Line6_Yes[0]" },
  { questionId: "part2.classificationsymbol", pdfField: "form1[0].#subform[1].Part2_ClassificationSymbol[0]", type: "checkbox" },
  { questionId: "continuation", pdfField: "form1[0].#subform[1].continuation[0]", type: "checkbox" },
  { questionId: "new", pdfField: "form1[0].#subform[1].new[0]", type: "checkbox" },
  { questionId: "previouschange", pdfField: "form1[0].#subform[1].previouschange[0]", type: "checkbox" },
  { questionId: "concurrent", pdfField: "form1[0].#subform[1].concurrent[0]", type: "checkbox" },
  { questionId: "change", pdfField: "form1[0].#subform[1].change[0]", type: "checkbox" },
  { questionId: "amended", pdfField: "form1[0].#subform[1].amended[0]", type: "checkbox" },
  { questionId: "p2checkbox4", pdfField: "form1[0].#subform[1].P2Checkbox4[0]", type: "checkbox" },
  { questionId: "p2checkbox4", pdfField: "form1[0].#subform[1].P2Checkbox4[1]", type: "checkbox" },
  { questionId: "p2checkbox4", pdfField: "form1[0].#subform[1].P2Checkbox4[2]", type: "checkbox" },
  { questionId: "p2checkbox4", pdfField: "form1[0].#subform[1].P2Checkbox4[3]", type: "checkbox" },
  { questionId: "p2checkbox4", pdfField: "form1[0].#subform[1].P2Checkbox4[4]", type: "checkbox" },
  { questionId: "p2checkbox4", pdfField: "form1[0].#subform[1].P2Checkbox4[5]" },
  { questionId: "ttlnumbersofworker", pdfField: "form1[0].#subform[1].TtlNumbersofWorker[0]" },
  { questionId: "part7lined.emp1name", pdfField: "form1[0].#subform[1].Part7LineD_Emp1Name[0]" },
  { questionId: "part3.line2.middlename", pdfField: "form1[0].#subform[1].Part3_Line2_MiddleName[0]" },
  { questionId: "part3.line2.givenname", pdfField: "form1[0].#subform[1].Part3_Line2_GivenName[0]" },
  { questionId: "part3.line2.familyname", pdfField: "form1[0].#subform[1].Part3_Line2_FamilyName[0]" },
  { questionId: "line1.receiptnumber", pdfField: "form1[0].#subform[1].Line1_ReceiptNumber[0]", type: "checkbox" },
  { questionId: "p3line1.checkbox", pdfField: "form1[0].#subform[1].P3Line1_Checkbox[0]", type: "checkbox" },
  { questionId: "p3line1.checkbox", pdfField: "form1[0].#subform[1].P3Line1_Checkbox[1]" },
  { questionId: "line4.ssn", pdfField: "form1[0].#subform[1].Line4_SSN[0]" },
  { questionId: "line3.taxnumber", pdfField: "form1[0].#subform[1].Line3_TaxNumber[0]" },
  { questionId: "line11e.expdate", pdfField: "form1[0].#subform[2].Line11e_ExpDate[0]" },
  { questionId: "line5.sevis", pdfField: "form1[0].#subform[2].Line5_SEVIS[0]" },
  { questionId: "line5.ead", pdfField: "form1[0].#subform[2].Line5_EAD[0]" },
  { questionId: "line8e.state", pdfField: "form1[0].#subform[2].Line8e_State[0]" },
  { questionId: "line8f.zipcode", pdfField: "form1[0].#subform[2].Line8f_ZipCode[0]" },
  { questionId: "line8d.citytown", pdfField: "form1[0].#subform[2].Line8d_CityTown[0]", type: "checkbox" },
  { questionId: "line6.unit", pdfField: "form1[0].#subform[2].Line6_Unit[0]" },
  { questionId: "line6.aptsteflrnumber", pdfField: "form1[0].#subform[2].Line6_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "line6.unit", pdfField: "form1[0].#subform[2].Line6_Unit[1]", type: "checkbox" },
  { questionId: "line6.unit", pdfField: "form1[0].#subform[2].Line6_Unit[2]" },
  { questionId: "line8a.streetnumbername", pdfField: "form1[0].#subform[2].Line8a_StreetNumberName[0]" },
  { questionId: "line11g.currentnon", pdfField: "form1[0].#subform[2].Line11g_CurrentNon[0]" },
  { questionId: "line11h.datestatusexpires", pdfField: "form1[0].#subform[2].Line11h_DateStatusExpires[0]" },
  { questionId: "line11e.expdate", pdfField: "form1[0].#subform[2].Line11e_ExpDate[1]" },
  { questionId: "line.countryofissuance", pdfField: "form1[0].#subform[2].Line_CountryOfIssuance[0]" },
  { questionId: "part4line3.dprovince", pdfField: "form1[0].#subform[2].Part4Line3_DProvince[0]" },
  { questionId: "part3line5.dateofarrival", pdfField: "form1[0].#subform[2].Part3Line5_DateofArrival[0]" },
  { questionId: "part3line5.passportortravdoc", pdfField: "form1[0].#subform[2].Part3Line5_PassportorTravDoc[0]" },
  { questionId: "officeaddresscity", pdfField: "form1[0].#subform[2].OfficeAddressCity[0]" },
  { questionId: "part4.1c.state.or.country", pdfField: "form1[0].#subform[2].Part4_1c_State_or_Country[0]", type: "checkbox" },
  { questionId: "typeofoffice", pdfField: "form1[0].#subform[2].TypeofOffice[0]", type: "checkbox" },
  { questionId: "typeofoffice", pdfField: "form1[0].#subform[2].TypeofOffice[1]", type: "checkbox" },
  { questionId: "typeofoffice", pdfField: "form1[0].#subform[2].TypeofOffice[2]" },
  { questionId: "part3line4.countryofbirth", pdfField: "form1[0].#subform[2].Part3Line4_CountryOfBirth[0]" },
  { questionId: "part3line4.countryofcitizenship", pdfField: "form1[0].#subform[2].Part3Line4_CountryOfCitizenship[0]" },
  { questionId: "line1.aliennumber", pdfField: "form1[0].#subform[2].Line1_AlienNumber[0]" },
  { questionId: "part3line5.arrivaldeparture", pdfField: "form1[0].#subform[2].Part3Line5_ArrivalDeparture[0]" },
  { questionId: "line6.dateofbirth", pdfField: "form1[0].#subform[2].Line6_DateOfBirth[0]", type: "checkbox" },
  { questionId: "line1.gender.p3", pdfField: "form1[0].#subform[2].Line1_Gender_P3[0]", type: "checkbox" },
  { questionId: "line1.gender.p3", pdfField: "form1[0].#subform[2].Line1_Gender_P3[1]" },
  { questionId: "line5.ssn", pdfField: "form1[0].#subform[2].Line5_SSN[0]" },
  { questionId: "line3.givenname2", pdfField: "form1[0].#subform[2].Line3_GivenName2[0]" },
  { questionId: "line3.middlename2", pdfField: "form1[0].#subform[2].Line3_MiddleName2[0]" },
  { questionId: "line3.familyname3", pdfField: "form1[0].#subform[2].Line3_FamilyName3[0]" },
  { questionId: "line3.givenname3", pdfField: "form1[0].#subform[2].Line3_GivenName3[0]" },
  { questionId: "line3.middlename3", pdfField: "form1[0].#subform[2].Line3_MiddleName3[0]" },
  { questionId: "line3.familyname2", pdfField: "form1[0].#subform[2].Line3_FamilyName2[0]" },
  { questionId: "line3.middlename1", pdfField: "form1[0].#subform[2].Line3_MiddleName1[0]" },
  { questionId: "line3.givenname1", pdfField: "form1[0].#subform[2].Line3_GivenName1[0]" },
  { questionId: "line3.familyname1", pdfField: "form1[0].#subform[2].Line3_FamilyName1[0]" },
  { questionId: "p4line4.howmany", pdfField: "form1[0].#subform[3].P4Line4_HowMany[0]", type: "checkbox" },
  { questionId: "p4line5.no", pdfField: "form1[0].#subform[3].P4Line5_No[0]", type: "checkbox" },
  { questionId: "p4line11a.yes", pdfField: "form1[0].#subform[3].P4Line11a_Yes[0]", type: "checkbox" },
  { questionId: "p4line11a.no", pdfField: "form1[0].#subform[3].P4Line11a_No[0]", type: "checkbox" },
  { questionId: "p4line5.yes", pdfField: "form1[0].#subform[3].P4Line5_Yes[0]" },
  { questionId: "p4line5.howmany", pdfField: "form1[0].#subform[3].P4Line5_HowMany[0]" },
  { questionId: "p4line5.howmany", pdfField: "form1[0].#subform[3].P4Line5_HowMany[1]", type: "checkbox" },
  { questionId: "p4line8", pdfField: "form1[0].#subform[3].P4Line8[0]", type: "checkbox" },
  { questionId: "p4line8", pdfField: "form1[0].#subform[3].P4Line8[1]", type: "checkbox" },
  { questionId: "p4line4.yes", pdfField: "form1[0].#subform[3].P4Line4_Yes[0]", type: "checkbox" },
  { questionId: "p4line4.no", pdfField: "form1[0].#subform[3].P4Line4_No[0]", type: "checkbox" },
  { questionId: "p4line6.yes", pdfField: "form1[0].#subform[3].P4Line6_Yes[0]", type: "checkbox" },
  { questionId: "p4line7", pdfField: "form1[0].#subform[3].P4Line7[0]", type: "checkbox" },
  { questionId: "p4line9.yes", pdfField: "form1[0].#subform[3].P4Line9_Yes[0]", type: "checkbox" },
  { questionId: "p4line9.no", pdfField: "form1[0].#subform[3].P4Line9_No[0]", type: "checkbox" },
  { questionId: "p4line10.yes", pdfField: "form1[0].#subform[3].P4Line10_Yes[0]", type: "checkbox" },
  { questionId: "p4line10.no", pdfField: "form1[0].#subform[3].P4Line10_No[0]", type: "checkbox" },
  { questionId: "p4line8a.yes", pdfField: "form1[0].#subform[3].P4Line8a_Yes[0]", type: "checkbox" },
  { questionId: "p4line8a.no", pdfField: "form1[0].#subform[3].P4Line8a_No[0]", type: "checkbox" },
  { questionId: "p4line8b.yes", pdfField: "form1[0].#subform[3].P4Line8b_Yes[0]", type: "checkbox" },
  { questionId: "p4line8b.no", pdfField: "form1[0].#subform[3].P4Line8b_No[0]", type: "checkbox" },
  { questionId: "p4line7", pdfField: "form1[0].#subform[3].P4Line7[1]", type: "checkbox" },
  { questionId: "p4line6.no", pdfField: "form1[0].#subform[3].P4Line6_No[0]" },
  { questionId: "p4.line11b", pdfField: "form1[0].#subform[3].P4_Line11b[0]", type: "checkbox" },
  { questionId: "p4line3.no", pdfField: "form1[0].#subform[3].P4Line3_No[0]", type: "checkbox" },
  { questionId: "p4line3.yes", pdfField: "form1[0].#subform[3].P4Line3_Yes[0]" },
  { questionId: "p4line3.howmany", pdfField: "form1[0].#subform[3].P4Line3_HowMany[0]", type: "checkbox" },
  { questionId: "p4line2.checkbox", pdfField: "form1[0].#subform[3].P4Line2_Checkbox[0]", type: "checkbox" },
  { questionId: "p4line2.checkbox", pdfField: "form1[0].#subform[3].P4Line2_Checkbox[1]" },
  { questionId: "line2c.citytown", pdfField: "form1[0].#subform[3].Line2c_CityTown[0]" },
  { questionId: "line2b.streetnumbername", pdfField: "form1[0].#subform[3].Line2b_StreetNumberName[0]", type: "checkbox" },
  { questionId: "line2b2.unit", pdfField: "form1[0].#subform[3].Line2b2_Unit[0]", type: "checkbox" },
  { questionId: "line2b2.unit", pdfField: "form1[0].#subform[3].Line2b2_Unit[1]" },
  { questionId: "line2b2.aptsteflrnumber", pdfField: "form1[0].#subform[3].Line2b2_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "line2b2.unit", pdfField: "form1[0].#subform[3].Line2b2_Unit[2]" },
  { questionId: "line2g2.province", pdfField: "form1[0].#subform[3].Line2g2_Province[0]" },
  { questionId: "line3f.postalcode", pdfField: "form1[0].#subform[3].Line3f_PostalCode[0]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[3].Line_Country[0]" },
  { questionId: "line2g2.province", pdfField: "form1[0].#subform[3].Line2g2_Province[1]", type: "checkbox" },
  { questionId: "p5line5.yes", pdfField: "form1[0].#subform[4].P5Line5_Yes[0]", type: "checkbox" },
  { questionId: "p5line5.no", pdfField: "form1[0].#subform[4].P5Line5_No[0]", type: "checkbox" },
  { questionId: "p5line4.no", pdfField: "form1[0].#subform[4].P5Line4_No[0]", type: "checkbox" },
  { questionId: "p5line6.yes", pdfField: "form1[0].#subform[4].P5Line6_Yes[0]", type: "checkbox" },
  { questionId: "p5line6.no", pdfField: "form1[0].#subform[4].P5Line6_No[0]", type: "checkbox" },
  { questionId: "p5line4.yes", pdfField: "form1[0].#subform[4].P5Line4_Yes[0]" },
  { questionId: "part5.q10.datefrom", pdfField: "form1[0].#subform[4].Part5_Q10_DateFrom[0]" },
  { questionId: "part5.q10.dateto", pdfField: "form1[0].#subform[4].Part5_Q10_DateTo[0]" },
  { questionId: "p5line9.hours", pdfField: "form1[0].#subform[4].P5Line9_Hours[0]", type: "checkbox" },
  { questionId: "p5line7.no", pdfField: "form1[0].#subform[4].P5Line7_No[0]", type: "checkbox" },
  { questionId: "p5line7.yes", pdfField: "form1[0].#subform[4].P5Line7_Yes[0]" },
  { questionId: "line10.explanation", pdfField: "form1[0].#subform[4].Line10_Explanation[0]" },
  { questionId: "line8.wages", pdfField: "form1[0].#subform[4].Line8_Wages[0]" },
  { questionId: "line8.per", pdfField: "form1[0].#subform[4].Line8_Per[0]" },
  { questionId: "p5line3a.state", pdfField: "form1[0].#subform[4].P5Line3a_State[0]" },
  { questionId: "p5line3a.zipcode", pdfField: "form1[0].#subform[4].P5Line3a_ZipCode[0]", type: "checkbox" },
  { questionId: "p5line3a.unit", pdfField: "form1[0].#subform[4].P5Line3a_Unit[0]" },
  { questionId: "p5line3a.aptsteflrnumber", pdfField: "form1[0].#subform[4].P5Line3a_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "p5line3a.unit", pdfField: "form1[0].#subform[4].P5Line3a_Unit[1]", type: "checkbox" },
  { questionId: "p5line3a.unit", pdfField: "form1[0].#subform[4].P5Line3a_Unit[2]" },
  { questionId: "p5line3a.streetnumbername", pdfField: "form1[0].#subform[4].P5Line3a_StreetNumberName[0]" },
  { questionId: "p5line3a.citytown", pdfField: "form1[0].#subform[4].P5Line3a_CityTown[0]" },
  { questionId: "part5.q2.lcaoreta", pdfField: "form1[0].#subform[4].Part5_Q2_LCAorETA[0]" },
  { questionId: "part5.q1.jobtitle", pdfField: "form1[0].#subform[4].Part5_Q1_JobTitle[0]", type: "checkbox" },
  { questionId: "p5line3", pdfField: "form1[0].#subform[4].P5Line3[0]", type: "checkbox" },
  { questionId: "p5line3", pdfField: "form1[0].#subform[4].P5Line3[1]" },
  { questionId: "p5line3a.thirdpartyorganization", pdfField: "form1[0].#subform[4].P5Line3a_ThirdpartyOrganization[0]" },
  { questionId: "p5line3b.state2", pdfField: "form1[0].#subform[4].P5Line3b_State2[0]" },
  { questionId: "p5line3b.zipcode2", pdfField: "form1[0].#subform[4].P5Line3b_ZipCode2[0]", type: "checkbox" },
  { questionId: "p5line3b.unit2", pdfField: "form1[0].#subform[4].P5Line3b_Unit2[0]" },
  { questionId: "p5line3b.aptsteflrnumber2", pdfField: "form1[0].#subform[4].P5Line3b_AptSteFlrNumber2[0]", type: "checkbox" },
  { questionId: "p5line3b.unit2", pdfField: "form1[0].#subform[4].P5Line3b_Unit2[1]", type: "checkbox" },
  { questionId: "p5line3b.unit2", pdfField: "form1[0].#subform[4].P5Line3b_Unit2[2]" },
  { questionId: "p5line3b.streetnumbername2", pdfField: "form1[0].#subform[4].P5Line3b_StreetNumberName2[0]" },
  { questionId: "p5line3b.citytown", pdfField: "form1[0].#subform[4].P5Line3b_CityTown[0]", type: "checkbox" },
  { questionId: "p5line3add", pdfField: "form1[0].#subform[4].P5Line3Add[0]", type: "checkbox" },
  { questionId: "p5line3add", pdfField: "form1[0].#subform[4].P5Line3Add[1]" },
  { questionId: "p5line3b.thirdpartyorganization2", pdfField: "form1[0].#subform[4].P5Line3b_ThirdpartyOrganization2[0]" },
  { questionId: "part5line12.typeofbusiness", pdfField: "form1[0].#subform[5].Part5Line12_TypeofBusiness[0]" },
  { questionId: "p5line13.yearestablished", pdfField: "form1[0].#subform[5].P5Line13_YearEstablished[0]" },
  { questionId: "p5line14.numberofemployees", pdfField: "form1[0].#subform[5].P5Line14_NumberofEmployees[0]" },
  { questionId: "line15.grossannualincome", pdfField: "form1[0].#subform[5].Line15_GrossAnnualIncome[0]" },
  { questionId: "line16.netannualincome", pdfField: "form1[0].#subform[5].Line16_NetAnnualIncome[0]", type: "checkbox" },
  { questionId: "p5line15.cb", pdfField: "form1[0].#subform[5].P5Line15_CB[0]", type: "checkbox" },
  { questionId: "p5line15.cb", pdfField: "form1[0].#subform[5].P5Line15_CB[1]", type: "checkbox" },
  { questionId: "nodeemed", pdfField: "form1[0].#subform[5].NoDeemed[0]", type: "checkbox" },
  { questionId: "deemed", pdfField: "form1[0].#subform[5].Deemed[0]" },
  { questionId: "line1a.petitionerlastname", pdfField: "form1[0].#subform[5].Line1a_PetitionerLastName[0]" },
  { questionId: "line1a.petitionerlastname", pdfField: "form1[0].#subform[5].Line1a_PetitionerLastName[1]" },
  { questionId: "line1b.petitionerfirstname", pdfField: "form1[0].#subform[5].Line1b_PetitionerFirstName[0]" },
  { questionId: "line1b.dateofsignature", pdfField: "form1[0].#subform[6].Line1b_DateofSignature[0]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[6].P5_Line6a_SignatureofApplicant[0]" },
  { questionId: "pt7line3.emailaddress", pdfField: "form1[0].#subform[6].Pt7Line3_EmailAddress[0]" },
  { questionId: "pt7line3.daytimephonenumber1", pdfField: "form1[0].#subform[6].Pt7Line3_DaytimePhoneNumber1[0]" },
  { questionId: "line.signature", pdfField: "form1[0].#subform[6].Line_Signature[0]" },
  { questionId: "line.dateofsignature", pdfField: "form1[0].#subform[6].Line_DateofSignature[0]" },
  { questionId: "emailaddress", pdfField: "form1[0].#subform[6].EmailAddress[0]" },
  { questionId: "pt8line4.daytimephonenumber1", pdfField: "form1[0].#subform[6].Pt8Line4_DaytimePhoneNumber1[0]" },
  { questionId: "pt8line4.daytimephonenumber1", pdfField: "form1[0].#subform[6].Pt8Line4_DaytimePhoneNumber1[1]" },
  { questionId: "line.preparerfamilyname", pdfField: "form1[0].#subform[6].Line_PreparerFamilyName[0]" },
  { questionId: "line.preparergivenname", pdfField: "form1[0].#subform[6].Line_PreparerGivenName[0]" },
  { questionId: "line.businessname", pdfField: "form1[0].#subform[6].Line_BusinessName[0]" },
  { questionId: "line.citytown", pdfField: "form1[0].#subform[6].Line_CityTown[1]" },
  { questionId: "part8.3.zipCode", pdfField: "form1[0].#subform[6].P8_Line3_ZipCode[0]" },
  { questionId: "part8.3.state", pdfField: "form1[0].#subform[6].P8_Line3_State[0]" },
  { questionId: "line7b.streetnumbername", pdfField: "form1[0].#subform[6].Line7b_StreetNumberName[1]", type: "checkbox" },
  { questionId: "part8line3.unit", pdfField: "form1[0].#subform[6].Part8Line3_Unit[0]", type: "checkbox" },
  { questionId: "part8line3.unit", pdfField: "form1[0].#subform[6].Part8Line3_Unit[1]", type: "checkbox" },
  { questionId: "part8line3.unit", pdfField: "form1[0].#subform[6].Part8Line3_Unit[2]" },
  { questionId: "part8line3.aptsteflrnumber", pdfField: "form1[0].#subform[6].Part8Line3_AptSteFlrNumber[0]" },
  { questionId: "part8.3.province", pdfField: "form1[0].#subform[6].P8_Line3_Province[0]" },
  { questionId: "part8.3.postalCode", pdfField: "form1[0].#subform[6].P8_Line3_PostalCode[0]" },
  { questionId: "part8.3.country", pdfField: "form1[0].#subform[6].P8_Line3_Country[0]" },
  { questionId: "line4.additionalinfo", pdfField: "form1[0].#subform[7].Line4_AdditionalInfo[0]" },
  { questionId: "line3.additionalinfo", pdfField: "form1[0].#subform[7].Line3_AdditionalInfo[0]" },
  { questionId: "#area[0].line10.aliennumber", pdfField: "form1[0].#subform[7].#area[0].Line10_AlienNumber[0]" },
  { questionId: "line2a.pagenumber", pdfField: "form1[0].#subform[7].Line2a_PageNumber[0]" },
  { questionId: "line2b.partnumber", pdfField: "form1[0].#subform[7].Line2b_PartNumber[0]" },
  { questionId: "line2c.itemnumber", pdfField: "form1[0].#subform[7].Line2c_ItemNumber[0]" },
  { questionId: "line4c.itemnumber", pdfField: "form1[0].#subform[7].Line4c_ItemNumber[0]" },
  { questionId: "line4b.partnumber", pdfField: "form1[0].#subform[7].Line4b_PartNumber[0]" },
  { questionId: "line4a.pagenumber", pdfField: "form1[0].#subform[7].Line4a_PageNumber[0]" },
  { questionId: "line4a.pagenumber", pdfField: "form1[0].#subform[7].Line4a_PageNumber[1]" },
  { questionId: "line4b.partnumber", pdfField: "form1[0].#subform[7].Line4b_PartNumber[1]" },
  { questionId: "line4c.itemnumber", pdfField: "form1[0].#subform[7].Line4c_ItemNumber[1]" },
  { questionId: "line2.additionalinfo", pdfField: "form1[0].#subform[7].Line2_AdditionalInfo[0]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[8].Line1_FamilyName[1]" },
  { questionId: "line1.givenname", pdfField: "form1[0].#subform[8].Line1_GivenName[1]" },
  { questionId: "line1.middlename", pdfField: "form1[0].#subform[8].Line1_MiddleName[1]", type: "checkbox" },
  { questionId: "e1.treatytrader", pdfField: "form1[0].#subform[8].E1_TreatyTrader[0]", type: "checkbox" },
  { questionId: "e2.treatyinvestor", pdfField: "form1[0].#subform[8].E2_TreatyInvestor[0]", type: "checkbox" },
  { questionId: "e2.cnmi", pdfField: "form1[0].#subform[8].E2_CNMI[0]", type: "checkbox" },
  { questionId: "supeline5.yes", pdfField: "form1[0].#subform[8].SupELine5_Yes[0]", type: "checkbox" },
  { questionId: "supeline5.no", pdfField: "form1[0].#subform[8].SupELine5_No[0]" },
  { questionId: "line3.companyororgname", pdfField: "form1[0].#subform[8].Line3_CompanyorOrgName[1]" },
  { questionId: "line.citytown", pdfField: "form1[0].#subform[8].Line_CityTown[2]" },
  { questionId: "s1.line3.zipcode", pdfField: "form1[0].#subform[8].S1_Line3_ZipCode[0]" },
  { questionId: "s1.line3.state", pdfField: "form1[0].#subform[8].S1_Line3_State[0]" },
  { questionId: "line7b.streetnumbername", pdfField: "form1[0].#subform[8].Line7b_StreetNumberName[2]", type: "checkbox" },
  { questionId: "sec1line3.unit", pdfField: "form1[0].#subform[8].Sec1Line3_Unit[0]", type: "checkbox" },
  { questionId: "sec1line3.unit", pdfField: "form1[0].#subform[8].Sec1Line3_Unit[1]", type: "checkbox" },
  { questionId: "sec1line3.unit", pdfField: "form1[0].#subform[8].Sec1Line3_Unit[2]" },
  { questionId: "sec1line3.aptsteflrnumber", pdfField: "form1[0].#subform[8].Sec1Line3_AptSteFlrNumber[0]" },
  { questionId: "line2.ttlnumberofemployees", pdfField: "form1[0].#subform[8].Line2_TtlNumberofEmployees[0]" },
  { questionId: "line4.description", pdfField: "form1[0].#subform[8].Line4_Description[0]" },
  { questionId: "supeline1.nameofemployer", pdfField: "form1[0].#subform[8].SupELine1_NameofEmployer[0]" },
  { questionId: "s1.line3.province", pdfField: "form1[0].#subform[8].S1_Line3_Province[0]" },
  { questionId: "s1.line3.postalcode", pdfField: "form1[0].#subform[8].S1_Line3_PostalCode[0]" },
  { questionId: "s1.line3.country", pdfField: "form1[0].#subform[8].S1_Line3_Country[0]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[8].Line_Country[1]" },
  { questionId: "line5.employeepositiondescription", pdfField: "form1[0].#subform[8].Line5_EmployeePositionDescription[0]", type: "checkbox" },
  { questionId: "sect2.parent", pdfField: "form1[0].#subform[9].Sect2_Parent[0]", type: "checkbox" },
  { questionId: "sect2.branch", pdfField: "form1[0].#subform[9].Sect2_Branch[0]", type: "checkbox" },
  { questionId: "sect2.subsidiary", pdfField: "form1[0].#subform[9].Sect2_Subsidiary[0]", type: "checkbox" },
  { questionId: "sect2.affiliate", pdfField: "form1[0].#subform[9].Sect2_Affiliate[0]", type: "checkbox" },
  { questionId: "sect2.jointventure", pdfField: "form1[0].#subform[9].Sect2_JointVenture[0]" },
  { questionId: "line2a.typeofbusiness", pdfField: "form1[0].#subform[9].Line2a_TypeofBusiness[0]" },
  { questionId: "line2b.dateestablished", pdfField: "form1[0].#subform[9].Line2b_DateEstablished[0]" },
  { questionId: "table1[0].row1[0].name.line1", pdfField: "form1[0].#subform[9].Table1[0].Row1[0].NAME_Line1[0]" },
  { questionId: "table1[0].row1[0].nationality.line1", pdfField: "form1[0].#subform[9].Table1[0].Row1[0].Nationality_line1[0]" },
  { questionId: "table1[0].row1[0].immigrationstatus.line1", pdfField: "form1[0].#subform[9].Table1[0].Row1[0].ImmigrationStatus_Line1[0]" },
  { questionId: "table1[0].row1[0].percentownership.line1", pdfField: "form1[0].#subform[9].Table1[0].Row1[0].PercentOwnership_Line1[0]" },
  { questionId: "table1[0].row2[0].name.line2", pdfField: "form1[0].#subform[9].Table1[0].Row2[0].NAME_Line2[0]" },
  { questionId: "table1[0].row2[0].nationality.line2", pdfField: "form1[0].#subform[9].Table1[0].Row2[0].Nationality_line2[0]" },
  { questionId: "table1[0].row2[0].immigrationstatus.line2", pdfField: "form1[0].#subform[9].Table1[0].Row2[0].ImmigrationStatus_Line2[0]" },
  { questionId: "table1[0].row2[0].percentownership.line2", pdfField: "form1[0].#subform[9].Table1[0].Row2[0].PercentOwnership_Line2[0]" },
  { questionId: "table1[0].row3[0].name.line3", pdfField: "form1[0].#subform[9].Table1[0].Row3[0].NAME_Line3[0]" },
  { questionId: "table1[0].row3[0].nationality.line3", pdfField: "form1[0].#subform[9].Table1[0].Row3[0].Nationality_line3[0]" },
  { questionId: "table1[0].row3[0].immigrationstatus.line3", pdfField: "form1[0].#subform[9].Table1[0].Row3[0].ImmigrationStatus_Line3[0]" },
  { questionId: "table1[0].row3[0].percentownership.line3", pdfField: "form1[0].#subform[9].Table1[0].Row3[0].PercentOwnership_Line3[0]" },
  { questionId: "table1[0].row4[0].name.line4", pdfField: "form1[0].#subform[9].Table1[0].Row4[0].NAME_Line4[0]" },
  { questionId: "table1[0].row4[0].nationality.line4", pdfField: "form1[0].#subform[9].Table1[0].Row4[0].Nationality_line4[0]" },
  { questionId: "table1[0].row4[0].immigrationstatus.line4", pdfField: "form1[0].#subform[9].Table1[0].Row4[0].ImmigrationStatus_Line4[0]" },
  { questionId: "table1[0].row4[0].percentownership.line4", pdfField: "form1[0].#subform[9].Table1[0].Row4[0].PercentOwnership_Line4[0]" },
  { questionId: "table1[0].row5[0].name5", pdfField: "form1[0].#subform[9].Table1[0].Row5[0].NAME5[0]" },
  { questionId: "table1[0].row5[0].nationality.line5", pdfField: "form1[0].#subform[9].Table1[0].Row5[0].Nationality_line5[0]" },
  { questionId: "table1[0].row5[0].immigrationstatus.line5", pdfField: "form1[0].#subform[9].Table1[0].Row5[0].ImmigrationStatus_Line5[0]" },
  { questionId: "table1[0].row5[0].percentownership.line5", pdfField: "form1[0].#subform[9].Table1[0].Row5[0].PercentOwnership_Line5[0]" },
  { questionId: "table1[0].row5[1].name.line6", pdfField: "form1[0].#subform[9].Table1[0].Row5[1].NAME_Line6[0]" },
  { questionId: "table1[0].row5[1].nationality.line6", pdfField: "form1[0].#subform[9].Table1[0].Row5[1].Nationality_line6[0]" },
  { questionId: "table1[0].row5[1].immigrationstatus.line6", pdfField: "form1[0].#subform[9].Table1[0].Row5[1].ImmigrationStatus_Line6[0]" },
  { questionId: "table1[0].row5[1].percentownership.line6", pdfField: "form1[0].#subform[9].Table1[0].Row5[1].PercentOwnership_Line6[0]" },
  { questionId: "table1[0].row5[2].name.line7", pdfField: "form1[0].#subform[9].Table1[0].Row5[2].NAME_Line7[0]" },
  { questionId: "table1[0].row5[2].nationality.line7", pdfField: "form1[0].#subform[9].Table1[0].Row5[2].Nationality_line7[0]" },
  { questionId: "table1[0].row5[2].immigrationstatus.line7", pdfField: "form1[0].#subform[9].Table1[0].Row5[2].ImmigrationStatus_Line7[0]" },
  { questionId: "table1[0].row5[2].percentownership.line7", pdfField: "form1[0].#subform[9].Table1[0].Row5[2].PercentOwnership_Line7[0]" },
  { questionId: "p5line.yearestablished", pdfField: "form1[0].#subform[9].P5Line_YearEstablished[0]" },
  { questionId: "line2d.grossannualincome", pdfField: "form1[0].#subform[9].Line2d_GrossAnnualIncome[0]" },
  { questionId: "line2e.netannualincome", pdfField: "form1[0].#subform[9].Line2e_NetAnnualIncome[0]" },
  { questionId: "supeline7a.howmany", pdfField: "form1[0].#subform[9].SupELine7a_HowMany[0]" },
  { questionId: "supeline7b.howmany", pdfField: "form1[0].#subform[9].SupELine7b_HowMany[0]" },
  { questionId: "supeline7c.totalnumber", pdfField: "form1[0].#subform[9].SupELine7c_TotalNumber[0]" },
  { questionId: "supeline7d.totalnumber", pdfField: "form1[0].#subform[9].SupELine7d_TotalNumber[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[9].Line3_JobDescription[0]" },
  { questionId: "esec3line1.ttlannualgross", pdfField: "form1[0].#subform[9].ESec3Line1_TtlAnnualGross[0]" },
  { questionId: "esec4.cash", pdfField: "form1[0].#subform[9].ESec4_Cash[0]" },
  { questionId: "esec3line2.yearending", pdfField: "form1[0].#subform[9].ESec3Line2_YearEnding[0]" },
  { questionId: "esec3line3.percentofttlgross", pdfField: "form1[0].#subform[9].ESec3Line3_PercentOfTtlGross[0]" },
  { questionId: "esec4.equipment", pdfField: "form1[0].#subform[9].ESec4_Equipment[0]" },
  { questionId: "esec4.premises", pdfField: "form1[0].#subform[9].ESec4_Premises[0]" },
  { questionId: "esec4.inventory", pdfField: "form1[0].#subform[9].ESec4_Inventory[0]" },
  { questionId: "esec4.other", pdfField: "form1[0].#subform[9].ESec4_Other[0]" },
  { questionId: "esec4.totla", pdfField: "form1[0].#subform[9].ESec4_Totla[0]", type: "checkbox" },
  { questionId: "employer", pdfField: "form1[0].#subform[11].employer[0]", type: "checkbox" },
  { questionId: "employer", pdfField: "form1[0].#subform[11].employer[1]", type: "checkbox" },
  { questionId: "a.canada", pdfField: "form1[0].#subform[11].a_Canada[0]", type: "checkbox" },
  { questionId: "b.mexico", pdfField: "form1[0].#subform[11].b_Mexico[0]", type: "checkbox" },
  { questionId: "c.chile", pdfField: "form1[0].#subform[11].c_Chile[0]", type: "checkbox" },
  { questionId: "e.other", pdfField: "form1[0].#subform[11].e_Other[0]", type: "checkbox" },
  { questionId: "d.singapore", pdfField: "form1[0].#subform[11].d_Singapore[0]", type: "checkbox" },
  { questionId: "f.chileorsingapore", pdfField: "form1[0].#subform[11].f_ChileOrSingapore[0]" },
  { questionId: "tasupline1.nameofpetitioner", pdfField: "form1[0].#subform[11].TASupLine1_NameofPetitioner[0]" },
  { questionId: "tasupline2b.dateofsignature", pdfField: "form1[0].#subform[11].TASupLine2b_DateofSignature[0]" },
  { questionId: "tasupline5.email", pdfField: "form1[0].#subform[11].TASupLine5_Email[0]" },
  { questionId: "tasupline1a.petitionerlastname", pdfField: "form1[0].#subform[11].TASupLine1a_PetitionerLastName[0]" },
  { questionId: "tasupline1b.petitionerfirstname", pdfField: "form1[0].#subform[11].TASupLine1b_PetitionerFirstName[0]" },
  { questionId: "line4.country", pdfField: "form1[0].#subform[11].Line4_Country[0]" },
  { questionId: "tasupline1.nameofbeneficiary", pdfField: "form1[0].#subform[11].TASupLine1_NameofBeneficiary[0]" },
  { questionId: "tasupline2.daytimephonenumber1", pdfField: "form1[0].#subform[11].TASupLine2_DaytimePhoneNumber1[0]" },
  { questionId: "tasupline3.mobilephonenumber1", pdfField: "form1[0].#subform[11].TASupLine3_MobilePhoneNumber1[0]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[11].P5_Line6a_SignatureofApplicant[1]" },
  { questionId: "line.citytown", pdfField: "form1[0].#subform[12].Line_CityTown[3]" },
  { questionId: "s3.line3.zipcode", pdfField: "form1[0].#subform[12].S3_Line3_ZipCode[0]" },
  { questionId: "s3.line3.state", pdfField: "form1[0].#subform[12].S3_Line3_State[0]" },
  { questionId: "line7b.streetnumbername", pdfField: "form1[0].#subform[12].Line7b_StreetNumberName[3]", type: "checkbox" },
  { questionId: "sec3line3.unit", pdfField: "form1[0].#subform[12].Sec3Line3_Unit[0]", type: "checkbox" },
  { questionId: "sec3line3.unit", pdfField: "form1[0].#subform[12].Sec3Line3_Unit[1]", type: "checkbox" },
  { questionId: "sec3line3.unit", pdfField: "form1[0].#subform[12].Sec3Line3_Unit[2]" },
  { questionId: "sec3line3.aptsteflrnumber", pdfField: "form1[0].#subform[12].Sec3Line3_AptSteFlrNumber[0]" },
  { questionId: "line.signature", pdfField: "form1[0].#subform[12].Line_Signature[1]" },
  { questionId: "line.dateofsignature", pdfField: "form1[0].#subform[12].Line_DateofSignature[1]" },
  { questionId: "tasupline5.email", pdfField: "form1[0].#subform[12].TASupLine5_Email[1]" },
  { questionId: "s3.line3.province", pdfField: "form1[0].#subform[12].S3_Line3_Province[0]" },
  { questionId: "line.businessname", pdfField: "form1[0].#subform[12].Line_BusinessName[1]" },
  { questionId: "line.preparerfamilyname", pdfField: "form1[0].#subform[12].Line_PreparerFamilyName[1]" },
  { questionId: "line.preparergivenname", pdfField: "form1[0].#subform[12].Line_PreparerGivenName[1]" },
  { questionId: "s3.line3.postalcode", pdfField: "form1[0].#subform[12].S3_Line3_PostalCode[0]" },
  { questionId: "s3.line3.country", pdfField: "form1[0].#subform[12].S3_Line3_Country[0]" },
  { questionId: "tasupline2.daytimephonenumber1", pdfField: "form1[0].#subform[12].TASupLine2_DaytimePhoneNumber1[1]" },
  { questionId: "pt8line4.daytimephonenumber1", pdfField: "form1[0].#subform[12].Pt8Line4_DaytimePhoneNumber1[2]" },
  { questionId: "line1.petitionername", pdfField: "form1[0].#subform[13].Line1_PetitionerName[0]" },
  { questionId: "line2.beneficiaryname", pdfField: "form1[0].#subform[13].Line2_BeneficiaryName[0]" },
  { questionId: "line2.ttlnumberofbeneficiaries", pdfField: "form1[0].#subform[13].Line2_TtlNumberofBeneficiaries[0]" },
  { questionId: "table1[1].row2[0].name.line1", pdfField: "form1[0].#subform[13].Table1[1].Row2[0].Name_Line1[0]" },
  { questionId: "table1[1].row2[0].datefrom.line1", pdfField: "form1[0].#subform[13].Table1[1].Row2[0].DateFrom_Line1[0]" },
  { questionId: "table1[1].row2[0].dateto.line1", pdfField: "form1[0].#subform[13].Table1[1].Row2[0].DateTo_Line1[0]" },
  { questionId: "table1[1].row3[0].name.line2", pdfField: "form1[0].#subform[13].Table1[1].Row3[0].Name_Line2[0]" },
  { questionId: "table1[1].row3[0].datefrom.line2", pdfField: "form1[0].#subform[13].Table1[1].Row3[0].DateFrom_Line2[0]" },
  { questionId: "table1[1].row3[0].dateto.line2", pdfField: "form1[0].#subform[13].Table1[1].Row3[0].DateTo_Line2[0]" },
  { questionId: "table1[1].row4[0].name.line3", pdfField: "form1[0].#subform[13].Table1[1].Row4[0].Name_Line3[0]" },
  { questionId: "table1[1].row4[0].datefrom.line3", pdfField: "form1[0].#subform[13].Table1[1].Row4[0].DateFrom_Line3[0]" },
  { questionId: "table1[1].row4[0].dateto.line3", pdfField: "form1[0].#subform[13].Table1[1].Row4[0].DateTo_Line3[0]" },
  { questionId: "table1[1].row5[0].name.line4", pdfField: "form1[0].#subform[13].Table1[1].Row5[0].Name_Line4[0]" },
  { questionId: "table1[1].row5[0].datefrom.line4", pdfField: "form1[0].#subform[13].Table1[1].Row5[0].DateFrom_Line4[0]" },
  { questionId: "table1[1].row5[0].dateto.line4", pdfField: "form1[0].#subform[13].Table1[1].Row5[0].DateTo_Line4[0]" },
  { questionId: "table1[1].row6[0].name.line5", pdfField: "form1[0].#subform[13].Table1[1].Row6[0].Name_Line5[0]" },
  { questionId: "table1[1].row6[0].datefrom.line5", pdfField: "form1[0].#subform[13].Table1[1].Row6[0].DateFrom_Line5[0]" },
  { questionId: "table1[1].row6[0].dateto.line5", pdfField: "form1[0].#subform[13].Table1[1].Row6[0].DateTo_Line5[0]" },
  { questionId: "table1[1].row6[1].name.line6", pdfField: "form1[0].#subform[13].Table1[1].Row6[1].Name_Line6[0]" },
  { questionId: "table1[1].row6[1].datefrom.line6", pdfField: "form1[0].#subform[13].Table1[1].Row6[1].DateFrom_Line6[0]" },
  { questionId: "table1[1].row6[1].dateto.line6", pdfField: "form1[0].#subform[13].Table1[1].Row6[1].DateTo_Line6[0]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[0]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[1]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[2]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[3]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[4]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[5]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[6]", type: "checkbox" },
  { questionId: "subhline4.class", pdfField: "form1[0].#subform[13].SubHLine4_class[7]" },
  { questionId: "subhline5.confirmationnum", pdfField: "form1[0].#subform[13].SubHLine5_ConfirmationNum[0]" },
  { questionId: "classhline5b.expdate", pdfField: "form1[0].#subform[15].ClassHLine5b_ExpDate[0]" },
  { questionId: "classhline5b.countryofissuance", pdfField: "form1[0].#subform[15].ClassHLine5b_CountryOfIssuance[0]" },
  { questionId: "classhline5b.passportortravdoc", pdfField: "form1[0].#subform[15].ClassHLine5b_PassportorTravDoc[0]", type: "checkbox" },
  { questionId: "line8a.check", pdfField: "form1[0].#subform[15].Line8a_Check[0]", type: "checkbox" },
  { questionId: "line8a.check", pdfField: "form1[0].#subform[15].Line8a_Check[1]" },
  { questionId: "line2.summaryofworkexperience", pdfField: "form1[0].#subform[15].Line2_SummaryofWorkExperience[0]" },
  { questionId: "line1.duties", pdfField: "form1[0].#subform[15].Line1_Duties[0]" },
  { questionId: "line8b.explain", pdfField: "form1[0].#subform[15].Line8b_Explain[0]", type: "checkbox" },
  { questionId: "suphline5.no", pdfField: "form1[0].#subform[15].SupHLine5_No[0]", type: "checkbox" },
  { questionId: "suphline5.yes", pdfField: "form1[0].#subform[15].SupHLine5_Yes[0]", type: "checkbox" },
  { questionId: "suphline5.yes", pdfField: "form1[0].#subform[15].SupHLine5_Yes[1]", type: "checkbox" },
  { questionId: "suphline5.no", pdfField: "form1[0].#subform[15].SupHLine5_No[1]" },
  { questionId: "sect1.datesignedbypetitioner", pdfField: "form1[0].#subform[15].Sect1_DateSignedByPetitioner[0]" },
  { questionId: "sect1.petitionerprintedname", pdfField: "form1[0].#subform[15].Sect1_PetitionerPrintedName[0]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[15].P5_Line6a_SignatureofApplicant[2]" },
  { questionId: "sect1.datesignedbydodpm", pdfField: "form1[0].#subform[16].Sect1_DateSignedByDODPM[0]" },
  { questionId: "sect1.dodpmsignature", pdfField: "form1[0].#subform[16].Sect1_DODPMSignature[0]" },
  { questionId: "sect1.dodpmname", pdfField: "form1[0].#subform[16].Sect1_DODPMName[0]", type: "checkbox" },
  { questionId: "a.seasonal", pdfField: "form1[0].#subform[16].a_seasonal[0]", type: "checkbox" },
  { questionId: "b.peakload", pdfField: "form1[0].#subform[16].b_peakload[0]", type: "checkbox" },
  { questionId: "d.onetime", pdfField: "form1[0].#subform[16].d_onetime[0]", type: "checkbox" },
  { questionId: "c.recurrent", pdfField: "form1[0].#subform[16].c_recurrent[0]", type: "checkbox" },
  { questionId: "a.unpredictable", pdfField: "form1[0].#subform[16].a_unpredictable[0]", type: "checkbox" },
  { questionId: "b.periodic", pdfField: "form1[0].#subform[16].b_periodic[0]", type: "checkbox" },
  { questionId: "c.intermittent", pdfField: "form1[0].#subform[16].c_intermittent[0]" },
  { questionId: "line3.explanation", pdfField: "form1[0].#subform[16].Line3_Explanation[0]", type: "checkbox" },
  { questionId: "suphline5", pdfField: "form1[0].#subform[16].SupHLine5[0]", type: "checkbox" },
  { questionId: "suphline5", pdfField: "form1[0].#subform[16].SupHLine5[1]", type: "checkbox" },
  { questionId: "suphline6a", pdfField: "form1[0].#subform[16].SupHLine6a[0]", type: "checkbox" },
  { questionId: "suphline6a", pdfField: "form1[0].#subform[16].SupHLine6a[1]", type: "checkbox" },
  { questionId: "suphline6", pdfField: "form1[0].#subform[16].SupHLine6[0]", type: "checkbox" },
  { questionId: "suphline6", pdfField: "form1[0].#subform[16].SupHLine6[1]" },
  { questionId: "sect1.authorizedofficialsignature", pdfField: "form1[0].#subform[16].Sect1_AuthorizedOfficialSignature[0]" },
  { questionId: "sect1.datesignedbyauthorizedofficial", pdfField: "form1[0].#subform[16].Sect1_DateSignedByAuthorizedOfficial[0]" },
  { questionId: "sect1.authorizedofficialname", pdfField: "form1[0].#subform[16].Sect1_AuthorizedOfficialName[0]", type: "checkbox" },
  { questionId: "suphline11", pdfField: "form1[0].#subform[17].SupHLine11[0]", type: "checkbox" },
  { questionId: "suphline11", pdfField: "form1[0].#subform[17].SupHLine11[1]", type: "checkbox" },
  { questionId: "suphline8c", pdfField: "form1[0].#subform[17].SupHLine8c[0]", type: "checkbox" },
  { questionId: "suphline8c", pdfField: "form1[0].#subform[17].SupHLine8c[1]" },
  { questionId: "suphline8a1.types", pdfField: "form1[0].#subform[17].SupHLine8a1_Types[0]" },
  { questionId: "sec2line7c.citytown", pdfField: "form1[0].#subform[17].Sec2Line7c_CityTown[0]" },
  { questionId: "sec2line7c.zipcode", pdfField: "form1[0].#subform[17].Sec2Line7c_ZipCode[0]" },
  { questionId: "sec2line7c.state", pdfField: "form1[0].#subform[17].Sec2Line7c_State[0]" },
  { questionId: "sec2line7c.streetnumbername", pdfField: "form1[0].#subform[17].Sec2Line7c_StreetNumberName[0]", type: "checkbox" },
  { questionId: "sec2line7c.unit", pdfField: "form1[0].#subform[17].Sec2Line7c_Unit[0]", type: "checkbox" },
  { questionId: "sec2line7c.unit", pdfField: "form1[0].#subform[17].Sec2Line7c_Unit[1]", type: "checkbox" },
  { questionId: "sec2line7c.unit", pdfField: "form1[0].#subform[17].Sec2Line7c_Unit[2]" },
  { questionId: "sec2line7c.aptsteflrnumber", pdfField: "form1[0].#subform[17].Sec2Line7c_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "suphline8a", pdfField: "form1[0].#subform[17].SupHLine8a[0]", type: "checkbox" },
  { questionId: "suphline8a", pdfField: "form1[0].#subform[17].SupHLine8a[1]", type: "checkbox" },
  { questionId: "suphline12", pdfField: "form1[0].#subform[17].SupHLine12[0]", type: "checkbox" },
  { questionId: "suphline12", pdfField: "form1[0].#subform[17].SupHLine12[1]", type: "checkbox" },
  { questionId: "suphline13", pdfField: "form1[0].#subform[17].SupHLine13[0]", type: "checkbox" },
  { questionId: "suphline13", pdfField: "form1[0].#subform[17].SupHLine13[1]" },
  { questionId: "line7.recruitorganization", pdfField: "form1[0].#subform[17].Line7_RecruitOrganization[0]" },
  { questionId: "line7.middlename", pdfField: "form1[0].#subform[17].Line7_MiddleName[0]" },
  { questionId: "line7.givenname", pdfField: "form1[0].#subform[17].Line7_GivenName[0]" },
  { questionId: "line7.familyname", pdfField: "form1[0].#subform[17].Line7_FamilyName[0]", type: "checkbox" },
  { questionId: "suphline14", pdfField: "form1[0].#subform[18].SupHLine14[0]", type: "checkbox" },
  { questionId: "suphline14", pdfField: "form1[0].#subform[18].SupHLine14[1]", type: "checkbox" },
  { questionId: "suphline15", pdfField: "form1[0].#subform[18].SupHLine15[0]", type: "checkbox" },
  { questionId: "suphline15", pdfField: "form1[0].#subform[18].SupHLine15[1]", type: "checkbox" },
  { questionId: "suphline16", pdfField: "form1[0].#subform[18].SupHLine16[0]", type: "checkbox" },
  { questionId: "suphline16", pdfField: "form1[0].#subform[18].SupHLine16[1]", type: "checkbox" },
  { questionId: "suphline17", pdfField: "form1[0].#subform[18].SupHLine17[0]", type: "checkbox" },
  { questionId: "suphline17", pdfField: "form1[0].#subform[18].SupHLine17[1]", type: "checkbox" },
  { questionId: "suphline18", pdfField: "form1[0].#subform[18].SupHLine18[0]", type: "checkbox" },
  { questionId: "suphline18", pdfField: "form1[0].#subform[18].SupHLine18[1]", type: "checkbox" },
  { questionId: "suphline19", pdfField: "form1[0].#subform[18].SupHLine19[0]", type: "checkbox" },
  { questionId: "suphline19", pdfField: "form1[0].#subform[18].SupHLine19[1]", type: "checkbox" },
  { questionId: "suphline20", pdfField: "form1[0].#subform[18].SupHLine20[0]", type: "checkbox" },
  { questionId: "suphline20", pdfField: "form1[0].#subform[18].SupHLine20[1]" },
  { questionId: "sect3.parta.datesignedbypetitioner", pdfField: "form1[0].#subform[19].Sect3_PartA_DateSignedByPetitioner[0]" },
  { questionId: "sect3.parta.petitionername", pdfField: "form1[0].#subform[19].Sect3_PartA_PetitionerName[0]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[19].P5_Line6a_SignatureofApplicant[3]" },
  { questionId: "date", pdfField: "form1[0].#subform[19].Date[0]" },
  { questionId: "sect3.partb.employersignature", pdfField: "form1[0].#subform[19].Sect3_PartB_EmployerSignature[0]" },
  { questionId: "textfield5", pdfField: "form1[0].#subform[19].TextField5[0]", type: "checkbox" },
  { questionId: "suphline21", pdfField: "form1[0].#subform[19].SupHLine21[0]", type: "checkbox" },
  { questionId: "suphline21", pdfField: "form1[0].#subform[19].SupHLine21[1]", type: "checkbox" },
  { questionId: "suphline22", pdfField: "form1[0].#subform[19].SupHLine22[0]", type: "checkbox" },
  { questionId: "suphline22", pdfField: "form1[0].#subform[19].SupHLine22[1]", type: "checkbox" },
  { questionId: "suphline23", pdfField: "form1[0].#subform[19].SupHLine23[0]", type: "checkbox" },
  { questionId: "suphline23", pdfField: "form1[0].#subform[19].SupHLine23[1]" },
  { questionId: "line24.familyname", pdfField: "form1[0].#subform[19].Line24_FamilyName[0]" },
  { questionId: "line24.givenname", pdfField: "form1[0].#subform[19].Line24_GivenName[0]" },
  { questionId: "line24.middlename", pdfField: "form1[0].#subform[19].Line24_MiddleName[0]" },
  { questionId: "line24.petitionername", pdfField: "form1[0].#subform[19].Line24_PetitionerName[0]" },
  { questionId: "sect3.partc.datesigned1", pdfField: "form1[0].#subform[20].Sect3_PartC_DateSigned1[0]" },
  { questionId: "line24.citytown", pdfField: "form1[0].#subform[20].Line24_CityTown[0]" },
  { questionId: "line24.zipcode", pdfField: "form1[0].#subform[20].Line24_ZipCode[0]" },
  { questionId: "line24.state", pdfField: "form1[0].#subform[20].Line24_State[0]" },
  { questionId: "line24.incareofname", pdfField: "form1[0].#subform[20].Line24_InCareofName[0]" },
  { questionId: "line24.streetnumbername", pdfField: "form1[0].#subform[20].Line24_StreetNumberName[0]", type: "checkbox" },
  { questionId: "line24.unit", pdfField: "form1[0].#subform[20].Line24_Unit[0]", type: "checkbox" },
  { questionId: "line24.unit", pdfField: "form1[0].#subform[20].Line24_Unit[1]", type: "checkbox" },
  { questionId: "line24.unit", pdfField: "form1[0].#subform[20].Line24_Unit[2]" },
  { questionId: "line24.aptsteflrnumber", pdfField: "form1[0].#subform[20].Line24_AptSteFlrNumber[0]" },
  { questionId: "line24.postalcode", pdfField: "form1[0].#subform[20].Line24_PostalCode[0]" },
  { questionId: "line24.province", pdfField: "form1[0].#subform[20].Line24_Province[0]" },
  { questionId: "line24.country", pdfField: "form1[0].#subform[20].Line24_Country[0]" },
  { questionId: "line24.emailaddress", pdfField: "form1[0].#subform[20].Line24_EmailAddress[0]" },
  { questionId: "line24.daytimephonenumber1", pdfField: "form1[0].#subform[20].Line24_DaytimePhoneNumber1[0]" },
  { questionId: "line24.mobilephonenumber1", pdfField: "form1[0].#subform[20].Line24_MobilePhoneNumber1[0]" },
  { questionId: "line25.ein", pdfField: "form1[0].#subform[20].Line25_EIN[0]" },
  { questionId: "line25.ssn", pdfField: "form1[0].#subform[20].Line25_SSN[0]" },
  { questionId: "line25.taxnumber", pdfField: "form1[0].#subform[20].Line25_TaxNumber[0]" },
  { questionId: "line26.typeofbusiness", pdfField: "form1[0].#subform[20].Line26_TypeofBusiness[0]" },
  { questionId: "line26.yearestablished", pdfField: "form1[0].#subform[20].Line26_YearEstablished[0]" },
  { questionId: "line26.numberofemployees", pdfField: "form1[0].#subform[20].Line26_NumberofEmployees[0]" },
  { questionId: "line26.grossannualincome", pdfField: "form1[0].#subform[20].Line26_GrossAnnualIncome[0]" },
  { questionId: "line26.netannualincome", pdfField: "form1[0].#subform[20].Line26_NetAnnualIncome[0]" },
  { questionId: "line27.title", pdfField: "form1[0].#subform[20].Line27_Title[0]" },
  { questionId: "line27.givenname", pdfField: "form1[0].#subform[20].Line27_GivenName[0]" },
  { questionId: "line27.familyname", pdfField: "form1[0].#subform[20].Line27_FamilyName[0]" },
  { questionId: "sect3.partc.signature1", pdfField: "form1[0].#subform[20].Sect3_PartC_Signature1[0]", type: "checkbox" },
  { questionId: "hsec3line1a.yes", pdfField: "form1[0].#subform[21].HSec3Line1a_Yes[0]", type: "checkbox" },
  { questionId: "hsec3line1b.no", pdfField: "form1[0].#subform[21].HSec3Line1b_No[0]", type: "checkbox" },
  { questionId: "hsec3line1c.yes", pdfField: "form1[0].#subform[21].HSec3Line1c_Yes[0]", type: "checkbox" },
  { questionId: "hsec3line1d.no", pdfField: "form1[0].#subform[21].HSec3Line1d_No[0]", type: "checkbox" },
  { questionId: "hsec3line1e.yes", pdfField: "form1[0].#subform[21].HSec3Line1e_Yes[0]", type: "checkbox" },
  { questionId: "hsec3line7.check", pdfField: "form1[0].#subform[21].HSec3Line7_Check[0]", type: "checkbox" },
  { questionId: "hsec3line7.check", pdfField: "form1[0].#subform[21].HSec3Line7_Check[1]", type: "checkbox" },
  { questionId: "hsec3line1e.no", pdfField: "form1[0].#subform[21].HSec3Line1e_No[0]", type: "checkbox" },
  { questionId: "hsec3line1d.yes", pdfField: "form1[0].#subform[21].HSec3Line1d_Yes[0]", type: "checkbox" },
  { questionId: "hsec3line1c.no", pdfField: "form1[0].#subform[21].HSec3Line1c_No[0]", type: "checkbox" },
  { questionId: "hsec3line1b.yes", pdfField: "form1[0].#subform[21].HSec3Line1b_Yes[0]", type: "checkbox" },
  { questionId: "hsec3line1a.no", pdfField: "form1[0].#subform[21].HSec3Line1a_No[0]" },
  { questionId: "line2.explanation", pdfField: "form1[0].#subform[21].Line2_Explanation[0]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[22].Line1_FamilyName[2]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[22].Line1_FamilyName[3]", type: "checkbox" },
  { questionId: "a.no.diploma", pdfField: "form1[0].#subform[22].a_no_diploma[0]", type: "checkbox" },
  { questionId: "b.hsdiploma", pdfField: "form1[0].#subform[22].b_HSDiploma[0]", type: "checkbox" },
  { questionId: "c.some.college", pdfField: "form1[0].#subform[22].c_some_college[0]", type: "checkbox" },
  { questionId: "d.collegeplus", pdfField: "form1[0].#subform[22].d_collegeplus[0]", type: "checkbox" },
  { questionId: "e.associatedegree", pdfField: "form1[0].#subform[22].e_AssociateDegree[0]", type: "checkbox" },
  { questionId: "g.masterdegree", pdfField: "form1[0].#subform[22].g_MasterDegree[0]", type: "checkbox" },
  { questionId: "h.professionaldegree", pdfField: "form1[0].#subform[22].h_ProfessionalDegree[0]", type: "checkbox" },
  { questionId: "f.bachelordegree", pdfField: "form1[0].#subform[22].f_BachelorDegree[0]", type: "checkbox" },
  { questionId: "i.doctoratedegree", pdfField: "form1[0].#subform[22].i_DoctorateDegree[0]", type: "checkbox" },
  { questionId: "h1bsecaline1a.no", pdfField: "form1[0].#subform[22].H1BSecALine1a_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1b.yes", pdfField: "form1[0].#subform[22].H1BSecALine1b_Yes[0]", type: "checkbox" },
  { questionId: "h1bsecaline1c.no", pdfField: "form1[0].#subform[22].H1BSecALine1c_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1c1.yes", pdfField: "form1[0].#subform[22].H1BSecALine1c1_Yes[0]", type: "checkbox" },
  { questionId: "h1bsecaline1c2.no", pdfField: "form1[0].#subform[22].H1BSecALine1c2_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1d.no", pdfField: "form1[0].#subform[22].H1BSecALine1d_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1d1.yes", pdfField: "form1[0].#subform[22].H1BSecALine1d1_Yes[0]", type: "checkbox" },
  { questionId: "h1bsecaline1d1.no", pdfField: "form1[0].#subform[22].H1BSecALine1d1_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1d.yes", pdfField: "form1[0].#subform[22].H1BSecALine1d_Yes[0]", type: "checkbox" },
  { questionId: "h1bsecaline1c2.yes", pdfField: "form1[0].#subform[22].H1BSecALine1c2_Yes[0]", type: "checkbox" },
  { questionId: "h1bsecaline1c1.no", pdfField: "form1[0].#subform[22].H1BSecALine1c1_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1c.yes", pdfField: "form1[0].#subform[22].H1BSecALine1c_Yes[0]", type: "checkbox" },
  { questionId: "h1bsecaline1b.no", pdfField: "form1[0].#subform[22].H1BSecALine1b_No[0]", type: "checkbox" },
  { questionId: "h1bsecaline1a.yes", pdfField: "form1[0].#subform[22].H1BSecALine1a_Yes[0]" },
  { questionId: "parta.q3.field.of.study", pdfField: "form1[0].#subform[22].PartA_q3_Field_of_Study[0]" },
  { questionId: "line2f[0].line6.naicscode", pdfField: "form1[0].#subform[22].Line2f[0].Line6_NAICSCode[0]" },
  { questionId: "line2f[1].line5.dotcode", pdfField: "form1[0].#subform[22].Line2f[1].Line5_DOTCode[0]" },
  { questionId: "line4.rateofpayperyear", pdfField: "form1[0].#subform[22].Line4_RateofPayPerYear[0]", type: "checkbox" },
  { questionId: "h1bsec2line1.yes", pdfField: "form1[0].#subform[22].H1BSec2Line1_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line1.no", pdfField: "form1[0].#subform[22].H1BSec2Line1_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line2.no", pdfField: "form1[0].#subform[22].H1BSec2Line2_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line2.yes", pdfField: "form1[0].#subform[22].H1BSec2Line2_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line3.no", pdfField: "form1[0].#subform[23].H1BSec2Line3_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line4.yes", pdfField: "form1[0].#subform[23].H1BSec2Line4_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line5.no", pdfField: "form1[0].#subform[23].H1BSec2Line5_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line6.yes", pdfField: "form1[0].#subform[23].H1BSec2Line6_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line7.no", pdfField: "form1[0].#subform[23].H1BSec2Line7_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line8.yes", pdfField: "form1[0].#subform[23].H1BSec2Line8_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line9.no", pdfField: "form1[0].#subform[23].H1BSec2Line9_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line9.yes", pdfField: "form1[0].#subform[23].H1BSec2Line9_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line8.no", pdfField: "form1[0].#subform[23].H1BSec2Line8_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line7.yes", pdfField: "form1[0].#subform[23].H1BSec2Line7_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line6.no", pdfField: "form1[0].#subform[23].H1BSec2Line6_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line5.yes", pdfField: "form1[0].#subform[23].H1BSec2Line5_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec2line4.no", pdfField: "form1[0].#subform[23].H1BSec2Line4_No[0]", type: "checkbox" },
  { questionId: "h1bsec2line3.yes", pdfField: "form1[0].#subform[23].H1BSec2Line3_Yes[0]", type: "checkbox" },
  { questionId: "cap", pdfField: "form1[0].#subform[23].Cap[0]", type: "checkbox" },
  { questionId: "cap", pdfField: "form1[0].#subform[23].Cap[1]", type: "checkbox" },
  { questionId: "cap", pdfField: "form1[0].#subform[23].Cap[2]", type: "checkbox" },
  { questionId: "cap", pdfField: "form1[0].#subform[23].Cap[3]" },
  { questionId: "h1bsec3line2c.typeofdegree", pdfField: "form1[0].#subform[23].H1bSec3Line2c_TypeofDegree[0]" },
  { questionId: "h1bsec3line2b.datedegreeawarded", pdfField: "form1[0].#subform[23].H1bSec3Line2b_DateDegreeAwarded[0]" },
  { questionId: "h1bsec3line2a.name", pdfField: "form1[0].#subform[23].H1bSec3Line2a_Name[0]" },
  { questionId: "part7lineb.bemp1city", pdfField: "form1[0].#subform[23].Part7LineB_BEmp1City[0]" },
  { questionId: "part7lineb.bemp1state", pdfField: "form1[0].#subform[23].Part7LineB_BEmp1State[0]" },
  { questionId: "part7lineb.bemp1zipcode", pdfField: "form1[0].#subform[23].Part7LineB_BEmp1ZipCode[0]" },
  { questionId: "h1bsec3line2d.streetname", pdfField: "form1[0].#subform[23].H1bSec3Line2d_StreetName[0]" },
  { questionId: "sec3.aptsteflrnumber", pdfField: "form1[0].#subform[23].Sec3_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "lineb.unit", pdfField: "form1[0].#subform[23].Lineb_Unit[0]", type: "checkbox" },
  { questionId: "lineb.unit", pdfField: "form1[0].#subform[23].Lineb_Unit[1]", type: "checkbox" },
  { questionId: "lineb.unit", pdfField: "form1[0].#subform[23].Lineb_Unit[2]", type: "checkbox" },
  { questionId: "partc.3acheckbox", pdfField: "form1[0].#subform[24].PartC_3aCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3ccheckbox", pdfField: "form1[0].#subform[24].PartC_3cCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3bcheckbox", pdfField: "form1[0].#subform[24].PartC_3bCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3echeckbox", pdfField: "form1[0].#subform[24].PartC_3eCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3fcheckbox", pdfField: "form1[0].#subform[24].PartC_3fCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3dcheckbox", pdfField: "form1[0].#subform[24].PartC_3dCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3gcheckbox", pdfField: "form1[0].#subform[24].PartC_3gCheckbox[0]", type: "checkbox" },
  { questionId: "partc.3hcheckbox", pdfField: "form1[0].#subform[24].PartC_3hCheckbox[0]", type: "checkbox" },
  { questionId: "h1bsec4line1a.yes", pdfField: "form1[0].#subform[24].H1BSec4Line1a_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec4line1a.no", pdfField: "form1[0].#subform[24].H1BSec4Line1a_No[0]", type: "checkbox" },
  { questionId: "h1bsec4line1b.yes", pdfField: "form1[0].#subform[24].H1BSec4Line1b_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec4line1c.no", pdfField: "form1[0].#subform[24].H1BSec4Line1c_No[0]", type: "checkbox" },
  { questionId: "h1bsec4line1c.yes", pdfField: "form1[0].#subform[24].H1BSec4Line1c_Yes[0]", type: "checkbox" },
  { questionId: "h1bsec4line1b.no", pdfField: "form1[0].#subform[24].H1BSec4Line1b_No[0]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[25].Line1_FamilyName[4]" },
  { questionId: "hsupline2.familyname", pdfField: "form1[0].#subform[25].HSupLine2_FamilyName[0]", type: "checkbox" },
  { questionId: "a.individual", pdfField: "form1[0].#subform[25].a_individual[0]", type: "checkbox" },
  { questionId: "b.blanket", pdfField: "form1[0].#subform[25].b_blanket[0]", type: "checkbox" },
  { questionId: "lsuppline4a", pdfField: "form1[0].#subform[25].LSuppLine4a[0]", type: "checkbox" },
  { questionId: "lsuppline4b.yes", pdfField: "form1[0].#subform[25].LSuppLine4b_Yes[0]", type: "checkbox" },
  { questionId: "lsuppline4b.no", pdfField: "form1[0].#subform[25].LSuppLine4b_No[0]", type: "checkbox" },
  { questionId: "lsuppline4a", pdfField: "form1[0].#subform[25].LSuppLine4a[1]" },
  { questionId: "table2[0].row1[0].sect1.name.line1", pdfField: "form1[0].#subform[25].Table2[0].Row1[0].Sect1_Name_Line1[0]" },
  { questionId: "table2[0].row1[0].datefrom.line1", pdfField: "form1[0].#subform[25].Table2[0].Row1[0].DateFrom_line1[0]" },
  { questionId: "table2[0].row1[0].dateto.line1", pdfField: "form1[0].#subform[25].Table2[0].Row1[0].DateTo_line1[0]" },
  { questionId: "table2[0].row2[0].sect1.name.line2", pdfField: "form1[0].#subform[25].Table2[0].Row2[0].Sect1_Name_Line2[0]" },
  { questionId: "table2[0].row2[0].datefrom.line2", pdfField: "form1[0].#subform[25].Table2[0].Row2[0].DateFrom_line2[0]" },
  { questionId: "table2[0].row2[0].dateto.line2", pdfField: "form1[0].#subform[25].Table2[0].Row2[0].DateTo_line2[0]" },
  { questionId: "table2[0].row3[0].sect1.name.line3", pdfField: "form1[0].#subform[25].Table2[0].Row3[0].Sect1_Name_Line3[0]" },
  { questionId: "table2[0].row3[0].datefrom.line3", pdfField: "form1[0].#subform[25].Table2[0].Row3[0].DateFrom_line3[0]" },
  { questionId: "table2[0].row3[0].dateto.line3", pdfField: "form1[0].#subform[25].Table2[0].Row3[0].DateTo_line3[0]" },
  { questionId: "table2[0].row4[0].sect1.name.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[0].Sect1_Name_Line3[0]" },
  { questionId: "table2[0].row4[0].datefrom.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[0].DateFrom_line3[0]" },
  { questionId: "table2[0].row4[0].dateto.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[0].DateTo_line3[0]" },
  { questionId: "table2[0].row4[1].sect1.name.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[1].Sect1_Name_Line3[0]" },
  { questionId: "table2[0].row4[1].datefrom.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[1].DateFrom_line3[0]" },
  { questionId: "table2[0].row4[1].dateto.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[1].DateTo_line3[0]" },
  { questionId: "table2[0].row4[2].sect1.name.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[2].Sect1_Name_Line3[0]" },
  { questionId: "table2[0].row4[2].datefrom.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[2].DateFrom_line3[0]" },
  { questionId: "table2[0].row4[2].dateto.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[2].DateTo_line3[0]" },
  { questionId: "table2[0].row4[3].sect1.name.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[3].Sect1_Name_Line3[0]" },
  { questionId: "table2[0].row4[3].datefrom.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[3].DateFrom_line3[0]" },
  { questionId: "table2[0].row4[3].dateto.line3", pdfField: "form1[0].#subform[25].Table2[0].Row4[3].DateTo_line3[0]", type: "checkbox" },
  { questionId: "a.l1a", pdfField: "form1[0].#subform[25].a_L1A[0]", type: "checkbox" },
  { questionId: "b.l1b", pdfField: "form1[0].#subform[25].b_L1B[0]" },
  { questionId: "part3line2.city", pdfField: "form1[0].#subform[25].Part3Line2_City[0]" },
  { questionId: "part3line2.state", pdfField: "form1[0].#subform[25].Part3Line2_State[0]" },
  { questionId: "part3line2.zipcode", pdfField: "form1[0].#subform[25].Part3Line2_ZipCode[0]" },
  { questionId: "part3line2.streetname", pdfField: "form1[0].#subform[25].Part3Line2_StreetName[0]" },
  { questionId: "line2.aptsteflrnumber", pdfField: "form1[0].#subform[25].Line2_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "lclassline4.unit", pdfField: "form1[0].#subform[25].LClassLine4_Unit[0]", type: "checkbox" },
  { questionId: "lclassline4.unit", pdfField: "form1[0].#subform[25].LClassLine4_Unit[1]", type: "checkbox" },
  { questionId: "lclassline4.unit", pdfField: "form1[0].#subform[25].LClassLine4_Unit[2]" },
  { questionId: "lsuppline3.nameofemployerabroad", pdfField: "form1[0].#subform[25].LSuppLine3_NameofEmployerAbroad[0]" },
  { questionId: "part3line2.province", pdfField: "form1[0].#subform[25].Part3Line2_Province[0]" },
  { questionId: "part3line2.country", pdfField: "form1[0].#subform[25].Part3Line2_Country[0]" },
  { questionId: "part3line2.postalcode", pdfField: "form1[0].#subform[25].Part3Line2_PostalCode[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[27].Line3_JobDescription[1]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[27].Line3_JobDescription[2]" },
  { questionId: "table3[0].row1[0].q5.datefrom.line1", pdfField: "form1[0].#subform[27].Table3[0].Row1[0].q5_DateFrom_Line1[0]" },
  { questionId: "table3[0].row1[0].q5.dateto.line1", pdfField: "form1[0].#subform[27].Table3[0].Row1[0].q5_DateTo_Line1[0]" },
  { questionId: "table3[0].row1[0].q5.explanation.line1", pdfField: "form1[0].#subform[27].Table3[0].Row1[0].q5_Explanation_Line1[0]" },
  { questionId: "table3[0].row2[0].q5.datefrom.line2", pdfField: "form1[0].#subform[27].Table3[0].Row2[0].q5_DateFrom_Line2[0]" },
  { questionId: "table3[0].row2[0].q5.dateto.line2", pdfField: "form1[0].#subform[27].Table3[0].Row2[0].q5_DateTo_Line2[0]" },
  { questionId: "table3[0].row2[0].q5.explanation.line2", pdfField: "form1[0].#subform[27].Table3[0].Row2[0].q5_Explanation_Line2[0]" },
  { questionId: "table3[0].row3[0].q5.datefrom.line3", pdfField: "form1[0].#subform[27].Table3[0].Row3[0].q5_DateFrom_Line3[0]" },
  { questionId: "table3[0].row3[0].q5.dateto.line3", pdfField: "form1[0].#subform[27].Table3[0].Row3[0].q5_DateTo_Line3[0]" },
  { questionId: "table3[0].row3[0].q5.explanation.line3", pdfField: "form1[0].#subform[27].Table3[0].Row3[0].q5_Explanation_Line3[0]" },
  { questionId: "table3[0].row4[0].q5.datefrom.line4", pdfField: "form1[0].#subform[27].Table3[0].Row4[0].q5_DateFrom_Line4[0]" },
  { questionId: "table3[0].row4[0].q5.dateto.line4", pdfField: "form1[0].#subform[27].Table3[0].Row4[0].q5_DateTo_Line4[0]" },
  { questionId: "table3[0].row4[0].q5.explanation.line4", pdfField: "form1[0].#subform[27].Table3[0].Row4[0].q5_Explanation_Line4[0]" },
  { questionId: "table3[0].row4[1].q5.datefrom.line5", pdfField: "form1[0].#subform[27].Table3[0].Row4[1].q5_DateFrom_Line5[0]" },
  { questionId: "table3[0].row4[1].q5.dateto.line5", pdfField: "form1[0].#subform[27].Table3[0].Row4[1].q5_DateTo_Line5[0]" },
  { questionId: "table3[0].row4[1].q5.explanation.line5", pdfField: "form1[0].#subform[27].Table3[0].Row4[1].q5_Explanation_Line5[0]" },
  { questionId: "table3[0].row4[2].q5.datefrom.line6", pdfField: "form1[0].#subform[27].Table3[0].Row4[2].q5_DateFrom_Line6[0]" },
  { questionId: "table3[0].row4[2].q5.dateto.line6", pdfField: "form1[0].#subform[27].Table3[0].Row4[2].q5_DateTo_Line6[0]" },
  { questionId: "table3[0].row4[2].q5.explanation.line6", pdfField: "form1[0].#subform[27].Table3[0].Row4[2].q5_Explanation_Line6[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[27].Line3_JobDescription[3]", type: "checkbox" },
  { questionId: "a.parent", pdfField: "form1[0].#subform[27].a_Parent[0]", type: "checkbox" },
  { questionId: "b.branch", pdfField: "form1[0].#subform[27].b_Branch[0]", type: "checkbox" },
  { questionId: "c.subsidiary", pdfField: "form1[0].#subform[27].c_Subsidiary[0]", type: "checkbox" },
  { questionId: "d.affiliate", pdfField: "form1[0].#subform[27].d_Affiliate[0]", type: "checkbox" },
  { questionId: "e.jointventure", pdfField: "form1[0].#subform[27].e_JointVenture[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[29].Line3_JobDescription[4]" },
  { questionId: "table4[0].row1[0].line1", pdfField: "form1[0].#subform[29].Table4[0].Row1[0].Line1[0]" },
  { questionId: "table4[0].row1[0].fein.line1", pdfField: "form1[0].#subform[29].Table4[0].Row1[0].FEIN_Line1[0]" },
  { questionId: "table4[0].row2[0].line2", pdfField: "form1[0].#subform[29].Table4[0].Row2[0].Line2[0]" },
  { questionId: "table4[0].row2[0].fein.line2", pdfField: "form1[0].#subform[29].Table4[0].Row2[0].FEIN_Line2[0]" },
  { questionId: "table4[0].row3[0].line3", pdfField: "form1[0].#subform[29].Table4[0].Row3[0].Line3[0]" },
  { questionId: "table4[0].row3[0].fein.line3", pdfField: "form1[0].#subform[29].Table4[0].Row3[0].FEIN_Line3[0]" },
  { questionId: "table4[0].row4[0].line4", pdfField: "form1[0].#subform[29].Table4[0].Row4[0].Line4[0]" },
  { questionId: "table4[0].row4[0].fein.line4", pdfField: "form1[0].#subform[29].Table4[0].Row4[0].FEIN_Line4[0]" },
  { questionId: "table4[0].row4[1].line5", pdfField: "form1[0].#subform[29].Table4[0].Row4[1].Line5[0]" },
  { questionId: "table4[0].row4[1].fein.line5", pdfField: "form1[0].#subform[29].Table4[0].Row4[1].FEIN_Line5[0]", type: "checkbox" },
  { questionId: "lsec1line11.no", pdfField: "form1[0].#subform[29].LSec1Line11_No[0]", type: "checkbox" },
  { questionId: "lsec1line12.yes", pdfField: "form1[0].#subform[29].LSec1Line12_Yes[0]", type: "checkbox" },
  { questionId: "lsec1line12", pdfField: "form1[0].#subform[29].LSec1Line12[0]", type: "checkbox" },
  { questionId: "lsec1line12", pdfField: "form1[0].#subform[29].LSec1Line12[1]", type: "checkbox" },
  { questionId: "lsec1line12.no", pdfField: "form1[0].#subform[29].LSec1Line12_No[0]", type: "checkbox" },
  { questionId: "lsec1line11.yes", pdfField: "form1[0].#subform[29].LSec1Line11_Yes[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[29].Line3_JobDescription[5]" },
  { questionId: "table5[0].row1[0].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row1[0].Cell1[0]" },
  { questionId: "table5[0].row1[0].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row1[0].Cell2[0]" },
  { questionId: "table5[0].row2[0].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row2[0].Cell1[0]" },
  { questionId: "table5[0].row2[0].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row2[0].Cell2[0]" },
  { questionId: "table5[0].row3[0].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row3[0].Cell1[0]" },
  { questionId: "table5[0].row3[0].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row3[0].Cell2[0]" },
  { questionId: "table5[0].row4[0].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row4[0].Cell1[0]" },
  { questionId: "table5[0].row4[0].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row4[0].Cell2[0]" },
  { questionId: "table5[0].row4[1].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row4[1].Cell1[0]" },
  { questionId: "table5[0].row4[1].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row4[1].Cell2[0]" },
  { questionId: "table5[0].row4[2].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row4[2].Cell1[0]" },
  { questionId: "table5[0].row4[2].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row4[2].Cell2[0]" },
  { questionId: "table5[0].row4[3].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row4[3].Cell1[0]" },
  { questionId: "table5[0].row4[3].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row4[3].Cell2[0]" },
  { questionId: "table5[0].row4[4].cell1", pdfField: "form1[0].#subform[31].Table5[0].Row4[4].Cell1[0]" },
  { questionId: "table5[0].row4[4].cell2", pdfField: "form1[0].#subform[31].Table5[0].Row4[4].Cell2[0]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[33].Line1_FamilyName[5]", type: "checkbox" },
  { questionId: "b.o1b", pdfField: "form1[0].#subform[33].b_O1B[0]", type: "checkbox" },
  { questionId: "a.o1a", pdfField: "form1[0].#subform[33].a_O1A[0]", type: "checkbox" },
  { questionId: "d.p1.majorleague", pdfField: "form1[0].#subform[33].d_P1_majorleague[0]", type: "checkbox" },
  { questionId: "e.p1", pdfField: "form1[0].#subform[33].e_P1[0]", type: "checkbox" },
  { questionId: "c.o2", pdfField: "form1[0].#subform[33].c_O2[0]", type: "checkbox" },
  { questionId: "f.p1s", pdfField: "form1[0].#subform[33].f_P1S[0]", type: "checkbox" },
  { questionId: "g.p2", pdfField: "form1[0].#subform[33].g_P2[0]", type: "checkbox" },
  { questionId: "h.p2s", pdfField: "form1[0].#subform[33].h_P2S[0]", type: "checkbox" },
  { questionId: "i.p3", pdfField: "form1[0].#subform[33].i_P3[0]", type: "checkbox" },
  { questionId: "j.p3s", pdfField: "form1[0].#subform[33].j_P3S[0]" },
  { questionId: "hsupline2.familyname", pdfField: "form1[0].#subform[33].HSupLine2_FamilyName[1]" },
  { questionId: "line2.ttlnumberofbeneficiaries", pdfField: "form1[0].#subform[33].Line2_TtlNumberofBeneficiaries[1]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[33].Line3_JobDescription[6]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[33].Line3_JobDescription[7]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[33].Line3_JobDescription[8]", type: "checkbox" },
  { questionId: "oandpsuppline7", pdfField: "form1[0].#subform[33].OandPSuppLine7[0]", type: "checkbox" },
  { questionId: "oandpsuppline7", pdfField: "form1[0].#subform[33].OandPSuppLine7[1]" },
  { questionId: "part7line10b.empcity", pdfField: "form1[0].#subform[34].Part7Line10b_EmpCity[0]" },
  { questionId: "part7line10b.emp1state", pdfField: "form1[0].#subform[34].Part7Line10b_Emp1State[0]" },
  { questionId: "part7line10b.emp1zipcode", pdfField: "form1[0].#subform[34].Part7Line10b_Emp1ZipCode[0]" },
  { questionId: "part7line10b.emp1streetname", pdfField: "form1[0].#subform[34].Part7Line10b_Emp1StreetName[0]" },
  { questionId: "part7line10c.emp1fromdate", pdfField: "form1[0].#subform[34].Part7Line10c_Emp1FromDate[0]" },
  { questionId: "line10b.aptsteflrnumber", pdfField: "form1[0].#subform[34].Line10b_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "line10b.unit", pdfField: "form1[0].#subform[34].Line10b_Unit[0]", type: "checkbox" },
  { questionId: "line10b.unit", pdfField: "form1[0].#subform[34].Line10b_Unit[1]", type: "checkbox" },
  { questionId: "line10b.unit", pdfField: "form1[0].#subform[34].Line10b_Unit[2]" },
  { questionId: "lsuppline10a.nameofpeer", pdfField: "form1[0].#subform[34].LSuppLine10a_NameofPeer[0]" },
  { questionId: "part7line11b.empcity", pdfField: "form1[0].#subform[34].Part7Line11b_EmpCity[0]" },
  { questionId: "part7line11b.emp1state", pdfField: "form1[0].#subform[34].Part7Line11b_Emp1State[0]" },
  { questionId: "part7line11b.emp1zipcode", pdfField: "form1[0].#subform[34].Part7Line11b_Emp1ZipCode[0]" },
  { questionId: "part7line11b.emp1streetname", pdfField: "form1[0].#subform[34].Part7Line11b_Emp1StreetName[0]" },
  { questionId: "part7lin11c.emp1fromdate", pdfField: "form1[0].#subform[34].Part7Lin11c_Emp1FromDate[0]" },
  { questionId: "line11b.aptsteflrnumber", pdfField: "form1[0].#subform[34].Line11b_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "line11b.unit", pdfField: "form1[0].#subform[34].Line11b_Unit[0]", type: "checkbox" },
  { questionId: "line11b.unit", pdfField: "form1[0].#subform[34].Line11b_Unit[1]", type: "checkbox" },
  { questionId: "line11b.unit", pdfField: "form1[0].#subform[34].Line11b_Unit[2]" },
  { questionId: "lsuppline11a.nameofpeer", pdfField: "form1[0].#subform[34].LSuppLine11a_NameofPeer[0]" },
  { questionId: "part7line12b.empcity", pdfField: "form1[0].#subform[34].Part7Line12b_EmpCity[0]" },
  { questionId: "part7line12b.emp1state", pdfField: "form1[0].#subform[34].Part7Line12b_Emp1State[0]" },
  { questionId: "part7line12b.emp1zipcode", pdfField: "form1[0].#subform[34].Part7Line12b_Emp1ZipCode[0]" },
  { questionId: "part7line12b.emp1streetname", pdfField: "form1[0].#subform[34].Part7Line12b_Emp1StreetName[0]" },
  { questionId: "part7line12c.emp1fromdate", pdfField: "form1[0].#subform[34].Part7Line12c_Emp1FromDate[0]" },
  { questionId: "line12b.aptsteflrnumber", pdfField: "form1[0].#subform[34].Line12b_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "line12b.unit", pdfField: "form1[0].#subform[34].Line12b_Unit[0]", type: "checkbox" },
  { questionId: "line12b.unit", pdfField: "form1[0].#subform[34].Line12b_Unit[1]", type: "checkbox" },
  { questionId: "line12b.unit", pdfField: "form1[0].#subform[34].Line12b_Unit[2]" },
  { questionId: "lsuppline12a.nameofpeer", pdfField: "form1[0].#subform[34].LSuppLine12a_NameofPeer[0]", type: "checkbox" },
  { questionId: "oandpsuppline7.yes", pdfField: "form1[0].#subform[34].OandPSuppLine7_Yes[0]", type: "checkbox" },
  { questionId: "oandpsuppline8", pdfField: "form1[0].#subform[34].OandPSuppLine8[0]", type: "checkbox" },
  { questionId: "oandpsuppline8", pdfField: "form1[0].#subform[34].OandPSuppLine8[1]", type: "checkbox" },
  { questionId: "oandpsuppline8", pdfField: "form1[0].#subform[34].OandPSuppLine8[2]", type: "checkbox" },
  { questionId: "oandpsuppline7.no", pdfField: "form1[0].#subform[34].OandPSuppLine7_No[0]" },
  { questionId: "line1.duties", pdfField: "form1[0].#subform[34].Line1_Duties[1]" },
  { questionId: "preparer.daytimephonenumber1.10d", pdfField: "form1[0].#subform[34].Preparer_DaytimePhoneNumber1_10d[0]" },
  { questionId: "preparer.daytimephonenumber1.11d", pdfField: "form1[0].#subform[34].Preparer_DaytimePhoneNumber1_11d[0]" },
  { questionId: "preparer.daytimephonenumber1.12d", pdfField: "form1[0].#subform[34].Preparer_DaytimePhoneNumber1_12d[0]" },
  { questionId: "part7line13b.empcity", pdfField: "form1[0].#subform[35].Part7Line13b_EmpCity[0]" },
  { questionId: "part7line13b.emp1state", pdfField: "form1[0].#subform[35].Part7Line13b_Emp1State[0]" },
  { questionId: "part7line13b.emp1zipcode", pdfField: "form1[0].#subform[35].Part7Line13b_Emp1ZipCode[0]" },
  { questionId: "part7line13b.emp1streetname", pdfField: "form1[0].#subform[35].Part7Line13b_Emp1StreetName[0]" },
  { questionId: "part7line13c.emp1fromdate", pdfField: "form1[0].#subform[35].Part7Line13c_Emp1FromDate[0]" },
  { questionId: "line13b.aptsteflrnumber", pdfField: "form1[0].#subform[35].Line13b_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "line13b.unit", pdfField: "form1[0].#subform[35].Line13b_Unit[0]", type: "checkbox" },
  { questionId: "line13b.unit", pdfField: "form1[0].#subform[35].Line13b_Unit[1]", type: "checkbox" },
  { questionId: "line13b.unit", pdfField: "form1[0].#subform[35].Line13b_Unit[2]" },
  { questionId: "lsuppline13a.nameofpeer", pdfField: "form1[0].#subform[35].LSuppLine13a_NameofPeer[0]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[35].Line1_FamilyName[6]" },
  { questionId: "line1.givenname", pdfField: "form1[0].#subform[35].Line1_GivenName[2]" },
  { questionId: "line1.middlename", pdfField: "form1[0].#subform[35].Line1_MiddleName[2]" },
  { questionId: "line1b.dateofsignature", pdfField: "form1[0].#subform[35].Line1b_DateofSignature[1]" },
  { questionId: "pt7line3.emailaddress", pdfField: "form1[0].#subform[35].Pt7Line3_EmailAddress[1]" },
  { questionId: "preparer.daytimephonenumber1.13d", pdfField: "form1[0].#subform[35].Preparer_DaytimePhoneNumber1_13d[0]" },
  { questionId: "pt7line3.daytimephonenumber1", pdfField: "form1[0].#subform[35].Pt7Line3_DaytimePhoneNumber1[1]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[35].P5_Line6a_SignatureofApplicant[4]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[36].Line1_FamilyName[7]" },
  { questionId: "hsupline2.familyname", pdfField: "form1[0].#subform[36].HSupLine2_FamilyName[2]" },
  { questionId: "line1.givenname", pdfField: "form1[0].#subform[36].Line1_GivenName[3]" },
  { questionId: "line1.middlename", pdfField: "form1[0].#subform[36].Line1_MiddleName[3]" },
  { questionId: "line1b.dateofsignature", pdfField: "form1[0].#subform[36].Line1b_DateofSignature[2]" },
  { questionId: "pt7line3.emailaddress", pdfField: "form1[0].#subform[36].Pt7Line3_EmailAddress[2]" },
  { questionId: "pt7line3.daytimephonenumber1", pdfField: "form1[0].#subform[36].Pt7Line3_DaytimePhoneNumber1[2]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[36].P5_Line6a_SignatureofApplicant[5]" },
  { questionId: "line1.familyname", pdfField: "form1[0].#subform[36].Line1_FamilyName[8]" },
  { questionId: "ttlnumbersofworker", pdfField: "form1[0].#subform[37].TtlNumbersofWorker[1]" },
  { questionId: "ttlnumbersofworker", pdfField: "form1[0].#subform[37].TtlNumbersofWorker[2]" },
  { questionId: "ttlnumbersofworker", pdfField: "form1[0].#subform[37].TtlNumbersofWorker[3]" },
  { questionId: "ttlnumbersofworker", pdfField: "form1[0].#subform[37].TtlNumbersofWorker[4]", type: "checkbox" },
  { questionId: "r1sec1line2", pdfField: "form1[0].#subform[37].R1Sec1Line2[0]", type: "checkbox" },
  { questionId: "r1sec1line2", pdfField: "form1[0].#subform[37].R1Sec1Line2[1]" },
  { questionId: "table2[1].row1[0].familymembername.line1", pdfField: "form1[0].#subform[37].Table2[1].Row1[0].FamilyMemberName_Line1[0]" },
  { questionId: "table2[1].row1[0].fromdate1", pdfField: "form1[0].#subform[37].Table2[1].Row1[0].FromDate1[0]" },
  { questionId: "table2[1].row1[0].todate1", pdfField: "form1[0].#subform[37].Table2[1].Row1[0].ToDate1[0]" },
  { questionId: "table2[1].row2[0].familymembername2", pdfField: "form1[0].#subform[37].Table2[1].Row2[0].FamilyMemberName2[0]" },
  { questionId: "table2[1].row2[0].fromdate2", pdfField: "form1[0].#subform[37].Table2[1].Row2[0].FromDate2[0]" },
  { questionId: "table2[1].row2[0].todate2", pdfField: "form1[0].#subform[37].Table2[1].Row2[0].ToDate2[0]" },
  { questionId: "table2[1].row3[0].familymembername3", pdfField: "form1[0].#subform[37].Table2[1].Row3[0].FamilyMemberName3[0]" },
  { questionId: "table2[1].row3[0].fromdate3", pdfField: "form1[0].#subform[37].Table2[1].Row3[0].FromDate3[0]" },
  { questionId: "table2[1].row3[0].todate3", pdfField: "form1[0].#subform[37].Table2[1].Row3[0].ToDate3[0]" },
  { questionId: "table2[1].row3[1].familymembername4", pdfField: "form1[0].#subform[37].Table2[1].Row3[1].FamilyMemberName4[0]" },
  { questionId: "table2[1].row3[1].fromdate4", pdfField: "form1[0].#subform[37].Table2[1].Row3[1].FromDate4[0]" },
  { questionId: "table2[1].row3[1].todate4", pdfField: "form1[0].#subform[37].Table2[1].Row3[1].ToDate4[0]" },
  { questionId: "table2[1].row3[2].familymembername5", pdfField: "form1[0].#subform[37].Table2[1].Row3[2].FamilyMemberName5[0]" },
  { questionId: "table2[1].row3[2].fromdate5", pdfField: "form1[0].#subform[37].Table2[1].Row3[2].FromDate5[0]" },
  { questionId: "table2[1].row3[2].todate5", pdfField: "form1[0].#subform[37].Table2[1].Row3[2].ToDate5[0]" },
  { questionId: "table2[1].row3[3].familymembername6", pdfField: "form1[0].#subform[37].Table2[1].Row3[3].FamilyMemberName6[0]" },
  { questionId: "table2[1].row3[3].fromdate6", pdfField: "form1[0].#subform[37].Table2[1].Row3[3].FromDate6[0]" },
  { questionId: "table2[1].row3[3].todate6", pdfField: "form1[0].#subform[37].Table2[1].Row3[3].ToDate6[0]" },
  { questionId: "table2[1].row3[4].familymembername7", pdfField: "form1[0].#subform[37].Table2[1].Row3[4].FamilyMemberName7[0]" },
  { questionId: "table2[1].row3[4].fromdate7", pdfField: "form1[0].#subform[37].Table2[1].Row3[4].FromDate7[0]" },
  { questionId: "table2[1].row3[4].todate7", pdfField: "form1[0].#subform[37].Table2[1].Row3[4].ToDate7[0]" },
  { questionId: "line1.petitionername", pdfField: "form1[0].#subform[37].Line1_PetitionerName[1]" },
  { questionId: "line2.beneficiaryname", pdfField: "form1[0].#subform[37].Line2_BeneficiaryName[1]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[39].Line3_JobDescription[9]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[39].Line3_JobDescription[10]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[39].Line3_JobDescription[11]" },
  { questionId: "table3[1].row1[0].position1", pdfField: "form1[0].#subform[39].Table3[1].Row1[0].Position1[0]" },
  { questionId: "table3[1].row1[0].summary1", pdfField: "form1[0].#subform[39].Table3[1].Row1[0].Summary1[0]" },
  { questionId: "table3[1].row2[0].position2", pdfField: "form1[0].#subform[39].Table3[1].Row2[0].Position2[0]" },
  { questionId: "table3[1].row2[0].summary2", pdfField: "form1[0].#subform[39].Table3[1].Row2[0].Summary2[0]" },
  { questionId: "table3[1].row2[1].position3", pdfField: "form1[0].#subform[39].Table3[1].Row2[1].Position3[0]" },
  { questionId: "table3[1].row2[1].summary3", pdfField: "form1[0].#subform[39].Table3[1].Row2[1].Summary3[0]" },
  { questionId: "table3[1].row2[2].position4", pdfField: "form1[0].#subform[39].Table3[1].Row2[2].Position4[0]" },
  { questionId: "table3[1].row2[2].summary4", pdfField: "form1[0].#subform[39].Table3[1].Row2[2].Summary4[0]" },
  { questionId: "table3[1].row2[3].position5", pdfField: "form1[0].#subform[39].Table3[1].Row2[3].Position5[0]" },
  { questionId: "table3[1].row2[3].summary5", pdfField: "form1[0].#subform[39].Table3[1].Row2[3].Summary5[0]" },
  { questionId: "table3[1].row2[4].position6", pdfField: "form1[0].#subform[39].Table3[1].Row2[4].Position6[0]" },
  { questionId: "table3[1].row2[4].summary6", pdfField: "form1[0].#subform[39].Table3[1].Row2[4].Summary6[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[39].Line3_JobDescription[12]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[39].Line3_JobDescription[13]" },
  { questionId: "r1sec1line6a1.explanation", pdfField: "form1[0].#subform[41].R1Sec1Line6a1_Explanation[0]", type: "checkbox" },
  { questionId: "r1sec1line7a", pdfField: "form1[0].#subform[41].R1Sec1Line7a[0]", type: "checkbox" },
  { questionId: "r1sec1line7a", pdfField: "form1[0].#subform[41].R1Sec1Line7a[1]" },
  { questionId: "r1sec1line7a1.explanation", pdfField: "form1[0].#subform[41].R1Sec1Line7a1_Explanation[0]" },
  { questionId: "line3.jobdescription", pdfField: "form1[0].#subform[41].Line3_JobDescription[14]", type: "checkbox" },
  { questionId: "r1sec1line6a", pdfField: "form1[0].#subform[41].R1Sec1Line6a[0]", type: "checkbox" },
  { questionId: "r1sec1line6a", pdfField: "form1[0].#subform[41].R1Sec1Line6a[1]", type: "checkbox" },
  { questionId: "r1sec1line8a", pdfField: "form1[0].#subform[41].R1Sec1Line8a[0]", type: "checkbox" },
  { questionId: "r1sec1line8a", pdfField: "form1[0].#subform[41].R1Sec1Line8a[1]" },
  { questionId: "r1sec1line8a1.explanation", pdfField: "form1[0].#subform[41].R1Sec1Line8a1_Explanation[0]" },
  { questionId: "r1sec1line9a1.explanation", pdfField: "form1[0].#subform[41].R1Sec1Line9a1_Explanation[0]", type: "checkbox" },
  { questionId: "r1sec1line9a", pdfField: "form1[0].#subform[41].R1Sec1Line9a[0]", type: "checkbox" },
  { questionId: "r1sec1line9a", pdfField: "form1[0].#subform[41].R1Sec1Line9a[1]" },
  { questionId: "r1sec1line10a1.explanation", pdfField: "form1[0].#subform[42].R1Sec1Line10a1_Explanation[0]" },
  { questionId: "r1sec1line11a1.explanation", pdfField: "form1[0].#subform[42].R1Sec1Line11a1_Explanation[0]" },
  { questionId: "r1sec1line12a1.explanation", pdfField: "form1[0].#subform[42].R1Sec1Line12a1_Explanation[0]", type: "checkbox" },
  { questionId: "r1sec1line10a", pdfField: "form1[0].#subform[42].R1Sec1Line10a[0]", type: "checkbox" },
  { questionId: "r1sec1line10a", pdfField: "form1[0].#subform[42].R1Sec1Line10a[1]", type: "checkbox" },
  { questionId: "r1sec1line11a.yes", pdfField: "form1[0].#subform[42].R1Sec1Line11a_Yes[0]", type: "checkbox" },
  { questionId: "r1sec1line11a.no", pdfField: "form1[0].#subform[42].R1Sec1Line11a_No[0]", type: "checkbox" },
  { questionId: "r1sec1line12a", pdfField: "form1[0].#subform[42].R1Sec1Line12a[0]", type: "checkbox" },
  { questionId: "r1sec1line12a", pdfField: "form1[0].#subform[42].R1Sec1Line12a[1]" },
  { questionId: "part14.dateofsignature", pdfField: "form1[0].#subform[42].Part14_DateofSignature[0]" },
  { questionId: "part14.preparerprintedname", pdfField: "form1[0].#subform[42].Part14_PreparerPrintedName[0]" },
  { questionId: "line5.jobtitle", pdfField: "form1[0].#subform[42].Line5_JobTitle[0]" },
  { questionId: "part14.firmname", pdfField: "form1[0].#subform[42].Part14_FirmName[0]" },
  { questionId: "part5.6a.signatureofApplicant", pdfField: "form1[0].#subform[42].P5_Line6a_SignatureofApplicant[6]" },
  { questionId: "part14.city", pdfField: "form1[0].#subform[43].Part14_City[0]" },
  { questionId: "line2.state", pdfField: "form1[0].#subform[43].Line2_State[0]" },
  { questionId: "part14.zipcode", pdfField: "form1[0].#subform[43].Part14_ZipCode[0]" },
  { questionId: "part14.streetname", pdfField: "form1[0].#subform[43].Part14_StreetName[0]" },
  { questionId: "sec1.aptsteflrnumber", pdfField: "form1[0].#subform[43].Sec1_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "sec1.unit", pdfField: "form1[0].#subform[43].Sec1_Unit[0]", type: "checkbox" },
  { questionId: "sec1.unit", pdfField: "form1[0].#subform[43].Sec1_Unit[1]", type: "checkbox" },
  { questionId: "sec1.unit", pdfField: "form1[0].#subform[43].Sec1_Unit[2]" },
  { questionId: "part14.emailaddress", pdfField: "form1[0].#subform[43].Part14_EmailAddress[0]" },
  { questionId: "employingorgname", pdfField: "form1[0].#subform[43].EmployingOrgName[0]" },
  { questionId: "nameofreligiousdenomination", pdfField: "form1[0].#subform[43].NameOfReligiousDenomination[0]" },
  { questionId: "part14.dateofsignature", pdfField: "form1[0].#subform[43].Part14_DateofSignature[1]" },
  { questionId: "preparersignature", pdfField: "form1[0].#subform[43].PreparerSignature[0]" },
  { questionId: "part14.city", pdfField: "form1[0].#subform[43].Part14_City[1]" },
  { questionId: "line2.state", pdfField: "form1[0].#subform[43].Line2_State[1]" },
  { questionId: "part14.zipcode", pdfField: "form1[0].#subform[43].Part14_ZipCode[1]" },
  { questionId: "part14.streetname", pdfField: "form1[0].#subform[43].Part14_StreetName[1]" },
  { questionId: "attest.aptsteflrnumber", pdfField: "form1[0].#subform[43].Attest_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "attest.unit", pdfField: "form1[0].#subform[43].Attest_Unit[0]", type: "checkbox" },
  { questionId: "attest.unit", pdfField: "form1[0].#subform[43].Attest_Unit[1]", type: "checkbox" },
  { questionId: "attest.unit", pdfField: "form1[0].#subform[43].Attest_Unit[2]" },
  { questionId: "part14.firmname", pdfField: "form1[0].#subform[43].Part14_FirmName[1]" },
  { questionId: "part14.emailaddress", pdfField: "form1[0].#subform[43].Part14_EmailAddress[1]" },
  { questionId: "part14.preparerprintedname", pdfField: "form1[0].#subform[43].Part14_PreparerPrintedName[1]" },
  { questionId: "line5.jobtitle", pdfField: "form1[0].#subform[43].Line5_JobTitle[1]" },
  { questionId: "preparer.daytimephonenumber1", pdfField: "form1[0].#subform[43].Preparer_DaytimePhoneNumber1[0]" },
  { questionId: "preparers.faxphonenumber1", pdfField: "form1[0].#subform[43].Preparers_FaxPhoneNumber1[0]" },
  { questionId: "preparers.faxphonenumber1", pdfField: "form1[0].#subform[43].Preparers_FaxPhoneNumber1[1]" },
  { questionId: "preparer.daytimephonenumber1", pdfField: "form1[0].#subform[43].Preparer_DaytimePhoneNumber1[1]" },
  { questionId: "line3.middlename1", pdfField: "form1[0].#subform[44].Line3_MiddleName1[1]" },
  { questionId: "line3.givenname1", pdfField: "form1[0].#subform[44].Line3_GivenName1[1]" },
  { questionId: "line3.familyname1", pdfField: "form1[0].#subform[44].Line3_FamilyName1[1]", type: "checkbox" },
  { questionId: "line1.gender", pdfField: "form1[0].#subform[44].Line1_Gender[0]", type: "checkbox" },
  { questionId: "line1.gender", pdfField: "form1[0].#subform[44].Line1_Gender[1]" },
  { questionId: "line5.ssn", pdfField: "form1[0].#subform[44].Line5_SSN[1]" },
  { questionId: "line6.dateofbirth", pdfField: "form1[0].#subform[44].Line6_DateOfBirth[1]" },
  { questionId: "line1.aliennumber", pdfField: "form1[0].#subform[44].Line1_AlienNumber[1]" },
  { questionId: "line3.middlename1", pdfField: "form1[0].#subform[44].Line3_MiddleName1[2]" },
  { questionId: "line3.givenname1", pdfField: "form1[0].#subform[44].Line3_GivenName1[2]" },
  { questionId: "line3.familyname1", pdfField: "form1[0].#subform[44].Line3_FamilyName1[2]" },
  { questionId: "part7linea.empcity", pdfField: "form1[0].#subform[44].Part7LineA_EmpCity[0]" },
  { questionId: "part7linea.emp1state", pdfField: "form1[0].#subform[44].Part7LineA_Emp1State[0]" },
  { questionId: "part7linea.emp1zipcode", pdfField: "form1[0].#subform[44].Part7LineA_Emp1ZipCode[0]" },
  { questionId: "part7linea.emp1streetname", pdfField: "form1[0].#subform[44].Part7LineA_Emp1StreetName[0]" },
  { questionId: "att1.aptsteflrnumber", pdfField: "form1[0].#subform[44].Att1_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "att1.unit", pdfField: "form1[0].#subform[44].Att1_Unit[0]", type: "checkbox" },
  { questionId: "att1.unit", pdfField: "form1[0].#subform[44].Att1_Unit[1]", type: "checkbox" },
  { questionId: "att1.unit", pdfField: "form1[0].#subform[44].Att1_Unit[2]" },
  { questionId: "line.citytown", pdfField: "form1[0].#subform[44].Line_CityTown[4]" },
  { questionId: "a1.zipcode", pdfField: "form1[0].#subform[44].A1_ZipCode[0]" },
  { questionId: "a1.state", pdfField: "form1[0].#subform[44].A1_State[0]" },
  { questionId: "line7b.streetnumbername", pdfField: "form1[0].#subform[44].Line7b_StreetNumberName[4]", type: "checkbox" },
  { questionId: "for.unit", pdfField: "form1[0].#subform[44].For_Unit[0]", type: "checkbox" },
  { questionId: "for.unit", pdfField: "form1[0].#subform[44].For_Unit[1]", type: "checkbox" },
  { questionId: "for.unit", pdfField: "form1[0].#subform[44].For_Unit[2]" },
  { questionId: "for.aptsteflrnumber", pdfField: "form1[0].#subform[44].For_AptSteFlrNumber[0]" },
  { questionId: "a1.province", pdfField: "form1[0].#subform[44].A1_Province[0]" },
  { questionId: "a1.postalcode", pdfField: "form1[0].#subform[44].A1_PostalCode[0]" },
  { questionId: "a1.country", pdfField: "form1[0].#subform[44].A1_Country[0]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[44].Line_Country[2]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[44].Line_Country[3]" },
  { questionId: "line14e.expdate", pdfField: "form1[0].#subform[44].Line14e_ExpDate[0]" },
  { questionId: "line14a.arrivaldeparture", pdfField: "form1[0].#subform[44].Line14a_ArrivalDeparture[0]" },
  { questionId: "line15.currentnon", pdfField: "form1[0].#subform[44].Line15_CurrentNon[0]" },
  { questionId: "line16.datestatusexpires", pdfField: "form1[0].#subform[44].Line16_DateStatusExpires[0]" },
  { questionId: "line14e.expdate", pdfField: "form1[0].#subform[44].Line14e_ExpDate[1]" },
  { questionId: "line11a.dateofarrival", pdfField: "form1[0].#subform[44].Line11a_DateofArrival[0]" },
  { questionId: "line14b.passport", pdfField: "form1[0].#subform[44].Line14b_Passport[0]" },
  { questionId: "line14b.passport", pdfField: "form1[0].#subform[44].Line14b_Passport[1]" },
  { questionId: "line14b.passport", pdfField: "form1[0].#subform[44].Line14b_Passport[2]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[44].Line_Country[4]" },
  { questionId: "line3.middlename1", pdfField: "form1[0].#subform[45].Line3_MiddleName1[3]" },
  { questionId: "line3.givenname1", pdfField: "form1[0].#subform[45].Line3_GivenName1[3]" },
  { questionId: "line3.familyname1", pdfField: "form1[0].#subform[45].Line3_FamilyName1[3]", type: "checkbox" },
  { questionId: "line2.gender", pdfField: "form1[0].#subform[45].Line2_Gender[0]", type: "checkbox" },
  { questionId: "line2.gender", pdfField: "form1[0].#subform[45].Line2_Gender[1]" },
  { questionId: "line5.ssn", pdfField: "form1[0].#subform[45].Line5_SSN[2]" },
  { questionId: "line6.dateofbirth", pdfField: "form1[0].#subform[45].Line6_DateOfBirth[2]" },
  { questionId: "line1.aliennumber", pdfField: "form1[0].#subform[45].Line1_AlienNumber[2]" },
  { questionId: "line3.middlename1", pdfField: "form1[0].#subform[45].Line3_MiddleName1[4]" },
  { questionId: "line3.givenname1", pdfField: "form1[0].#subform[45].Line3_GivenName1[4]" },
  { questionId: "line3.familyname1", pdfField: "form1[0].#subform[45].Line3_FamilyName1[4]" },
  { questionId: "part7linea.empcity", pdfField: "form1[0].#subform[45].Part7LineA_EmpCity[1]" },
  { questionId: "part7linea.emp1state", pdfField: "form1[0].#subform[45].Part7LineA_Emp1State[1]" },
  { questionId: "part7linea.emp1zipcode", pdfField: "form1[0].#subform[45].Part7LineA_Emp1ZipCode[1]" },
  { questionId: "part7linea.emp1streetname", pdfField: "form1[0].#subform[45].Part7LineA_Emp1StreetName[1]" },
  { questionId: "att2.aptsteflrnumber", pdfField: "form1[0].#subform[45].Att2_AptSteFlrNumber[0]", type: "checkbox" },
  { questionId: "att2.unit", pdfField: "form1[0].#subform[45].Att2_Unit[0]", type: "checkbox" },
  { questionId: "att2.unit", pdfField: "form1[0].#subform[45].Att2_Unit[1]", type: "checkbox" },
  { questionId: "att2.unit", pdfField: "form1[0].#subform[45].Att2_Unit[2]" },
  { questionId: "line.citytown", pdfField: "form1[0].#subform[45].Line_CityTown[5]" },
  { questionId: "fr.zipcode", pdfField: "form1[0].#subform[45].FR_ZipCode[0]" },
  { questionId: "fr.state", pdfField: "form1[0].#subform[45].FR_State[0]" },
  { questionId: "line7b.streetnumbername", pdfField: "form1[0].#subform[45].Line7b_StreetNumberName[5]", type: "checkbox" },
  { questionId: "for2.unit", pdfField: "form1[0].#subform[45].For2_Unit[0]", type: "checkbox" },
  { questionId: "for2.unit", pdfField: "form1[0].#subform[45].For2_Unit[1]", type: "checkbox" },
  { questionId: "for2.unit", pdfField: "form1[0].#subform[45].For2_Unit[2]" },
  { questionId: "for2.aptsteflrnumber", pdfField: "form1[0].#subform[45].For2_AptSteFlrNumber[0]" },
  { questionId: "fr.province", pdfField: "form1[0].#subform[45].FR_Province[0]" },
  { questionId: "fr.postalcode", pdfField: "form1[0].#subform[45].FR_PostalCode[0]" },
  { questionId: "fr.country", pdfField: "form1[0].#subform[45].FR_Country[0]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[45].Line_Country[5]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[45].Line_Country[6]" },
  { questionId: "line14e.expdate", pdfField: "form1[0].#subform[45].Line14e_ExpDate[2]" },
  { questionId: "line14a.arrivaldeparture", pdfField: "form1[0].#subform[45].Line14a_ArrivalDeparture[1]" },
  { questionId: "line15.currentnon", pdfField: "form1[0].#subform[45].Line15_CurrentNon[1]" },
  { questionId: "line16.datestatusexpires", pdfField: "form1[0].#subform[45].Line16_DateStatusExpires[1]" },
  { questionId: "line14e.expdate", pdfField: "form1[0].#subform[45].Line14e_ExpDate[3]" },
  { questionId: "line11a.dateofarrival", pdfField: "form1[0].#subform[45].Line11a_DateofArrival[1]" },
  { questionId: "line14b.sevis", pdfField: "form1[0].#subform[45].Line14b_SEVIS[0]" },
  { questionId: "line14b.ead", pdfField: "form1[0].#subform[45].Line14b_EAD[0]" },
  { questionId: "line14b.passport", pdfField: "form1[0].#subform[45].Line14b_Passport[3]" },
  { questionId: "line.country", pdfField: "form1[0].#subform[45].Line_Country[7]" },
];
