/**
 * Form Registry Definition for I131
 * Generated on: 2025-12-22T19:11:11.497Z
 * 
 * Copy this to src/lib/constants/forms-registry.ts
 */

const I131_DEFINITION: FormDefinition = {
  id: "i131",
  code: "I131",
  name: "TODO: Add Form Name",
  description: "TODO: Add description",
  category: "other",
  estimatedTime: "30-45 minutes",
  filingFee: 0,
  price: 60,
  sections: [
    {
      id: "section1",
      title: "Part 1: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "form1[0].p1[0].g28.attached",
          type: "checkbox",
          label: "form1[0]. P1[0]. G28  Attached",
          required: false,
        },
        {
          id: "form1[0].p1[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P1[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p1[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P1[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p1[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P1[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p1[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P1[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p1[0].cb.apptype",
          type: "text",
          label: "form1[0]. P1[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p1[0].p1.line4",
          type: "text",
          label: "form1[0]. P1[0]. P1  Line4",
          required: false,
        },
        {
          id: "form1[0].p1[0].p1.line5a",
          type: "checkbox",
          label: "form1[0]. P1[0]. P1  Line5 A",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "text",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5c",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 C",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5e",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 E",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5f",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 F",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5g",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 G",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5h",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 H",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5i",
          type: "checkbox",
          label: "form1[0]. P2[0]. P1  Line5 I",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "text",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5m",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 M",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5j",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 J",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5k",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 K",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5l",
          type: "text",
          label: "form1[0]. P2[0]. P1  Line5 L",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line6a",
          type: "checkbox",
          label: "form1[0]. P2[0]. P1  Line6 A",
          required: false,
        },
        {
          id: "form1[0].p2[0].cb.apptype",
          type: "text",
          label: "form1[0]. P2[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p2[0].p1.line5b",
          type: "checkbox",
          label: "form1[0]. P2[0]. P1  Line5 B",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "text",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6d",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 D",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "text",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6e",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 E",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line8a.1",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line8 A 1",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line8a.2",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line8 A 2",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "text",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line8c",
          type: "text",
          label: "form1[0]. P3[0]. P1  Line8 C",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line8b",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line8 B",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "text",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6c2",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 C2",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "text",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6c1",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 C1",
          required: false,
        },
        {
          id: "form1[0].p3[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P3[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6b.3",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 B 3",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6b.2",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 B 2",
          required: false,
        },
        {
          id: "form1[0].p3[0].p1.line6b.1",
          type: "checkbox",
          label: "form1[0]. P3[0]. P1  Line6 B 1",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "text",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line12.dateofadmission",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line12  Date Of Admission",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line10e.1",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line10 E 1",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line10e.3",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line10 E 3",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line10e.2",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line10 E 2",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line10h.2",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line10 H 2",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line10h.1",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line10 H 1",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "text",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line10i",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line10 I",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "checkbox",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].cb.apptype",
          type: "text",
          label: "form1[0]. P4[0]. C B  App Type",
          required: false,
        },
        {
          id: "form1[0].p4[0].part2.line1.middlename",
          type: "text",
          label: "form1[0]. P4[0]. Part2  Line1  Middle Name",
          required: false,
        },
        {
          id: "form1[0].p4[0].part2.line1.givenname",
          type: "text",
          label: "form1[0]. P4[0]. Part2  Line1  Given Name",
          required: false,
        },
        {
          id: "form1[0].p4[0].part2.line1.familyname",
          type: "checkbox",
          label: "form1[0]. P4[0]. Part2  Line1  Family Name",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line13.yesno",
          type: "checkbox",
          label: "form1[0]. P4[0]. P1  Line13  Yes No",
          required: false,
        },
        {
          id: "form1[0].p4[0].p1.line13.yesno",
          type: "text",
          label: "form1[0]. P4[0]. P1  Line13  Yes No",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.citytown",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  City Town",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.zipcode",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  Zip Code",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.state",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  State",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.incareofname",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  In Careof Name",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.streetnumbername",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line3  Street Number Name",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.unit",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line3  Unit",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.unit",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line3  Unit",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.unit",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  Unit",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.aptsteflrnumber",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  Apt Ste Flr Number",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.postalcode",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  Postal Code",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.province",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  Province",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line3.country",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line3  Country",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.citytown",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  City Town",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.zipcode",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  Zip Code",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.state",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  State",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.incareofname",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  In Careof Name",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.streetnumbername",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line4  Street Number Name",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.unit",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line4  Unit",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.unit",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line4  Unit",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.unit",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  Unit",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.aptsteflrnumber",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  Apt Ste Flr Number",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.postalcode",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  Postal Code",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.province",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  Province",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line4.country",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line4  Country",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line11.uscisonlineacctnumber",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line11  U S C I S Online Acct Number",
          required: false,
        },
        {
          id: "form1[0].p5[0].#area[0].part2.line5.aliennumber",
          type: "text",
          label: "form1[0]. P5[0].#area[0]. Part2  Line5  Alien Number",
          required: false,
        },
        {
          id: "form1[0].p5[0].#area[1].part2.line10.ssn",
          type: "checkbox",
          label: "form1[0]. P5[0].#area[1]. Part2  Line10  S S N",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line8.gender",
          type: "checkbox",
          label: "form1[0]. P5[0]. Part2  Line8  Gender",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line8.gender",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line8  Gender",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line9.dateofbirth",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line9  Date Of Birth",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line6.countryofbirth",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line6  Country Of Birth",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line7.countryofcitizenshipornationality",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line7  Country Of Citizenshipor Nationality",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line12.classofadmission",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line12  Classof Admission",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line13.i94recordno",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line13  I94 Record No",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.middlename2",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Middle Name2",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.middlename1",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Middle Name1",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.givenname1",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Given Name1",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.familyname1",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Family Name1",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.givenname2",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Given Name2",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.familyname2",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Family Name2",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.middlename3",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Middle Name3",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.givenname3",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Given Name3",
          required: false,
        },
        {
          id: "form1[0].p5[0].part2.line2.familyname3",
          type: "text",
          label: "form1[0]. P5[0]. Part2  Line2  Family Name3",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line16.familyname",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line16  Family Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line16.givenname",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line16  Given Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line16.middlename",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line16  Middle Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.familyname1",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Family Name1",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.givenname1",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Given Name1",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.middlename1",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Middle Name1",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.familyname2",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Family Name2",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.givenname2",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Given Name2",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.middlename2",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Middle Name2",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.familyname3",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Family Name3",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.givenname3",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Given Name3",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line17.middlename3",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line17  Middle Name3",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line18.dateofbirth",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line18  Date Of Birth",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line19.countryofbirth",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line19  Country Of Birth",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line20.countryofcitizenship",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line20  Country Of Citizenship",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line21.daytimetelephonenumber",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line21  Daytime Telephone Number",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line22.email",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line22  Email",
          required: false,
        },
        {
          id: "form1[0].p6[0].anumber[0].p2.line23.aliennumber",
          type: "text",
          label: "form1[0]. P6[0]. A Number[0]. P2  Line23  Alien Number",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.citytown",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  City Town",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.zipcode",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  Zip Code",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.state",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  State",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.incareofname",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  In Careof Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.streetnumbername",
          type: "checkbox",
          label: "form1[0]. P6[0]. P2  Line24  Street Number Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.unit",
          type: "checkbox",
          label: "form1[0]. P6[0]. P2  Line24  Unit",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.unit",
          type: "checkbox",
          label: "form1[0]. P6[0]. P2  Line24  Unit",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.unit",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  Unit",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.aptsteflrnumber",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  Apt Ste Flr Number",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.postalcode",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  Postal Code",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.province",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  Province",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line24.country",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line24  Country",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.citytown",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  City Town",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.zipcode",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  Zip Code",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.state",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  State",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.incareofname",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  In Careof Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.streetnumbername",
          type: "checkbox",
          label: "form1[0]. P6[0]. P2  Line25  Street Number Name",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.unit",
          type: "checkbox",
          label: "form1[0]. P6[0]. P2  Line25  Unit",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.unit",
          type: "checkbox",
          label: "form1[0]. P6[0]. P2  Line25  Unit",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.unit",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  Unit",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.aptsteflrnumber",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  Apt Ste Flr Number",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.postalcode",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  Postal Code",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.province",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  Province",
          required: false,
        },
        {
          id: "form1[0].p6[0].p2.line25.country",
          type: "text",
          label: "form1[0]. P6[0]. P2  Line25  Country",
          required: false,
        },
        {
          id: "form1[0].p6[0].par2.line15.emedicalparoleeid",
          type: "text",
          label: "form1[0]. P6[0]. Par2  Line15 e Medical Parolee I D",
          required: false,
        },
        {
          id: "form1[0].p6[0].part2.line14.i94expdate",
          type: "text",
          label: "form1[0]. P6[0]. Part2  Line14  I94 Exp Date",
          required: false,
        },
        {
          id: "form1[0].p7[0].p2.line26.classofadmission",
          type: "text",
          label: "form1[0]. P7[0]. P2  Line26  Classof Admission",
          required: false,
        },
        {
          id: "form1[0].p7[0].p2.line27.i94recordno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P2  Line27  I94 Record No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line2.race.black",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line2  Race  Black",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line2.race.hawaiian",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line2  Race  Hawaiian",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line2.race.american",
          type: "text",
          label: "form1[0]. P7[0]. P3  Line2  Race  American",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line3.heightfeet",
          type: "text",
          label: "form1[0]. P7[0]. P3  Line3  Height Feet",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line3.heightinches",
          type: "text",
          label: "form1[0]. P7[0]. P3  Line3  Height Inches",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line4.pound1",
          type: "text",
          label: "form1[0]. P7[0]. P3  Line4  Pound1",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line4.pound2",
          type: "text",
          label: "form1[0]. P7[0]. P3  Line4  Pound2",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line4.pound3",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line4  Pound3",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line6.haircolor",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line6  Hair Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line2.race.asian",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line2  Race  Asian",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line2.race.white",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line2  Race  White",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line1.ethnicity",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line1  Ethnicity",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line1.ethnicity",
          type: "checkbox",
          label: "form1[0]. P7[0]. P3  Line1  Ethnicity",
          required: false,
        },
        {
          id: "form1[0].p7[0].p3.line5.eyecolor",
          type: "text",
          label: "form1[0]. P7[0]. P3  Line5  Eye Color",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line2c.disposition",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line2c  Disposition",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line2a.yesno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line2a  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line2a.yesno",
          type: "text",
          label: "form1[0]. P7[0]. P4  Line2a  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line2b.dateissued",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line2b  Date Issued",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line1.yesno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line1  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line1.yesno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line1  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line3a.yesno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line3a  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line3a.yesno",
          type: "text",
          label: "form1[0]. P7[0]. P4  Line3a  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line3b.dateissued",
          type: "text",
          label: "form1[0]. P7[0]. P4  Line3b  Date Issued",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line3c.disposition",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line3c  Disposition",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line4.yesno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line4  Yes No",
          required: false,
        },
        {
          id: "form1[0].p7[0].p4.line4.yesno",
          type: "checkbox",
          label: "form1[0]. P7[0]. P4  Line4  Yes No",
          required: false,
        },
        {
          id: "p4.line5",
          type: "checkbox",
          label: "P4  Line5",
          required: false,
        },
        {
          id: "p4.line5",
          type: "checkbox",
          label: "P4  Line5",
          required: false,
        },
        {
          id: "p4.line5",
          type: "checkbox",
          label: "P4  Line5",
          required: false,
        },
        {
          id: "p4.line5",
          type: "checkbox",
          label: "P4  Line5",
          required: false,
        },
        {
          id: "p4.line7a",
          type: "checkbox",
          label: "P4  Line7a",
          required: false,
        },
        {
          id: "p4.line7a",
          type: "text",
          label: "P4  Line7a",
          required: false,
        },
        {
          id: "line4c.no",
          type: "checkbox",
          label: "Line4c  No",
          required: false,
        },
        {
          id: "line4c.yes",
          type: "checkbox",
          label: "Line4c  Yes",
          required: false,
        },
        {
          id: "p11.language",
          type: "text",
          label: "P11  Language",
          required: false,
        },
        {
          id: "global.anumber[0].part2.line5.aliennumber",
          type: "text",
          label: "Global  A Number[0]. Part2  Line5  Alien Number",
          required: false,
        },
      ],
    },
    {
      id: "part4",
      title: "Part 4: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part4.6a.name",
          type: "checkbox",
          label: "6a. Name",
          required: false,
        },
        {
          id: "part4.6a.aNumber",
          type: "checkbox",
          label: "6a. A Number",
          required: false,
        },
        {
          id: "part4.6a.countryofBirthCitizenship",
          type: "checkbox",
          label: "6a. Countryof Birth Citizenship",
          required: false,
        },
        {
          id: "part4.6a.terms",
          type: "checkbox",
          label: "6a. Terms",
          required: false,
        },
        {
          id: "part4.6a.dOB",
          type: "checkbox",
          label: "6a. D O B",
          required: false,
        },
        {
          id: "part4.6a.gender",
          type: "checkbox",
          label: "6a. Gender",
          required: false,
        },
        {
          id: "part4.6a.validity",
          type: "checkbox",
          label: "6a. Validity",
          required: false,
        },
        {
          id: "part4.6a.photo",
          type: "text",
          label: "6a. Photo",
          required: false,
        },
        {
          id: "part4.6a.explanation",
          type: "text",
          label: "6a. Explanation",
          required: false,
        },
        {
          id: "part4.6b.receiptNumber",
          type: "checkbox",
          label: "6b. Receipt Number",
          required: false,
        },
        {
          id: "part4.7b.cityOrTown",
          type: "text",
          label: "7b. City Or Town",
          required: false,
        },
        {
          id: "part4.7b.country",
          type: "checkbox",
          label: "7b. Country",
          required: false,
        },
        {
          id: "part4.8.cB",
          type: "checkbox",
          label: "8. C B",
          required: false,
        },
        {
          id: "part4.8.cB",
          type: "text",
          label: "8. C B",
          required: false,
        },
        {
          id: "part4.9a.inCareofName",
          type: "text",
          label: "9a. In Careof Name",
          required: false,
        },
        {
          id: "part4.9a.cityTown",
          type: "text",
          label: "9a. City Town",
          required: false,
        },
        {
          id: "part4.9a.zipCode",
          type: "text",
          label: "9a. Zip Code",
          required: false,
        },
        {
          id: "part4.9a.state",
          type: "text",
          label: "9a. State",
          required: false,
        },
        {
          id: "part4.9a.streetNumberName",
          type: "checkbox",
          label: "9a. Street Number Name",
          required: false,
        },
        {
          id: "part4.9a.unit",
          type: "checkbox",
          label: "9a. Unit",
          required: false,
        },
        {
          id: "part4.9a.unit",
          type: "checkbox",
          label: "9a. Unit",
          required: false,
        },
        {
          id: "part4.9a.unit",
          type: "text",
          label: "9a. Unit",
          required: false,
        },
        {
          id: "part4.9a.aptSteFlrNumber",
          type: "text",
          label: "9a. Apt Ste Flr Number",
          required: false,
        },
        {
          id: "part4.9a.postalCode",
          type: "text",
          label: "9a. Postal Code",
          required: false,
        },
        {
          id: "part4.9a.province",
          type: "text",
          label: "9a. Province",
          required: false,
        },
        {
          id: "part4.9a.country",
          type: "text",
          label: "9a. Country",
          required: false,
        },
        {
          id: "part4.9c.email",
          type: "text",
          label: "9c. Email",
          required: false,
        },
        {
          id: "part4.9b.email",
          type: "checkbox",
          label: "9b. Email",
          required: false,
        },
      ],
    },
    {
      id: "part5",
      title: "Part 5: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part5.1.lessthan6",
          type: "checkbox",
          label: "1. Lessthan6",
          required: false,
        },
        {
          id: "part5.1.6months",
          type: "checkbox",
          label: "1. 6months",
          required: false,
        },
        {
          id: "part5.1.1to2",
          type: "checkbox",
          label: "1. 1to2",
          required: false,
        },
        {
          id: "part5.1.2to3",
          type: "checkbox",
          label: "1. 2to3",
          required: false,
        },
        {
          id: "part5.1.3to4",
          type: "checkbox",
          label: "1. 3to4",
          required: false,
        },
        {
          id: "part5.1.morethan",
          type: "checkbox",
          label: "1. morethan",
          required: false,
        },
      ],
    },
    {
      id: "part6",
      title: "Part 6: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part6.2.yesNo",
          type: "checkbox",
          label: "2. Yes No",
          required: false,
        },
        {
          id: "part6.2.yesNo",
          type: "text",
          label: "2. Yes No",
          required: false,
        },
        {
          id: "part6.1.countryRefugee",
          type: "checkbox",
          label: "1. Country Refugee",
          required: false,
        },
        {
          id: "part6.3b.yesNo",
          type: "checkbox",
          label: "3b. Yes No",
          required: false,
        },
        {
          id: "part6.3c.yesNo",
          type: "checkbox",
          label: "3c. Yes No",
          required: false,
        },
        {
          id: "part6.3c.yesNo",
          type: "checkbox",
          label: "3c. Yes No",
          required: false,
        },
        {
          id: "part6.3b.yesNo",
          type: "checkbox",
          label: "3b. Yes No",
          required: false,
        },
        {
          id: "part6.3a.yesNo",
          type: "checkbox",
          label: "3a. Yes No",
          required: false,
        },
        {
          id: "part6.3a.yesNo",
          type: "checkbox",
          label: "3a. Yes No",
          required: false,
        },
        {
          id: "part6.4a.yesNo",
          type: "checkbox",
          label: "4a. Yes No",
          required: false,
        },
        {
          id: "part6.4b.yesNo",
          type: "checkbox",
          label: "4b. Yes No",
          required: false,
        },
        {
          id: "part6.5.yesNo",
          type: "checkbox",
          label: "5. Yes No",
          required: false,
        },
        {
          id: "part6.5.yesNo",
          type: "checkbox",
          label: "5. Yes No",
          required: false,
        },
        {
          id: "part6.4b.yesNo",
          type: "checkbox",
          label: "4b. Yes No",
          required: false,
        },
        {
          id: "part6.4a.yesNo",
          type: "checkbox",
          label: "4a. Yes No",
          required: false,
        },
        {
          id: "part6.6a.yesNo",
          type: "checkbox",
          label: "6a. Yes No",
          required: false,
        },
        {
          id: "part6.6a.yesNo",
          type: "text",
          label: "6a. Yes No",
          required: false,
        },
        {
          id: "part6.6b.cityOrTown",
          type: "text",
          label: "6b. City Or Town",
          required: false,
        },
        {
          id: "part6.6c.country",
          type: "checkbox",
          label: "6c. Country",
          required: false,
        },
      ],
    },
    {
      id: "part7",
      title: "Part 7: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part7.4.cB",
          type: "checkbox",
          label: "4. C B",
          required: false,
        },
        {
          id: "part7.4.cB",
          type: "text",
          label: "4. C B",
          required: false,
        },
        {
          id: "part7.5.expectedLengthTrip",
          type: "text",
          label: "5. Expected Length Trip",
          required: false,
        },
        {
          id: "part7.2.purpose",
          type: "text",
          label: "2. Purpose",
          required: false,
        },
        {
          id: "part7.1.dateOfDeparture",
          type: "text",
          label: "1. Date Of Departure",
          required: false,
        },
        {
          id: "part7.3.listCountries",
          type: "checkbox",
          label: "3. List Countries",
          required: false,
        },
      ],
    },
    {
      id: "part9",
      title: "Part 9: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part9.1.eAD",
          type: "text",
          label: "1. E A D",
          required: false,
        },
      ],
    },
    {
      id: "part8",
      title: "Part 8: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part8.3a.dateOfIntendedArrival",
          type: "text",
          label: "3a. Date Of Intended Arrival",
          required: false,
        },
        {
          id: "part8.3b.cityOrTown",
          type: "text",
          label: "3b. City Or Town",
          required: false,
        },
        {
          id: "part8.3b.country",
          type: "text",
          label: "3b. Country",
          required: false,
        },
        {
          id: "part8.2.expectedLengthTripinUS",
          type: "text",
          label: "2. Expected Length Tripin U S",
          required: false,
        },
        {
          id: "part8.1.explain",
          type: "text",
          label: "1. Explain",
          required: false,
        },
      ],
    },
    {
      id: "part10",
      title: "Part 10: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part10.line4.dateofsignature",
          type: "text",
          label: "Part10  Line4  Dateof Signature",
          required: false,
        },
        {
          id: "part10.line4.applicantsignature",
          type: "text",
          label: "Part10  Line4  Applicant Signature",
          required: false,
        },
        {
          id: "part10.line1.dayphone",
          type: "text",
          label: "Part10  Line1  Day Phone",
          required: false,
        },
        {
          id: "part10.line2.mobilephone",
          type: "text",
          label: "Part10  Line2  Mobile Phone",
          required: false,
        },
        {
          id: "part10.line3.email",
          type: "text",
          label: "Part10  Line3  Email",
          required: false,
        },
      ],
    },
    {
      id: "part11",
      title: "Part 11: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part11.line3.dayphone",
          type: "text",
          label: "Part11  Line3  Day Phone",
          required: false,
        },
        {
          id: "part11.line4.mobilephone",
          type: "text",
          label: "Part11  Line4  Mobile Phone",
          required: false,
        },
        {
          id: "part11.line5.email",
          type: "text",
          label: "Part11  Line5  Email",
          required: false,
        },
        {
          id: "part11.line6.interpretersig",
          type: "text",
          label: "Part11  Line6  Interpreter Sig",
          required: false,
        },
        {
          id: "part11.line6.dateofsignature",
          type: "text",
          label: "Part11  Line6  Dateof Signature",
          required: false,
        },
        {
          id: "part11.line1.interpreterfamilyname",
          type: "text",
          label: "Part11  Line1  Interpreter Family Name",
          required: false,
        },
        {
          id: "part11.line1.interpretergivenname",
          type: "text",
          label: "Part11  Line1  Interpreter Given Name",
          required: false,
        },
        {
          id: "part11.line2.nameofbusinessororgname",
          type: "text",
          label: "Part11  Line2  Nameof Businessor Org Name",
          required: false,
        },
      ],
    },
    {
      id: "part12",
      title: "Part 12: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part12.line6.preparersig",
          type: "text",
          label: "Part12  Line6  Preparer Sig",
          required: false,
        },
        {
          id: "part12.line6.dateofsignature",
          type: "text",
          label: "Part12  Line6  Dateof Signature",
          required: false,
        },
        {
          id: "part12.line1.familyname",
          type: "text",
          label: "Part12  Line1  Family Name",
          required: false,
        },
        {
          id: "part12.line1.givenname",
          type: "text",
          label: "Part12  Line1  Given Name",
          required: false,
        },
        {
          id: "part12.line2.nameofbusinessororgname",
          type: "text",
          label: "Part12  Line2  Nameof Businessor Org Name",
          required: false,
        },
        {
          id: "part12.line5.email",
          type: "text",
          label: "Part12  Line5  Email",
          required: false,
        },
        {
          id: "part12.line3.dayphone",
          type: "text",
          label: "Part12  Line3  Day Phone",
          required: false,
        },
        {
          id: "part12.line4.mobilephone",
          type: "text",
          label: "Part12  Line4  Mobile Phone",
          required: false,
        },
      ],
    },
    {
      id: "part2",
      title: "Part 2: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part2.line1.familyname",
          type: "text",
          label: "Part2  Line1  Family Name",
          required: false,
        },
        {
          id: "part2.line1.givenname",
          type: "text",
          label: "Part2  Line1  Given Name",
          required: false,
        },
        {
          id: "part2.line1.middlename",
          type: "text",
          label: "Part2  Line1  Middle Name",
          required: false,
        },
      ],
    },
    {
      id: "part13",
      title: "Part 13: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part13.line3.pagenumber",
          type: "text",
          label: "Part13  Line3  Page Number",
          required: false,
        },
        {
          id: "part13.line3.partnumber",
          type: "text",
          label: "Part13  Line3  Part Number",
          required: false,
        },
        {
          id: "part13.line3.itemnumber",
          type: "text",
          label: "Part13  Line3  Item Number",
          required: false,
        },
        {
          id: "part13.line3.additionalinfo",
          type: "text",
          label: "Part13  Line3  Additional Info",
          required: false,
        },
        {
          id: "part13.line4.pagenumber",
          type: "text",
          label: "Part13  Line4  Page Number",
          required: false,
        },
        {
          id: "part13.line4.partnumber",
          type: "text",
          label: "Part13  Line4  Part Number",
          required: false,
        },
        {
          id: "part13.line4.itemnumber",
          type: "text",
          label: "Part13  Line4  Item Number",
          required: false,
        },
        {
          id: "part13.line4.additionalinfo",
          type: "text",
          label: "Part13  Line4  Additional Info",
          required: false,
        },
        {
          id: "part13.line5.pagenumber",
          type: "text",
          label: "Part13  Line5  Page Number",
          required: false,
        },
        {
          id: "part13.line5.partnumber",
          type: "text",
          label: "Part13  Line5  Part Number",
          required: false,
        },
        {
          id: "part13.line5.itemnumber",
          type: "text",
          label: "Part13  Line5  Item Number",
          required: false,
        },
        {
          id: "part13.line5.additionalinfo",
          type: "text",
          label: "Part13  Line5  Additional Info",
          required: false,
        },
        {
          id: "part13.line6.pagenumber",
          type: "text",
          label: "Part13  Line6  Page Number",
          required: false,
        },
        {
          id: "part13.line6.partnumber",
          type: "text",
          label: "Part13  Line6  Part Number",
          required: false,
        },
        {
          id: "part13.line6.itemnumber",
          type: "text",
          label: "Part13  Line6  Item Number",
          required: false,
        },
        {
          id: "part13.line6.additionalinfo",
          type: "text",
          label: "Part13  Line6  Additional Info",
          required: false,
        },
        {
          id: "part13.line7.pagenumber",
          type: "text",
          label: "Part13  Line7  Page Number",
          required: false,
        },
        {
          id: "part13.line7.partnumber",
          type: "text",
          label: "Part13  Line7  Part Number",
          required: false,
        },
        {
          id: "part13.line7.itemnumber",
          type: "text",
          label: "Part13  Line7  Item Number",
          required: false,
        },
        {
          id: "part13.line7.additionalinfo",
          type: "text",
          label: "Part13  Line7  Additional Info",
          required: false,
        },
      ],
    },
  ],
  requiredDocuments: [
    "TODO: List required documents",
  ],
  instructions: [
    "TODO: Add instructions",
  ],
};

// Add to FORMS_REGISTRY array:
// I131_DEFINITION,
