/**
 * Form Registry Definition for I90UNLOCKED
 * Generated on: 2025-12-16T14:12:35.057Z
 * 
 * Copy this to src/lib/constants/forms-registry.ts
 */

const I90UNLOCKED_DEFINITION: FormDefinition = {
  id: "i90unlocked",
  code: "I90UNLOCKED",
  name: "TODO: Add Form Name",
  description: "TODO: Add description",
  category: "other",
  estimatedTime: "30-45 minutes",
  filingFee: 0,
  price: 60,
  sections: [
    {
      id: "part1",
      title: "Part 1: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part1.3a.familyName",
          type: "text",
          label: "3a. Family Name",
          required: false,
        },
        {
          id: "part1.3b.givenName",
          type: "text",
          label: "3b. Given Name",
          required: false,
        },
        {
          id: "part1.3c.middleName",
          type: "checkbox",
          label: "3c. Middle Name",
          required: false,
        },
        {
          id: "part1.checkbox4",
          type: "checkbox",
          label: "P1 checkbox4",
          required: false,
        },
        {
          id: "part1.checkbox4",
          type: "checkbox",
          label: "P1 checkbox4",
          required: false,
        },
        {
          id: "part1.checkbox4",
          type: "text",
          label: "P1 checkbox4",
          required: false,
        },
        {
          id: "part1.6a.inCareofName",
          type: "text",
          label: "6a. In Careof Name",
          required: false,
        },
        {
          id: "part1.6b.streetNumberName",
          type: "text",
          label: "6b. Street Number Name",
          required: false,
        },
        {
          id: "part1.6c.aptSteFlrNumber",
          type: "text",
          label: "6c. Apt Ste Flr Number",
          required: false,
        },
        {
          id: "part1.6d.cityOrTown",
          type: "text",
          label: "6d. City Or Town",
          required: false,
        },
        {
          id: "part1.6h.postalCode",
          type: "text",
          label: "6h. Postal Code",
          required: false,
        },
        {
          id: "part1.6f.zipCode",
          type: "text",
          label: "6f. Zip Code",
          required: false,
        },
        {
          id: "part1.6e.state",
          type: "text",
          label: "6e. State",
          required: false,
        },
        {
          id: "part1.6i.country",
          type: "text",
          label: "6i. Country",
          required: false,
        },
        {
          id: "part1.5a.familyName",
          type: "text",
          label: "5a. Family Name",
          required: false,
        },
        {
          id: "part1.5b.givenName",
          type: "text",
          label: "5b. Given Name",
          required: false,
        },
        {
          id: "part1.5c.middleName",
          type: "text",
          label: "5c. Middle Name",
          required: false,
        },
        {
          id: "part1.2.acctIdentifier",
          type: "text",
          label: "2. Acct Identifier",
          required: false,
        },
        {
          id: "part1.6g.province",
          type: "text",
          label: "6g. Province",
          required: false,
        },
        {
          id: "part1.checkbox6c_Unit",
          type: "checkbox",
          label: "P1 checkbox6c  Unit",
          required: false,
        },
        {
          id: "part1.checkbox6c_Unit",
          type: "checkbox",
          label: "P1 checkbox6c  Unit",
          required: false,
        },
        {
          id: "part1.checkbox6c_Unit",
          type: "text",
          label: "P1 checkbox6c  Unit",
          required: false,
        },
        {
          id: "part1.7a.streetNumberName",
          type: "text",
          label: "7a. Street Number Name",
          required: false,
        },
        {
          id: "part1.7c.cityOrTown",
          type: "text",
          label: "7c. City Or Town",
          required: false,
        },
        {
          id: "part1.7e.zipCode",
          type: "text",
          label: "7e. Zip Code",
          required: false,
        },
        {
          id: "part1.7b.aptSteFlrNumber",
          type: "text",
          label: "7b. Apt Ste Flr Number",
          required: false,
        },
        {
          id: "part1.7h.country",
          type: "text",
          label: "7h. Country",
          required: false,
        },
        {
          id: "part1.7g.postalCode",
          type: "text",
          label: "7g. Postal Code",
          required: false,
        },
        {
          id: "part1.7f.province",
          type: "checkbox",
          label: "7f. Province",
          required: false,
        },
        {
          id: "part1.checkbox7b_Unit",
          type: "checkbox",
          label: "P1 checkbox7b  Unit",
          required: false,
        },
        {
          id: "part1.checkbox7b_Unit",
          type: "checkbox",
          label: "P1 checkbox7b  Unit",
          required: false,
        },
        {
          id: "part1.checkbox7b_Unit",
          type: "text",
          label: "P1 checkbox7b  Unit",
          required: false,
        },
        {
          id: "part1.7d.state",
          type: "text",
          label: "7d. State",
          required: false,
        },
        {
          id: "part1.9.dateOfBirth",
          type: "text",
          label: "9. Date Of Birth",
          required: false,
        },
        {
          id: "part1.10.cityTownOfBirth",
          type: "text",
          label: "10. City Town Of Birth",
          required: false,
        },
        {
          id: "part1.11.countryofBirth",
          type: "text",
          label: "11. Countryof Birth",
          required: false,
        },
        {
          id: "part1.16.sSN",
          type: "text",
          label: "16. S S N",
          required: false,
        },
        {
          id: "part1.15.dateOfAdmission",
          type: "text",
          label: "15. Date Of Admission",
          required: false,
        },
        {
          id: "part1.14.classOfAdmission",
          type: "checkbox",
          label: "14. Class Of Admission",
          required: false,
        },
        {
          id: "part1.12.motherGivenName",
          type: "text",
          label: "12. Mother Given Name",
          required: false,
        },
        {
          id: "part1.13.fatherGivenName",
          type: "checkbox",
          label: "13. Father Given Name",
          required: false,
        },
        {
          id: "part1.8.male",
          type: "checkbox",
          label: "8. male",
          required: false,
        },
        {
          id: "part1.8.female",
          type: "checkbox",
          label: "8. female",
          required: false,
        },
        {
          id: "part1.3a.familyName",
          type: "text",
          label: "3a. Family Name",
          required: false,
        },
        {
          id: "part1.3b.givenName",
          type: "text",
          label: "3b. Given Name",
          required: false,
        },
        {
          id: "part1.3c.middleName",
          type: "text",
          label: "3c. Middle Name",
          required: false,
        },
      ],
    },
    {
      id: "section1",
      title: "Part 1: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "#area[1].p1.line1.aliennumber",
          type: "checkbox",
          label: "#area[1]. P1  Line1  Alien Number",
          required: false,
        },
        {
          id: "p5.checkbox1b",
          type: "text",
          label: "P5  Checkbox1b",
          required: false,
        },
        {
          id: "p5.checkbox1a",
          type: "checkbox",
          label: "P5  Checkbox1a",
          required: false,
        },
        {
          id: "p5.checkbox2",
          type: "text",
          label: "P5  Checkbox2",
          required: false,
        },
        {
          id: "p6.language",
          type: "text",
          label: "P6  Language",
          required: false,
        },
        {
          id: "#area[3].p1.line1.aliennumber",
          type: "text",
          label: "#area[3]. P1  Line1  Alien Number",
          required: false,
        },
      ],
    },
    {
      id: "part2",
      title: "Part 2: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "text",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox1",
          type: "checkbox",
          label: "P2 checkbox1",
          required: false,
        },
        {
          id: "part2.checkbox1",
          type: "checkbox",
          label: "P2 checkbox1",
          required: false,
        },
        {
          id: "part2.checkbox1",
          type: "checkbox",
          label: "P2 checkbox1",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "checkbox",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.checkbox2",
          type: "text",
          label: "P2 checkbox2",
          required: false,
        },
        {
          id: "part2.2h1.cityandState",
          type: "text",
          label: "2h1. Cityand State",
          required: false,
        },
        {
          id: "part2.checkbox3",
          type: "checkbox",
          label: "P2 checkbox3",
          required: false,
        },
        {
          id: "part2.checkbox3",
          type: "checkbox",
          label: "P2 checkbox3",
          required: false,
        },
        {
          id: "part2.checkbox3",
          type: "checkbox",
          label: "P2 checkbox3",
          required: false,
        },
        {
          id: "part2.checkbox3",
          type: "checkbox",
          label: "P2 checkbox3",
          required: false,
        },
        {
          id: "part2.checkbox3",
          type: "text",
          label: "P2 checkbox3",
          required: false,
        },
      ],
    },
    {
      id: "part3",
      title: "Part 3: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part3.1.locationAppliedVisa",
          type: "text",
          label: "1. Location Applied Visa",
          required: false,
        },
        {
          id: "part3.2.locationIssuedVisa",
          type: "checkbox",
          label: "2. Location Issued Visa",
          required: false,
        },
        {
          id: "part3.checkbox4",
          type: "checkbox",
          label: "P3 checkbox4",
          required: false,
        },
        {
          id: "part3.checkbox4",
          type: "checkbox",
          label: "P3 checkbox4",
          required: false,
        },
        {
          id: "part3.checkbox5",
          type: "checkbox",
          label: "P3 checkbox5",
          required: false,
        },
        {
          id: "part3.checkbox5",
          type: "text",
          label: "P3 checkbox5",
          required: false,
        },
        {
          id: "part3.8.heightFeet",
          type: "text",
          label: "8. Height Feet",
          required: false,
        },
        {
          id: "part3.8.heightInches",
          type: "checkbox",
          label: "8. Height Inches",
          required: false,
        },
        {
          id: "part3.9.heightInches1",
          type: "text",
          label: "9. Height Inches1",
          required: false,
        },
        {
          id: "part3.9.heightInches2",
          type: "text",
          label: "9. Height Inches2",
          required: false,
        },
        {
          id: "part3.9.heightInches3",
          type: "checkbox",
          label: "9. Height Inches3",
          required: false,
        },
        {
          id: "part3.checkbox6",
          type: "checkbox",
          label: "P3 checkbox6",
          required: false,
        },
        {
          id: "part3.checkbox6",
          type: "checkbox",
          label: "P3 checkbox6",
          required: false,
        },
        {
          id: "part3.checkbox7_Hawaiian",
          type: "checkbox",
          label: "P3 checkbox7  Hawaiian",
          required: false,
        },
        {
          id: "part3.checkbox7_Indian",
          type: "checkbox",
          label: "P3 checkbox7  Indian",
          required: false,
        },
        {
          id: "part3.checkbox7_White",
          type: "checkbox",
          label: "P3 checkbox7  White",
          required: false,
        },
        {
          id: "part3.checkbox7_Asian",
          type: "checkbox",
          label: "P3 checkbox7  Asian",
          required: false,
        },
        {
          id: "part3.checkbox7_Black",
          type: "checkbox",
          label: "P3 checkbox7  Black",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "checkbox",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.checkbox10",
          type: "text",
          label: "P3 checkbox10",
          required: false,
        },
        {
          id: "part3.3a1.cityandState",
          type: "text",
          label: "3a1. Cityand State",
          required: false,
        },
        {
          id: "part3.3a.destination",
          type: "checkbox",
          label: "3a. Destination",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
        {
          id: "part3.checkbox11",
          type: "checkbox",
          label: "P3 checkbox11",
          required: false,
        },
      ],
    },
    {
      id: "part4",
      title: "Part 4: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part4.checkbox1",
          type: "checkbox",
          label: "P4 checkbox1",
          required: false,
        },
        {
          id: "part4.checkbox1",
          type: "checkbox",
          label: "P4 checkbox1",
          required: false,
        },
        {
          id: "part4.checkbox1a",
          type: "text",
          label: "P4 checkbox1a",
          required: false,
        },
        {
          id: "part4.1a.accomodationRequested",
          type: "checkbox",
          label: "1a. Accomodation Requested",
          required: false,
        },
        {
          id: "part4.checkbox1b",
          type: "text",
          label: "P4 checkbox1b",
          required: false,
        },
        {
          id: "part4.1b.accomodationRequested",
          type: "checkbox",
          label: "1b. Accomodation Requested",
          required: false,
        },
        {
          id: "part4.checkbox1c",
          type: "text",
          label: "P4 checkbox1c",
          required: false,
        },
        {
          id: "part4.1c.accomodationRequested",
          type: "checkbox",
          label: "1c. Accomodation Requested",
          required: false,
        },
      ],
    },
    {
      id: "part5",
      title: "Part 5: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part5.1b.language",
          type: "checkbox",
          label: "1b. Language",
          required: false,
        },
        {
          id: "part5.2.nameofRepresentative",
          type: "text",
          label: "2. Nameof Representative",
          required: false,
        },
        {
          id: "part5.5.emailAddress",
          type: "text",
          label: "5. Email Address",
          required: false,
        },
        {
          id: "part5.3.daytimePhoneNumber",
          type: "text",
          label: "3. Daytime Phone Number",
          required: false,
        },
        {
          id: "part5.4.mobilePhoneNumber",
          type: "text",
          label: "4. Mobile Phone Number",
          required: false,
        },
        {
          id: "part5.6b.dateofSignature",
          type: "text",
          label: "6b. Dateof Signature",
          required: false,
        },
        {
          id: "part5.6a.signatureofApplicant",
          type: "text",
          label: "6a. Signatureof Applicant",
          required: false,
        },
      ],
    },
    {
      id: "part6",
      title: "Part 6: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part6.1b.interpretersGivenName",
          type: "text",
          label: "1b. Interpreters Given Name",
          required: false,
        },
        {
          id: "part6.1a.interpretersFamilyName",
          type: "text",
          label: "1a. Interpreters Family Name",
          required: false,
        },
        {
          id: "part6.2.nameofBusinessor",
          type: "text",
          label: "2. Nameof Businessor",
          required: false,
        },
        {
          id: "part6.3c.cityTown",
          type: "text",
          label: "3c. City Town",
          required: false,
        },
        {
          id: "part6.3a.streetNumberName",
          type: "text",
          label: "3a. Street Number Name",
          required: false,
        },
        {
          id: "part6.3b.aptSteFlrNumber",
          type: "text",
          label: "3b. Apt Ste Flr Number",
          required: false,
        },
        {
          id: "part6.3f.province",
          type: "text",
          label: "3f. Province",
          required: false,
        },
        {
          id: "part6.3e.zipCode",
          type: "text",
          label: "3e. Zip Code",
          required: false,
        },
        {
          id: "part6.3d.state",
          type: "text",
          label: "3d. State",
          required: false,
        },
        {
          id: "part6.3h.country",
          type: "text",
          label: "3h. Country",
          required: false,
        },
        {
          id: "part6.3g.postalCode",
          type: "checkbox",
          label: "3g. Postal Code",
          required: false,
        },
        {
          id: "part6.checkbox3b_Unit",
          type: "checkbox",
          label: "P6 checkbox3b  Unit",
          required: false,
        },
        {
          id: "part6.checkbox3b_Unit",
          type: "checkbox",
          label: "P6 checkbox3b  Unit",
          required: false,
        },
        {
          id: "part6.checkbox3b_Unit",
          type: "text",
          label: "P6 checkbox3b  Unit",
          required: false,
        },
        {
          id: "part6.5.interpretersEmailAddress",
          type: "text",
          label: "5. Interpreters Email Address",
          required: false,
        },
        {
          id: "part6.4.interpretersDaytimePhoneNumber",
          type: "text",
          label: "4. Interpreters Daytime Phone Number",
          required: false,
        },
        {
          id: "part6.4.interpretersDaytimePhoneNumber",
          type: "text",
          label: "4. Interpreters Daytime Phone Number",
          required: false,
        },
        {
          id: "part6.6b.dateofSignature",
          type: "text",
          label: "6b. Dateof Signature",
          required: false,
        },
        {
          id: "part6.6a.signature",
          type: "text",
          label: "6a. Signature",
          required: false,
        },
      ],
    },
    {
      id: "part7",
      title: "Part 7: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part7.1a.familyName",
          type: "text",
          label: "1a. Family Name",
          required: false,
        },
        {
          id: "part7.1b.preparersGivenName",
          type: "text",
          label: "1b. Preparers Given Name",
          required: false,
        },
        {
          id: "part7.2.nameofBusinessor",
          type: "text",
          label: "2. Nameof Businessor",
          required: false,
        },
        {
          id: "part7.3c.cityTown",
          type: "text",
          label: "3c. City Town",
          required: false,
        },
        {
          id: "part7.3a.streetNumberName",
          type: "text",
          label: "3a. Street Number Name",
          required: false,
        },
        {
          id: "part7.3b.aptSteFlrNumber",
          type: "text",
          label: "3b. Apt Ste Flr Number",
          required: false,
        },
        {
          id: "part7.3f.province",
          type: "text",
          label: "3f. Province",
          required: false,
        },
        {
          id: "part7.3e.zipCode",
          type: "text",
          label: "3e. Zip Code",
          required: false,
        },
        {
          id: "part7.3d.state",
          type: "text",
          label: "3d. State",
          required: false,
        },
        {
          id: "part7.3h.country",
          type: "text",
          label: "3h. Country",
          required: false,
        },
        {
          id: "part7.3g.postalCode",
          type: "checkbox",
          label: "3g. Postal Code",
          required: false,
        },
        {
          id: "part7.checkbox3b_Unit",
          type: "checkbox",
          label: "P7 checkbox3b  Unit",
          required: false,
        },
        {
          id: "part7.checkbox3b_Unit",
          type: "checkbox",
          label: "P7 checkbox3b  Unit",
          required: false,
        },
        {
          id: "part7.checkbox3b_Unit",
          type: "text",
          label: "P7 checkbox3b  Unit",
          required: false,
        },
        {
          id: "part7.6.preparersEmailAddress",
          type: "text",
          label: "6. Preparers Email Address",
          required: false,
        },
        {
          id: "part7.4.preparersDaytimePhoneNumber",
          type: "text",
          label: "4. Preparers Daytime Phone Number",
          required: false,
        },
        {
          id: "part7.5.preparersFaxNumber",
          type: "checkbox",
          label: "5. Preparers Fax Number",
          required: false,
        },
        {
          id: "part7.checkbox7",
          type: "checkbox",
          label: "P7 checkbox7",
          required: false,
        },
        {
          id: "part7.checkbox7",
          type: "checkbox",
          label: "P7 checkbox7",
          required: false,
        },
        {
          id: "part7.checkbox7Extend",
          type: "checkbox",
          label: "P7 checkbox7 Extend",
          required: false,
        },
        {
          id: "part7.checkbox7Extend",
          type: "text",
          label: "P7 checkbox7 Extend",
          required: false,
        },
        {
          id: "part7.8a.signatureofPreparer",
          type: "text",
          label: "8a. Signatureof Preparer",
          required: false,
        },
        {
          id: "part7.8b.dateofSignature",
          type: "text",
          label: "8b. Dateof Signature",
          required: false,
        },
      ],
    },
    {
      id: "part8",
      title: "Part 8: Information",
      description: "TODO: Add section description",
      questions: [
        {
          id: "part8.3d.additionalInfo",
          type: "text",
          label: "3d. Additional Info",
          required: false,
        },
        {
          id: "part8.5a.pageNumber",
          type: "text",
          label: "5a. Page Number",
          required: false,
        },
        {
          id: "part8.5b.partNumber",
          type: "text",
          label: "5b. Part Number",
          required: false,
        },
        {
          id: "part8.5c.itemNumber",
          type: "text",
          label: "5c. Item Number",
          required: false,
        },
        {
          id: "part8.5d.additionalInfo",
          type: "text",
          label: "5d. Additional Info",
          required: false,
        },
        {
          id: "part8.4d.additionalInfo",
          type: "text",
          label: "4d. Additional Info",
          required: false,
        },
        {
          id: "part8.3a.pageNumber",
          type: "text",
          label: "3a. Page Number",
          required: false,
        },
        {
          id: "part8.3b.partNumber",
          type: "text",
          label: "3b. Part Number",
          required: false,
        },
        {
          id: "part8.3c.itemNumber",
          type: "text",
          label: "3c. Item Number",
          required: false,
        },
        {
          id: "part8.4a.pageNumber",
          type: "text",
          label: "4a. Page Number",
          required: false,
        },
        {
          id: "part8.4b.partNumber",
          type: "text",
          label: "4b. Part Number",
          required: false,
        },
        {
          id: "part8.4c.itemNumber",
          type: "text",
          label: "4c. Item Number",
          required: false,
        },
        {
          id: "part8.5a.pageNumber",
          type: "text",
          label: "5a. Page Number",
          required: false,
        },
        {
          id: "part8.5b.partNumber",
          type: "text",
          label: "5b. Part Number",
          required: false,
        },
        {
          id: "part8.5c.itemNumber",
          type: "text",
          label: "5c. Item Number",
          required: false,
        },
        {
          id: "part8.5d.additionalInfo",
          type: "text",
          label: "5d. Additional Info",
          required: false,
        },
        {
          id: "part8.5a.pageNumber",
          type: "text",
          label: "5a. Page Number",
          required: false,
        },
        {
          id: "part8.5b.partNumber",
          type: "text",
          label: "5b. Part Number",
          required: false,
        },
        {
          id: "part8.5c.itemNumber",
          type: "text",
          label: "5c. Item Number",
          required: false,
        },
        {
          id: "part8.5d.additionalInfo",
          type: "text",
          label: "5d. Additional Info",
          required: false,
        },
      ],
    },
  ],
  requiredDocuments: [
    "TODO: List required documents",
  ],
  instructions: [
    "TODO: Add instructions",
  ],
};

// Add to FORMS_REGISTRY array:
// I90UNLOCKED_DEFINITION,
